export const SHIPPING_RATE_LABELS = {
  SEARCH_PLACEHOLDER: 'Tên hoặc khu vực...',
  BTN_ADD: 'Thêm bảng giá',
  SEARCH_LABEL: 'Tìm kiếm',
  TITLE_NAME: 'Tên bảng giá',
  TITLE_AREA: 'Khu vực',
  TITLE_RATE: 'Giá cước',
  TITLE_MIN_CHARGE: 'Phí tối thiểu',
  TITLE_STATUS: 'Trạng thái',
  TITLE_ACTIONS: 'Thao tác',
  STATUS_ACTIVE: 'Đang dùng',
  STATUS_INACTIVE: 'Ngừng dùng', // or 'Ngừng'
  BTN_EDIT: 'Sửa',
  BTN_DELETE: 'Xoá',
  BTN_CANCEL: 'Hủy',
  BTN_CREATE: 'Tạo mới',
  BTN_UPDATE: 'Cập nhật',
  BTN_SAVING: 'Đang lưu...',
  ERROR_PREFIX: 'Lỗi: ',
  ERROR_LOAD: 'Lỗi tải dữ liệu: ',
  CONFIRM_DELETE: 'Xoá bảng giá',
  EMPTY_TITLE_SEARCH: 'Không tìm thấy bảng giá phù hợp',
  EMPTY_TITLE: 'Chưa có bảng giá cước nào',
  EMPTY_DESC_SEARCH: 'Thử điều chỉnh bộ lọc.',
  EMPTY_DESC: 'Bấm "+ Thêm bảng giá" để tạo giá cước vận chuyển.',
  FORM_NAME: 'Tên bảng giá',
  FORM_AREA: 'Khu vực giao',
  FORM_RATE_TRIP: 'Giá cố định/chuyến (VNĐ)',
  FORM_RATE_METER: 'Giá theo mét (VNĐ/m)',
  FORM_RATE_KG: 'Giá theo kg (VNĐ/kg)',
  FORM_LOADING_FEE: 'Phí bốc xếp (VNĐ)',
  FORM_MIN_CHARGE: 'Phí tối thiểu (VNĐ)',
  FORM_STATUS: 'Trạng thái',
  FORM_NOTES: 'Ghi chú',
  SUFFIX_TRIP: ' đ/chuyến',
  SUFFIX_METER: ' đ/m',
  SUFFIX_KG: ' đ/kg',
  SUFFIX_VND: ' đ',
  PLACEHOLDER_NAME: 'VD: Tuyến HCM - Bình Dương',
  PLACEHOLDER_AREA: 'VD: Bình Dương',
  PLACEHOLDER_NOTES: 'Ghi chú thêm...',
  TEXT_LOADING_FEE: 'Bốc xếp',
} as const;
