export const PRINT_TEMPLATE_LABELS = {
  TITLE: 'Kho Mẫu In Chứng Từ',
  SUBTITLE:
    'Quản lý, cấu hình và xem trước tất cả mẫu chứng từ xuất kho, lệnh dệt và tem nhãn',
  BTN_CREATE: 'Tạo Mẫu In Mới',
  BTN_UTILITIES: 'Tiện Ích',
  BTN_IMPORT: 'Nhập Mẫu JSON',
  BTN_EXPORT: 'Xuất File Mẫu',
  SEARCH_PLACEHOLDER: 'Tìm theo tên mẫu, mã mẫu...',
  FILTER_DOC_TYPE: 'Loại chứng từ',
  FILTER_PRINTER_TYPE: 'Loại máy in',
  FILTER_STATUS: 'Trạng thái',
  ALL_DOCS: 'Tất cả chứng từ',
  ALL_PRINTERS: 'Tất cả thiết bị in',
  STATUS_ALL: 'Tất cả trạng thái',
  STATUS_ACTIVE: 'Đang sử dụng',
  STATUS_DRAFT: 'Bản nháp',
  STATUS_ARCHIVED: 'Đã lưu trữ',
  DEFAULT_BADGE: 'Mặc Định',
  SYSTEM_BADGE: 'Mẫu Gốc',
  CUSTOM_BADGE: 'Tùy Chỉnh',
  BTN_QUICK_PREVIEW: 'Xem trước bản in',
  BTN_OPEN_DESIGNER: 'Chỉnh sửa Designer',
  BTN_DUPLICATE: 'Nhân Bản Mẫu',
  BTN_SET_DEFAULT: 'Đặt Làm Mặc Định',
  BTN_ARCHIVE: 'Lưu Trữ Mẫu',
  BTN_RESTORE: 'Khôi Phục Mẫu',
  BTN_DELETE: 'Xóa Mẫu',
  BTN_TEST_PRINT: 'In Thử Ngay (PDF)',
  BTN_CANCEL: 'Hủy Bỏ',
  BTN_CONFIRM: 'Xác Nhận',
  BTN_SAVE: 'Lưu Cấu Hình',
  MODAL_CREATE_TITLE: 'Tạo Mẫu In Chứng Từ Mới',
  MODAL_DUPLICATE_TITLE: 'Nhân Bản Mẫu In',
  FIELD_TEMPLATE_NAME: 'Tên mẫu in',
  FIELD_TEMPLATE_CODE: 'Mã định danh',
  FIELD_DOC_TYPE: 'Loại chứng từ',
  FIELD_PRINTER_TYPE: 'Thiết bị in dự kiến',
  FIELD_PAPER_FORMAT: 'Khổ giấy',
  FIELD_DESCRIPTION: 'Mô tả ghi chú',
  PREVIEW_MODAL_TITLE: 'Bản In Thử Nghiệm (Print Preview)',
  FIXTURE_LABEL: 'Dữ liệu thử nghiệm:',
  FIXTURE_SHORT: 'Đơn ngắn (3 cây vải)',
  FIXTURE_LONG: 'Đơn dài (15 cây vải)',
  EMPTY_TITLE: 'Không tìm thấy mẫu in nào',
  EMPTY_DESC:
    'Thử thay đổi từ khóa tìm kiếm hoặc bộ lọc trạng thái. Bạn có muốn tạo mẫu in mới không?',
} as const;

export const PRINT_DOC_TABS = [
  { key: 'ALL', label: 'Tất cả' },
  { key: 'shipment_delivery', label: 'Phiếu Xuất Kho' },
  { key: 'inventory_receipt', label: 'Phiếu Nhập Kho' },
  { key: 'production_order', label: 'Lệnh Sản Xuất' },
  { key: 'roll_tag', label: 'Tem Cây Vải' },
  { key: 'sales_statement', label: 'Báo Cáo & Bảng Kê' },
] as const;

export const PRINT_TEMPLATE_MESSAGES = {
  CREATE_SUCCESS: 'Đã tạo mẫu in mới thành công',
  UPDATE_SUCCESS: 'Đã cập nhật mẫu in thành công',
  DUPLICATE_SUCCESS: 'Đã nhân bản mẫu in thành công',
  SET_DEFAULT_SUCCESS: 'Đã đặt mẫu in làm mặc định cho loại chứng từ này',
  ARCHIVE_SUCCESS: 'Đã chuyển mẫu in vào lưu trữ',
  RESTORE_SUCCESS: 'Đã khôi phục mẫu in hoạt động',
  DELETE_SUCCESS: 'Đã xóa mẫu in',
  SAVE_ERROR: 'Lỗi khi lưu cấu hình mẫu in:',
} as const;
