import type { DocumentType, PrinterProfileType } from '@/domain/print';
import type { VPOption } from '@/shared/components';

export const DOC_TYPE_OPTIONS: VPOption<DocumentType>[] = [
  { value: 'shipment_delivery', label: 'Phiếu Xuất Kho' },
  { value: 'inventory_receipt', label: 'Phiếu Nhập Kho' },
  { value: 'production_order', label: 'Lệnh Sản Xuất' },
  { value: 'roll_tag', label: 'Tem Cây Vải' },
  { value: 'sales_statement', label: 'Bảng Kê Giao Hàng' },
  { value: 'payment_receipt', label: 'Phiếu Thu Tiền' },
];

export const PRINTER_TYPE_OPTIONS: VPOption<PrinterProfileType>[] = [
  { value: 'dot_matrix', label: 'In Kim (3 liên)' },
  { value: 'laser', label: 'Laser / PDF' },
  { value: 'thermal_receipt', label: 'In Nhiệt K80' },
  { value: 'thermal_label', label: 'Tem Barcode' },
];

export const PRINT_TEMPLATE_LABELS = {
  TITLE: 'Kho Mẫu In Chứng Từ',
  SUBTITLE:
    'Quản lý, cấu hình và xem trước tất cả mẫu chứng từ xuất kho, lệnh dệt và tem nhãn',
  BTN_CREATE: 'Tạo Mẫu In Mới',
  BTN_UTILITIES: 'Tiện Ích',
  BTN_IMPORT: 'Nhập Mẫu JSON',
  BTN_EXPORT: 'Xuất File Mẫu',
  SEARCH_PLACEHOLDER: 'Tìm theo tên mẫu, mã mẫu...',
  FILTER_DOC_TYPE: 'Loại chứng từ',
  FILTER_PRINTER_TYPE: 'Loại máy in',
  FILTER_STATUS: 'Trạng thái',
  ALL_DOCS: 'Tất cả chứng từ',
  ALL_PRINTERS: 'Tất cả thiết bị in',
  STATUS_ALL: 'Tất cả trạng thái',
  STATUS_ACTIVE: 'Đang sử dụng',
  STATUS_DRAFT: 'Bản nháp',
  STATUS_ARCHIVED: 'Đã lưu trữ',
  DEFAULT_BADGE: 'Mặc Định',
  SYSTEM_BADGE: 'Mẫu Gốc',
  CUSTOM_BADGE: 'Tùy Chỉnh',
  BTN_QUICK_PREVIEW: 'Xem trước bản in',
  BTN_OPEN_DESIGNER: 'Chỉnh sửa Designer',
  BTN_DUPLICATE: 'Nhân Bản Mẫu',
  BTN_SET_DEFAULT: 'Đặt Làm Mặc Định',
  BTN_ARCHIVE: 'Lưu Trữ Mẫu',
  BTN_RESTORE: 'Khôi Phục Mẫu',
  BTN_DELETE: 'Xóa Mẫu',
  BTN_TEST_PRINT: 'In Thử Ngay (PDF)',
  BTN_CANCEL: 'Hủy Bỏ',
  BTN_CONFIRM: 'Xác Nhận',
  BTN_SAVE: 'Lưu Cấu Hình',
  MODAL_CREATE_TITLE: 'Tạo Mẫu In Chứng Từ Mới',
  MODAL_DUPLICATE_TITLE: 'Nhân Bản Mẫu In',
  FIELD_TEMPLATE_NAME: 'Tên mẫu in',
  FIELD_TEMPLATE_CODE: 'Mã định danh',
  FIELD_DOC_TYPE: 'Loại chứng từ',
  FIELD_PRINTER_TYPE: 'Thiết bị in dự kiến',
  FIELD_PAPER_FORMAT: 'Khổ giấy',
  FIELD_DESCRIPTION: 'Mô tả ghi chú',
  PREVIEW_MODAL_TITLE: 'Bản In Thử Nghiệm (Print Preview)',
  FIXTURE_LABEL: 'Dữ liệu thử nghiệm:',
  FIXTURE_SHORT: 'Đơn ngắn (3 cây vải)',
  FIXTURE_LONG: 'Đơn dài (15 cây vải)',
  EMPTY_TITLE: 'Không tìm thấy mẫu in nào',
  EMPTY_DESC:
    'Thử thay đổi từ khóa tìm kiếm hoặc bộ lọc trạng thái. Bạn có muốn tạo mẫu in mới không?',
} as const;

export const PRINT_DOC_TABS = [
  { key: 'ALL', label: 'Tất cả' },
  { key: 'shipment_delivery', label: 'Phiếu Xuất Kho' },
  { key: 'inventory_receipt', label: 'Phiếu Nhập Kho' },
  { key: 'production_order', label: 'Lệnh Sản Xuất' },
  { key: 'roll_tag', label: 'Tem Cây Vải' },
  { key: 'sales_statement', label: 'Báo Cáo & Bảng Kê' },
] as const;

export const PRINT_TEMPLATE_MESSAGES = {
  CREATE_SUCCESS: 'Đã tạo mẫu in mới thành công',
  UPDATE_SUCCESS: 'Đã cập nhật mẫu in thành công',
  DUPLICATE_SUCCESS: 'Đã nhân bản mẫu in thành công',
  SET_DEFAULT_SUCCESS: 'Đã đặt mẫu in làm mặc định cho loại chứng từ này',
  ARCHIVE_SUCCESS: 'Đã chuyển mẫu in vào lưu trữ',
  RESTORE_SUCCESS: 'Đã khôi phục mẫu in hoạt động',
  DELETE_SUCCESS: 'Đã xóa mẫu in',
  SAVE_ERROR: 'Lỗi khi lưu cấu hình mẫu in:',
} as const;

export const PREVIEW_SHIPMENT_FIXTURE = {
  id: 'fixture-shipment-preview',
  shipment_number: 'XK2604-0001',
  order_id: 'order-1',
  customer_id: 'customer-1',
  shipment_date: '2026-04-02',
  delivery_address: '80A Trương Phước Phan, Phường Bình Trị Đông, TP.HCM',
  carrier: 'Xe tải Vĩnh Phát (51C-123.45)',
  tracking_number: null,
  status: 'shipped',
  notes: 'Giao trong giờ hành chính. Liên hệ trước khi đến 15 phút.',
  created_by: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  last_chat_at: null,
  delivery_staff_id: null,
  shipping_rate_id: null,
  shipping_cost: 0,
  loading_fee: 0,
  total_weight_kg: null,
  total_meters: null,
  vehicle_info: null,
  prepared_at: null,
  shipped_at: null,
  delivered_at: null,
  delivery_proof: null,
  receiver_name: 'Trần Văn B',
  receiver_phone: '0909 888 999',
  employee_id: null,
  tenant_id: null,
  journey_status: null,
  signed_at: null,
  customer_signature_url: null,
  proof_photos: null,
  orders: { order_number: 'DH2604-0012' },
  customers: {
    name: 'Công ty TNHH May Mặc Thời Trang Á Đông',
    code: 'KH-ADONG-01',
    address: '456 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    phone: '0909 123 456',
    contact_person: 'Nguyễn Thị Thu',
  },
  shipment_items: [
    {
      id: 'item-1',
      shipment_id: 'fixture-shipment-preview',
      finished_roll_id: 'roll-101',
      fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
      color_name: 'Trắng Sứ (W-01)',
      quantity: 120.5,
      unit: 'm',
      roll_number: 'C01',
      roll_length_m: null,
      warehouse_location: null,
      notes: 'Đạt chuẩn kiểm kim',
      price_per_meter: null,
      sort_order: 1,
      tenant_id: null,
      total_amount: null,
    },
    {
      id: 'item-2',
      shipment_id: 'fixture-shipment-preview',
      finished_roll_id: 'roll-102',
      fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
      color_name: 'Trắng Sứ (W-01)',
      quantity: 118.0,
      unit: 'm',
      roll_number: 'C02',
      roll_length_m: null,
      warehouse_location: null,
      notes: null,
      price_per_meter: null,
      sort_order: 2,
      tenant_id: null,
      total_amount: null,
    },
    {
      id: 'item-3',
      shipment_id: 'fixture-shipment-preview',
      finished_roll_id: 'roll-103',
      fabric_type: 'Vải CVC 65/35 Cá Sấu 4 chiều',
      color_name: 'Xanh Navy (NV-09)',
      quantity: 145.2,
      unit: 'm',
      roll_number: 'C03',
      roll_length_m: null,
      warehouse_location: null,
      notes: null,
      price_per_meter: null,
      sort_order: 3,
      tenant_id: null,
      total_amount: null,
    },
  ],
} as unknown as import('@/domain/shipments/types').ShipmentDocument;
