export const SUPPLIER_PORTAL_LABELS = {
  // ── Common ──
  FILTER_ALL: 'Tất cả',
  LOADING: 'Đang tải dữ liệu...',
  COMPANY_NAME: 'Vinh Phát Hưng',
  LINK_INVALID_DESC:
    'Liên kết có thể không chính xác hoặc yêu cầu báo giá này đã đóng. Vui lòng liên hệ với người phụ trách mua hàng.',
  PRINT_BTN: 'In / Tải PDF',

  // ── RFQ / Quote Form ──
  PAGE_TITLE: 'Gửi báo giá',
  PAGE_SUBTITLE: 'Cổng thông tin tiếp nhận báo giá từ Nhà cung cấp',
  RFQ_INFO: 'Thông tin yêu cầu báo giá',
  SUPPLIER_INFO: 'Thông tin liên hệ của bạn',
  ITEMS_INFO: 'Chi tiết báo giá',

  FORM_NAME: 'Tên Công ty / Người liên hệ',
  FORM_NAME_PLACEHOLDER: 'Nhập tên hoặc công ty...',
  FORM_PHONE: 'Số điện thoại',
  FORM_PHONE_PLACEHOLDER: 'Dùng để xác thực báo giá của bạn...',
  FORM_NOTES: 'Ghi chú chung',
  FORM_NOTES_PLACEHOLDER: 'Điều kiện thanh toán, thời gian giao hàng...',

  COL_MATERIAL: 'Tên vật tư',
  COL_SPECS: 'Quy cách',
  COL_QTY_REQ: 'SL Yêu cầu',
  COL_QTY_OFFERED: 'SL Cung cấp',
  COL_PRICE: 'Đơn giá (VND)',
  COL_ITEM_NOTES: 'Ghi chú',

  SUBMIT_BTN: 'Gửi Báo Giá',
  SUBMITTING_BTN: 'Đang gửi...',

  SUCCESS_TITLE: 'Gửi báo giá thành công!',
  SUCCESS_DESC:
    'Cảm ơn bạn đã gửi báo giá. Bộ phận Mua hàng sẽ liên hệ lại với bạn sớm nhất.',
  ERROR_NOT_FOUND: 'Không tìm thấy yêu cầu báo giá hoặc đợt báo giá đã đóng.',
  ERROR_REQUIRED_FIELDS: 'Vui lòng điền đủ Tên và Số điện thoại liên hệ.',
  ERROR_NO_ITEMS: 'Vui lòng nhập đơn giá cho ít nhất 1 vật tư.',

  LABEL_RFQ_CODE: 'Mã Yêu cầu',
  LABEL_DEADLINE: 'Hạn chót báo giá',
  LABEL_TITLE: 'Tiêu đề',
  LABEL_NOTES_FROM_BUYER: 'Ghi chú từ bộ phận Mua hàng:',
  LABEL_REQUIRED: 'Yêu cầu',
  LABEL_CURRENCY: 'VND',
  LABEL_ITEM_NOTES_FULL: 'Ghi chú vật tư (Quy cách thay thế, thương hiệu...)',
  PLACEHOLDER_ITEM_NOTES: 'Ghi chú thêm nếu cần...',
  PLACEHOLDER_QTY: 'Có thể cung cấp...',
  PLACEHOLDER_PRICE: '0',
  ERROR_SUBMIT: 'Không thể gửi báo giá. Vui lòng thử lại sau.',
  LOADING_RFQ: 'Đang tải thông tin yêu cầu báo giá...',
  PRINT_RFQ: 'In báo giá',

  // ── PO Detail / Page ──
  LOADING_PO: 'Đang tải thông tin đơn hàng...',
  PO_NOT_FOUND_TITLE: 'Không tìm thấy đơn hàng',
  PO_NOT_FOUND_DESC: 'Đơn hàng không tồn tại hoặc bạn không có quyền truy cập.',
  PO_LOAD_ERROR_TITLE: 'Lỗi tải thông tin Đơn hàng',
  PO_PUBLIC_NOT_FOUND_TITLE: 'Không tìm thấy thông tin Đơn đặt hàng',
  PO_PUBLIC_NOT_FOUND_DESC:
    'Liên kết có thể không chính xác hoặc đơn hàng không tồn tại.',
  PO_CONFIRM_SUCCESS: 'Đã xác nhận đơn hàng thành công',
  PO_CONFIRM_ERROR: 'Có lỗi xảy ra khi xác nhận đơn hàng',
  PO_REJECT_SUCCESS: 'Đã từ chối đơn hàng thành công',
  PO_REJECT_ERROR: 'Có lỗi xảy ra khi từ chối đơn hàng',

  // ── POViewer (detail card) ──
  PO_HEADER_PREFIX: 'ĐƠN ĐẶT HÀNG',
  PO_STATUS_CONFIRMED: 'Đã xác nhận',
  PO_STATUS_REJECTED: 'Đã từ chối',
  PO_PRINT: 'In đơn hàng',
  PO_CONFIRMED_BANNER: 'Đơn hàng đã được xác nhận',
  PO_REJECTED_BANNER: 'Bạn đã từ chối đơn hàng này',
  PO_CANCELLED_BANNER: 'Đơn hàng đã bị hủy hoặc từ chối',
  PO_SECTION_INFO: 'THÔNG TIN CHUNG',
  PO_LABEL_SUPPLIER: 'Nhà cung cấp',
  PO_LABEL_ORDER_DATE: 'Ngày đặt',
  PO_LABEL_TOTAL: 'Tổng cộng (VND)',
  PO_SECTION_NOTES: 'GHI CHÚ TỪ NGƯỜI MUA',
  PO_SECTION_ITEMS: 'DANH SÁCH MẶT HÀNG',
  PO_ITEM_QTY: 'Số lượng:',
  PO_ITEM_PRICE: 'Đơn giá:',
  PO_ATTACHMENTS_TITLE: 'Tài liệu đính kèm',
  PO_ATTACHMENT_FALLBACK: 'Tài liệu',
  PO_RESPONSE_TITLE: 'Phản hồi đơn hàng',
  PO_RESPONSE_DESC:
    'Vui lòng kiểm tra kỹ thông tin đơn hàng, số lượng và đơn giá trước khi phản hồi.',
  PO_CONFIRM_BTN: 'XÁC NHẬN ĐƠN ĐẶT HÀNG',
  PO_CANNOT_FULFILL: 'Không thể đáp ứng',
  PO_REJECT_REASON_LABEL: 'Lý do không thể đáp ứng',
  PO_REJECT_REASON_PLACEHOLDER:
    'VD: Không đủ hàng tồn kho, sai giá, sai ngày giao...',
  PO_BTN_BACK: 'Quay lại',
  PO_BTN_SEND_RESPONSE: 'Gửi phản hồi',

  // ── PO Stepper Steps ──
  STEP_PO_SENT: 'Gửi đơn',
  STEP_PO_CONFIRMED: 'Xác nhận',
  STEP_PO_DELIVERING: 'Giao hàng',
  STEP_PO_COMPLETED: 'Hoàn thành',

  // ── RFQ Stepper Steps ──
  STEP_RFQ_OPEN: 'Tiếp nhận RFQ',
  STEP_RFQ_SUBMITTED: 'Gửi báo giá',
  STEP_RFQ_CLOSED: 'Đánh giá & Duyệt',

  // ── PO List ──
  PO_LIST_TITLE: 'Đơn đặt hàng (PO)',
  PO_LIST_DESC: 'Quản lý các đơn đặt hàng từ Vĩnh Phát ERP',
  PO_LIST_CARD_TITLE: 'Danh sách đơn hàng',
  PO_LIST_COL_CODE: 'Mã Đơn',
  PO_LIST_COL_DATE: 'Ngày Đặt',
  PO_LIST_COL_EXPECTED: 'Ngày Giao Dự Kiến',
  PO_LIST_COL_TOTAL: 'Tổng Tiền',
  PO_LIST_COL_STATUS: 'Trạng Thái',
  PO_LIST_EMPTY: 'Chưa có đơn đặt hàng nào',
  PO_LIST_STATUS_DRAFT: 'Bản nháp',
  PO_LIST_STATUS_PENDING: 'Chờ duyệt',
  PO_LIST_STATUS_APPROVED: 'Đã duyệt',
  PO_LIST_STATUS_SENT: 'Đã gửi',
  PO_LIST_STATUS_CONFIRMED: 'Đã xác nhận',
  PO_LIST_STATUS_REJECTED: 'Đã từ chối',
  PO_LIST_STATUS_COMPLETED: 'Đã hoàn thành',
  PO_LIST_STATUS_CANCELLED: 'Đã hủy/Từ chối',

  // ── RFQ List ──
  RFQ_LIST_TITLE: 'Yêu cầu báo giá (RFQ)',
  RFQ_LIST_DESC: 'Danh sách các yêu cầu báo giá từ Vĩnh Phát ERP',
  RFQ_LIST_CARD_TITLE: 'Danh sách yêu cầu báo giá',
  RFQ_LIST_COL_CODE: 'Mã RFQ',
  RFQ_LIST_COL_TITLE: 'Tiêu đề',
  RFQ_LIST_COL_DEADLINE: 'Hạn chót',
  RFQ_LIST_COL_STATUS: 'Trạng thái',
  RFQ_LIST_EMPTY: 'Chưa có yêu cầu báo giá nào',
  RFQ_LIST_STATUS_OPEN: 'Đang mở',
  RFQ_LIST_STATUS_CLOSED: 'Đã đóng',

  // ── Profile ──
  PROFILE_ERROR_NO_SUPPLIER: 'Không tìm thấy thông tin nhà cung cấp',
  PROFILE_TITLE: 'Hồ sơ nhà cung cấp',
  PROFILE_LABEL_NAME: 'Tên công ty / Nhà cung cấp *',
  PROFILE_PLACEHOLDER_NAME: 'Nhập tên nhà cung cấp',
  PROFILE_LABEL_TAX: 'Mã số thuế',
  PROFILE_PLACEHOLDER_TAX: 'Nhập mã số thuế',
  PROFILE_LABEL_CONTACT: 'Người liên hệ',
  PROFILE_PLACEHOLDER_CONTACT: 'Nhập tên người liên hệ',
  PROFILE_LABEL_PHONE: 'Số điện thoại',
  PROFILE_PLACEHOLDER_PHONE: 'Nhập số điện thoại',
  PROFILE_LABEL_EMAIL: 'Email',
  PROFILE_PLACEHOLDER_EMAIL: 'Nhập địa chỉ email',
  PROFILE_LABEL_ADDRESS: 'Địa chỉ',
  PROFILE_PLACEHOLDER_ADDRESS: 'Nhập địa chỉ công ty',
  PROFILE_SAVING: 'Đang lưu...',
  PROFILE_SAVE: 'Lưu thay đổi',
  PROFILE_UPDATE_SUCCESS: 'Cập nhật hồ sơ thành công',
  PROFILE_UPDATE_ERROR: 'Có lỗi xảy ra khi cập nhật hồ sơ',

  // ── Invoices ──
  INVOICES_TITLE: 'Hóa đơn chờ thanh toán',
  INVOICES_DESC: 'Danh sách các hóa đơn hoặc chứng từ chưa được thanh toán đủ.',
  INVOICES_CARD_TITLE: 'Chứng từ nợ',
  INVOICES_COL_CODE: 'Mã Chứng Từ',
  INVOICES_COL_TYPE: 'Loại',
  INVOICES_COL_DATE: 'Ngày Ghi Nhận',
  INVOICES_COL_TOTAL: 'Tổng Tiền',
  INVOICES_COL_REMAINING: 'Còn Lại (Nợ)',
  INVOICES_EMPTY: 'Không có hóa đơn nợ nào',

  // ── Debt ──
  DEBT_TITLE: 'Công nợ',
  DEBT_DESC: 'Quản lý số dư công nợ và lịch sử giao dịch.',
  DEBT_TOTAL_ACCRUED: 'Tổng phát sinh nợ',
  DEBT_TOTAL_PAID: 'Tổng đã thanh toán',
  DEBT_BALANCE: 'Công nợ hiện tại (Chờ thanh toán)',
  DEBT_HISTORY_TITLE: 'Lịch sử giao dịch',
  DEBT_COL_TIME: 'Thời Gian',
  DEBT_COL_TYPE: 'Loại GD',
  DEBT_COL_REFERENCE: 'Tham Chiếu',
  DEBT_COL_DEBIT: 'Nợ Phát Sinh',
  DEBT_COL_CREDIT: 'Đã Thanh Toán',
  DEBT_EMPTY: 'Chưa có giao dịch công nợ nào',
  DEBT_TYPE_PURCHASE: 'Mua hàng (Nợ tăng)',
  DEBT_TYPE_PAYMENT: 'Thanh toán (Nợ giảm)',
  DEBT_TYPE_ADJUSTMENT: 'Điều chỉnh',

  // ── Dashboard ──
  DASHBOARD_GREETING_MORNING: 'Chào buổi sáng,',
  DASHBOARD_GREETING_AFTERNOON: 'Chào buổi chiều,',
  DASHBOARD_GREETING_EVENING: 'Chào buổi tối,',
  DASHBOARD_SUBTITLE: 'Tổng quan hoạt động cung cấp của bạn.',
  DASHBOARD_PORTAL_LABEL: 'Cổng nhà cung cấp',
  DASHBOARD_BRAND: 'Vĩnh Phát ERP',
  DASHBOARD_NEW_PO: 'Đơn hàng mới (PO)',
  DASHBOARD_NEW_PO_SUB: 'Đang chờ bạn xác nhận',
  DASHBOARD_NEW_RFQ: 'Báo giá cần phản hồi',
  DASHBOARD_NEW_RFQ_SUB: 'Cần xử lý báo giá',
  DASHBOARD_DELIVERING: 'Đang giao hàng',
  DASHBOARD_DELIVERING_SUB: 'Lô hàng đang được thực hiện',
  DASHBOARD_UNPAID: 'Hóa đơn chờ thanh toán',
  DASHBOARD_UNPAID_SUB: 'Tổng công nợ hiện tại',
  DASHBOARD_VIEW_ALL: 'Xem tất cả',
  DASHBOARD_VIEW_DETAIL: 'Xem chi tiết',
  DASHBOARD_RECENT_PO: 'Đơn hàng gần đây',
  DASHBOARD_RECENT_PO_EMPTY: 'Chưa có đơn hàng nào',
  DASHBOARD_RECENT_PO_EMPTY_DESC:
    'Khi có đơn đặt hàng mới từ Vĩnh Phát, chúng sẽ hiển thị ở đây.',
  DASHBOARD_RECENT_RFQ: 'Yêu cầu báo giá mới (RFQ)',
  DASHBOARD_RECENT_RFQ_EMPTY: 'Chưa có RFQ nào',
  DASHBOARD_RECENT_RFQ_EMPTY_DESC:
    'Khi có yêu cầu báo giá mới, chúng sẽ hiển thị ở đây.',
  DASHBOARD_STATUS_NEW: 'Mới',
  DASHBOARD_STATUS_PROCESSING: 'Đang xử lý',
  DASHBOARD_STATUS_COMPLETED: 'Hoàn thành',

  // ── POComments ──
  COMMENTS_TITLE: 'Trao đổi với Vinh Phát',
  COMMENTS_EMPTY: 'Chưa có trao đổi nào.',
  COMMENTS_EMPTY_DESC: 'Hãy gửi tin nhắn nếu bạn có thắc mắc về đơn hàng.',
  COMMENTS_SENDER_ME: 'Bạn',
  COMMENTS_SENDER_BUYER: 'Vinh Phát',
  COMMENTS_INPUT_PLACEHOLDER: 'Nhập tin nhắn...',
};
