export const ORDERS_FORM_LABELS = {
  TITLE_EDIT: 'Sửa đơn: ',
  TITLE_NEW: 'Tạo đơn hàng mới',
  UNSAVED_WARNING: 'Bạn có thông tin chưa lưu. Bạn có chắc chắn muốn đóng?',
  ERROR_PREFIX: 'Lỗi: ',
  FIELD_ORDER_NUMBER: 'Số đơn hàng',
  FIELD_ORDER_TYPE: 'Loại đơn hàng',
  FIELD_ORDER_DATE: 'Ngày đặt hàng',
  FIELD_CUSTOMER: 'Khách hàng',
  FIELD_DELIVERY_DATE: 'Ngày giao dự kiến',
  FIELD_NOTES: 'Ghi chú đơn hàng',
  PLACEHOLDER_NOTES: 'Ghi chú về đơn hàng...',
  SECTION_ITEMS: 'Dòng hàng',
  ITEM_ROW_PREFIX: 'Dòng Hàng #',
  BTN_REMOVE: 'Xóa ✕',
  BTN_REMOVE_TITLE: 'Xóa dòng',
  FIELD_FABRIC_TYPE: 'Loại vải',
  PLACEHOLDER_FABRIC: 'Chọn hoặc nhập loại vải',
  FIELD_COLOR: 'Màu',
  PLACEHOLDER_COLOR: 'Chọn hoặc nhập màu...',
  FIELD_COLOR_CODE: 'Mã màu',
  PLACEHOLDER_COLOR_CODE: 'VD: TC-01',
  FIELD_UNIT: 'Đơn vị',
  BTN_ADD_ITEM: '+ Thêm dòng hàng mới',
  BTN_SAVE: 'Lưu thay đổi',
  BTN_CREATE: 'Tạo đơn mới',
  TXT_TOTAL: 'Tổng cộng: ',
  AUTO_NUMBER: 'Tự động',
  PLACEHOLDER_CUSTOMER: '— Chọn khách hàng —',
  FIELD_QUANTITY: 'Số lượng',
  FIELD_PRICE: 'Đơn giá',
  LBL_TOTAL_AMOUNT: 'Tổng tiền',
  LBL_BALANCE_DUE: 'Còn nợ',
  LBL_DELIVERY: 'Giao hàng: ',
  BADGE_TRADING: 'Thương mại',
  FIELD_PRODUCT_CATEGORY: 'Loại sản phẩm',
  FIELD_STOCK_SOURCE: 'Chọn từ kho',
  PLACEHOLDER_SELECT_YARN: 'Chọn loại sợi...',
  PLACEHOLDER_SELECT_FABRIC: 'Chọn cuộn vải...',
  FIELD_LOT: 'Số lô (Lot)',
  PLACEHOLDER_LOT: 'Chọn lô...',
  FIELD_AUTO_YARN_NAME: 'Tên sợi (tự động)',
  ERR_STOCK_EXCEEDED: (max: string) => `Vượt quá tồn kho khả dụng (${max})`,
} as const;

export const ORDERS_LIST_LABELS = {
  SEARCH_LABEL: 'Tìm kiếm',
  SEARCH_PLACEHOLDER: 'Mã đơn, tên khách hàng...',
  ERR_DELETE_ONLY_DRAFT: 'Chỉ có thể xoá đơn hàng ở trạng thái Nháp.',
  CONFIRM_DELETE: 'Xóa đơn hàng "{0}"? Hành động này không thể hoàn tác.',
  PAGE_TITLE: 'Đơn hàng',
  PAGE_SUBTITLE: 'Quản lý đơn hàng',
  BTN_PROGRESS: 'Tiến độ SX',
  BTN_CREATE_ORDER: 'Tạo đơn hàng',
  BTN_CREATE_ORDER_PLUS: '+ Tạo đơn hàng',
  ERR_LOAD_DATA: 'Lỗi tải dữ liệu:',
  EMPTY_SEARCH_TITLE: 'Không tìm thấy đơn hàng',
  EMPTY_NO_DATA_TITLE: 'Chưa có đơn hàng nào',
  EMPTY_SEARCH_DESC: 'Hãy thử thay đổi điều kiện lọc.',
  EMPTY_NO_DATA_DESC: 'Nhấn nút tạo đơn để bắt đầu.',
  PAGINATION_LABEL: 'đơn hàng',
  ERR_NOT_FOUND: 'Không tìm thấy đơn hàng.',
  CONFIRM_TRADING:
    'Xác nhận đơn hàng thương mại? Hệ thống sẽ tự động trừ kho cho các dòng hàng.',
  CONFIRM_PRODUCTION:
    'Xác nhận đơn hàng? Hệ thống sẽ tạo 7 công đoạn tiến độ tự động.',
  CONFIRM_CANCEL_TRADING:
    'Hủy đơn thương mại? Hệ thống sẽ hoàn trả tồn kho đã trừ.',
  CONFIRM_CANCEL: 'Hủy đơn hàng này?',
  CONFIRM_COMPLETE: 'Hoàn thành đơn hàng?',
  CONFIRM_APPROVE_REQ: 'Chấp nhận đơn yêu cầu này và chuyển thành đơn nháp?',
  CONFIRM_REJECT_REQ: 'Từ chối đơn yêu cầu này?',
  BTN_BACK: 'Quay lại',
  TYPE_PRODUCTION: 'Sản xuất',
  LBL_ORDER_DATE: 'Ngày đặt',
  LBL_DELIVERY_DATE: 'Ngày giao',
  LBL_PAID_AMOUNT: 'Đã thu',
  LBL_NOTES_PREFIX: 'Ghi chú:',
  LBL_PAYMENT_PROGRESS: 'Thanh toán',
  BTN_APPROVE_REQ: 'Duyệt yêu cầu',
  BTN_REJECT_REQ: 'Từ chối',
  BTN_EDIT: 'Sửa đơn',
  BTN_CONFIRM_TRADING: 'Xác nhận & Trừ kho',
  BTN_CONFIRM: 'Xác nhận đơn',
  BTN_SHIP: 'Tạo phiếu xuất',
  BTN_PAY: 'Thu tiền',
  BTN_COMPLETE: 'Hoàn thành',
  BTN_CONTRACT: 'Tạo hợp đồng',
  BTN_CANCEL: 'Hủy đơn',
  EMPTY_ITEMS: 'Chưa có dòng hàng.',
  COL_SOURCE: 'Nguồn',
  TYPE_FABRIC: 'Vải',
  COL_PRICE: 'Đơn giá (đ)',
  COL_AMOUNT: 'Thành tiền (đ)',
  COL_ORDER_CUSTOMER: 'Số đơn / Khách hàng',
  COL_ORDER_DATE: 'Ngày đặt',
  COL_DELIVERY_DATE: 'Dự kiến giao',
  COL_TOTAL: 'Tổng tiền',
  COL_BALANCE: 'Còn nợ',
  COL_STATUS: 'Trạng thái',
  COL_ACTIONS: 'Thao tác',
  AUDIT_LOG_TITLE: 'Lịch sử hoạt động',
} as const;

export const ORDERS_PROG_LABELS = {
  PROG_LOADING: 'Đang tải...',
  PROG_EMPTY_ACTIVE: 'Không có đơn hàng nào đang hoạt động.',
  PROG_EMPTY_AUDIT: 'Chưa có lịch sử thay đổi.',
  PROG_OVERDUE: 'Trễ hạn',
  PROG_READY_TO_SHIP: 'Sẵn sàng giao',
  PROG_IN_PROGRESS: 'Đang sản xuất',
  PROG_WAITING: 'Chờ sản xuất',
  PROG_SECTION_OVERDUE: 'Đơn trễ hạn',
  PROG_SECTION_READY: 'Sẵn sàng giao hàng',
  PROG_SECTION_WAITING: 'Chờ bắt đầu sản xuất',
  PROG_LATE_DAYS: 'trễ',
  PROG_LATE_SUFFIX: 'ngày',
  PROG_TIMELINE_TITLE: 'Tiến độ sản xuất',
  PROG_EXPECTED: 'Dự kiến:',
  PROG_ACTUAL: 'Thực tế:',
  PROG_BOARD_TITLE: 'Tiến độ đơn hàng',
  PROG_PAGE_TITLE: 'Tiến độ Sản xuất',
  PROG_FILTER_STAGE: 'Công đoạn',
  PROG_FILTER_STATUS: 'Trạng thái',
  PROG_FILTER_ALL: 'Tất cả',
  PROG_STATUS_PENDING: 'Chờ xử lý',
  PROG_STATUS_DOING: 'Đang làm',
  PROG_STATUS_DONE: 'Hoàn thành',
  PROG_STATUS_SKIPPED: 'Bỏ qua',
  // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
  PROG_BTN_START: '▶ Bắt đầu',
  PROG_BTN_COMPLETE: '✓ Hoàn thành',
  PROG_BTN_SKIP: 'Bỏ qua',
  PROG_BTN_SAVE: 'Lưu',
  PROG_BTN_CANCEL: 'Hủy',
  PROG_PLACEHOLDER_NOTE: 'Ghi chú...',
  PROG_ERROR_UPDATE: 'Lỗi cập nhật:',
  PROG_STANDALONE_WO: 'LSX độc lập',
  PROG_EMPTY_FILTER: 'Không tìm thấy đơn hàng phù hợp.',
  PROG_EMPTY_CONFIRMED: 'Chưa có đơn hàng nào được xác nhận.',
  PROG_BTN_CLEAR_FILTER: '✕ Xóa lọc',
  PROG_AUDIT_LOG_TITLE: 'Nhật ký thay đổi',
  PROG_AUDIT_LOG_RECENT: 'Cập nhật gần đây',
  PROG_TAB_DASHBOARD: 'Tổng quan',
  PROG_TAB_BOARD: 'Bảng tiến độ',
  PROG_TAB_AUDIT: 'Nhật ký',
} as const;

export const ORDERS_RES_LABELS = {
  RES_TAB_PREFIX: 'Dòng',
  RES_SUM_RESERVED: 'Đã giữ',
  RES_SUM_LENGTH: 'Tổng dài',
  RES_SUM_WEIGHT: 'Tổng nặng',
  RES_COL_ROLL: 'Mã cuộn',
  RES_COL_FABRIC: 'Loại vải',
  RES_COL_COLOR: 'Màu',
  RES_COL_LENGTH: 'Dài',
  RES_COL_WEIGHT: 'Nặng',
  RES_COL_LOCATION: 'Vị trí',
  RES_COL_GRADE: 'CL',
  // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
  RES_TITLE: '🔒 Giữ cuộn — ',
  RES_REQUIRED: '— Cần:',
  RES_RESERVED_LIST_TITLE: 'Cuộn đang giữ',
  RES_AVAILABLE_LIST_TITLE: 'Cuộn khả dụng',
  RES_BTN_UNRESERVE: 'Bỏ giữ',
  RES_BTN_RESERVE: 'Giữ',
  RES_BTN_PROCESSING: 'Đang xử lý...',
  RES_EMPTY_AVAILABLE: 'Không có cuộn nào khả dụng',
  RES_FOR: 'cho',
  RES_BTN_CLOSE: 'Đóng',
} as const;

export const ORDERS_OVERRIDE_LABELS = {
  OVERRIDE_DIALOG_TITLE: 'Xác nhận vượt hạn mức',
  OVERRIDE_DIALOG_WARNING: 'Cảnh báo hạn mức',
  OVERRIDE_MSG_ADMIN_ONLY:
    'Bạn có quyền phê duyệt ngoại lệ (Override). Bạn có muốn tiếp tục lưu đơn hàng này?',
  OVERRIDE_MSG_SALE_ONLY: 'Vui lòng liên hệ Quản lý để xin phê duyệt ngoại lệ.',
  OVERRIDE_BTN_CONFIRM: 'Xác nhận tiếp tục',
  OVERRIDE_BTN_CANCEL: 'Hủy / Quay lại',
  OVERRIDE_TITLE_OVERDUE: 'Cảnh báo: Nợ quá hạn',
  OVERRIDE_TITLE_LIMIT: 'Cảnh báo: Vượt hạn mức tín dụng',
  OVERRIDE_SUB_OVERDUE: 'Khách hàng đang có công nợ quá hạn chưa thanh toán',
  OVERRIDE_SUB_LIMIT: 'Đơn hàng sẽ đẩy công nợ khách vượt quá hạn mức cho phép',
  OVERRIDE_CLOSE: 'Đóng',
  OVERRIDE_STAT_OVERDUE: 'Nợ quá hạn',
  OVERRIDE_STAT_CURRENT: 'Công nợ hiện tại',
  OVERRIDE_STAT_NEW: 'Giá trị đơn mới',
  OVERRIDE_STAT_PROJECTED: 'Dự kiến công nợ sau tạo đơn',
  OVERRIDE_STAT_LIMIT: 'Hạn mức tín dụng',
} as const;

export const ORDERS_DASHBOARD_LABELS = {
  KPI_PENDING_APPROVAL: 'Yêu cầu chờ duyệt',
  KPI_EXPECTED_REVENUE: 'Doanh thu dự kiến',
  KPI_TOTAL_DEBT: 'Tổng công nợ',
  KPI_PENDING_DESC: 'Yêu cầu từ Customer Portal',
  KPI_REVENUE_DESC: 'Tổng giá trị đơn hiển thị',
  KPI_DEBT_DESC: 'Số tiền khách còn nợ',
  DASHBOARD_TABLE_TITLE: 'Đơn hàng đang xử lý',
  DASH_TAB_ALL: 'Tất cả',
  DASH_TAB_IN_PROGRESS: 'Đang SX',
  DASH_TAB_OVERDUE: 'Trễ hạn',
  DASH_TAB_FULFILLED: 'Đã giao đủ',
  DASH_COL_ORDER: 'Mã ĐH',
  DASH_COL_CUSTOMER: 'Khách hàng',
  DASH_COL_STATUS: 'Trạng thái',
  DASH_COL_PCT: 'SX hoàn thành',
  DASH_COL_WO: 'Lệnh SX',
  DASH_COL_PROGRESS: 'Tiến độ',
  DASH_COL_DELIVERY: 'Hạn giao',
  COL_ORDER_CODE: 'Mã đơn',
  COL_STAGE: 'Công đoạn',
  LBL_LATE: 'Trễ hạn',
  LBL_ON_TIME: 'Đúng hạn',
  LBL_WARNING: 'Cảnh báo',
  KPI_TOTAL_ORDERS: 'Tổng đơn đang xử lý',
  KPI_ON_TIME: 'Đúng hạn',
  KPI_LATE: 'Trễ hạn',
  KPI_WARNING: 'Cảnh báo',
  KPI_COMPLETED_TODAY: 'Hoàn thành hôm nay',
  DASH_KPI_TOTAL_PROC: 'Tổng ĐH đang xử lý',
  DASH_KPI_FULFILLED: 'đã giao đủ',
  DASH_KPI_PROD_DONE: 'Đã hoàn thành SX',
  DASH_KPI_ORDERS: 'đơn hàng',
  DASH_KPI_LATE_DELIV: 'Trễ hạn giao',
  DASH_KPI_URGENT: 'Cần xử lý gấp',
  DASH_KPI_GOOD: 'Tốt',
  DASH_KPI_AVG_PCT: 'Tỉ lệ hoàn thành TB',
} as const;

export const ORDERS_AUDIT_LABELS = {
  AUDIT_LBL_USER: 'Người thao tác',
  AUDIT_LBL_ACTION: 'Hành động',
  AUDIT_LBL_TIME: 'Thời gian',
  AUDIT_LBL_DETAILS: 'Chi tiết',
  AUDIT_EMPTY: 'Chưa có giao dịch hoạt động nào được ghi nhận.',
  AUDIT_LOADING: 'Đang tải lịch sử...',
  AUDIT_ERROR: 'Lỗi tải dữ liệu lịch sử',
  AUDIT_DEFAULT_ACTOR: 'Hệ thống',
  AUDIT_EVENT_ORDER_CREATED: 'Tạo đơn hàng',
  AUDIT_EVENT_ORDER_CREATED_DETAIL: 'Khởi tạo đơn hàng',
  AUDIT_EVENT_REQ_CREATED: 'Tạo yêu cầu',
  AUDIT_EVENT_REQ_CREATED_DETAIL: 'Tạo từ Portal Khách hàng',
  AUDIT_EVENT_STATUS_CHANGED: 'Cập nhật trạng thái',
} as const;

export const ORDERS_MODULE_LABELS = {
  MODULE_TITLE: 'Đơn Hàng & Bán Hàng',
  MODULE_DESC:
    'Quản lý đơn đặt hàng, tự động chuyển đổi sang lệnh sản xuất, theo dõi tiến độ và giao hàng.',
  KPI_PENDING_PROD: 'Chờ sản xuất',
  KPI_DELIVERING: 'Đang giao',
  HIGHLIGHT_SO_TO_WO: 'Tự động tạo Lệnh Sản Xuất từ Đơn hàng.',
  HIGHLIGHT_TRACKING: 'Theo dõi tiến độ realtime.',
  MILESTONE_INVOICE: 'Tích hợp hóa đơn điện tử.',
  PLUGIN_LABEL: 'Đơn hàng',
  PLUGIN_DESC: 'Quản lý đơn hàng, báo giá và bán hàng.',
  PROG_MODULE_TITLE: 'Tiến Độ Sản Xuất',
  PROG_MODULE_DESC:
    'Theo dõi và cập nhật tiến độ cho từng đơn hàng theo thời gian thực.',
  PROG_KPI_DOING: 'Đang thực hiện',
  PROG_HIGHLIGHT_KANBAN: 'Giao diện Kanban trực quan.',
  PROG_HIGHLIGHT_AUTO: 'Tự động chuyển công đoạn.',
  PROG_MILESTONE_IOT: 'Tích hợp máy đo IoT.',
  PROG_PLUGIN_LABEL: 'Tiến độ SX',
  PROG_PLUGIN_DESC: 'Theo dõi tiến độ đơn hàng',
} as const;
