export const ORDER_MESSAGES = {
  TITLE_EDIT: 'Sửa đơn: ',
  TITLE_NEW: 'Tạo đơn hàng mới',
  UNSAVED_WARNING: 'Bạn có thông tin chưa lưu. Bạn có chắc chắn muốn đóng?',
  ERROR_PREFIX: 'Lỗi: ',
  FIELD_ORDER_NUMBER: 'Số đơn hàng',
  FIELD_ORDER_TYPE: 'Loại đơn hàng',
  FIELD_ORDER_DATE: 'Ngày đặt hàng',
  FIELD_CUSTOMER: 'Khách hàng',
  FIELD_DELIVERY_DATE: 'Ngày giao dự kiến',
  FIELD_NOTES: 'Ghi chú đơn hàng',
  PLACEHOLDER_NOTES: 'Ghi chú về đơn hàng...',
  SECTION_ITEMS: 'Dòng hàng',
  ITEM_ROW_PREFIX: 'Dòng Hàng #',
  BTN_REMOVE: 'Xóa ✕',
  BTN_REMOVE_TITLE: 'Xóa dòng',
  FIELD_FABRIC_TYPE: 'Loại vải',
  PLACEHOLDER_FABRIC: 'Chọn hoặc nhập loại vải',
  FIELD_COLOR: 'Màu',
  PLACEHOLDER_COLOR: 'Chọn hoặc nhập màu...',
  FIELD_COLOR_CODE: 'Mã màu',
  PLACEHOLDER_COLOR_CODE: 'VD: TC-01',
  FIELD_UNIT: 'Đơn vị',
  BTN_ADD_ITEM: '+ Thêm dòng hàng mới',
  BTN_SAVE: 'Lưu thay đổi',
  BTN_CREATE: 'Tạo đơn mới',
  TXT_TOTAL: 'Tổng cộng: ',
  AUTO_NUMBER: 'Tự động',
  PLACEHOLDER_CUSTOMER: '— Chọn khách hàng —',
  FIELD_QUANTITY: 'Số lượng',
  FIELD_PRICE: 'Đơn giá',
  LBL_TOTAL_AMOUNT: 'Tổng tiền',
  LBL_BALANCE_DUE: 'Còn nợ',
  LBL_DELIVERY: 'Giao hàng: ',
  COL_ORDER_CUSTOMER: 'Số đơn / Khách hàng',
  COL_ORDER_DATE: 'Ngày đặt',
  COL_DELIVERY_DATE: 'Dự kiến giao',
  COL_TOTAL: 'Tổng tiền',
  COL_BALANCE: 'Còn nợ',
  COL_STATUS: 'Trạng thái',
  COL_ACTIONS: 'Thao tác',
} as const;
