export const SUPPLIER_LIST_LABELS = {
  TITLE: 'Nhà cung cấp',
  ADD_BUTTON: 'Thêm nhà cung cấp',
  KPI_TOTAL: 'Tổng nhà cung cấp',
  KPI_TOTAL_DESC: 'Đối tác cung cấp vật tư',
  KPI_ACTIVE: 'Đang giao dịch',
  KPI_ACTIVE_DESC: 'Trạng thái hoạt động',
  TAB_ALL: 'Tất cả NCC',
  TAB_ACTIVE: 'Đang giao dịch',
  SEARCH_PLACEHOLDER: 'Tên hoặc mã NCC...',
  FILTER_SEARCH: 'Tìm kiếm NCC',
  FILTER_CATEGORY: 'Danh mục',
  FILTER_STATUS: 'Trạng thái',
  COL_CODE: 'Mã NCC',
  COL_NAME: 'Tên nhà cung cấp',
  COL_CATEGORY: 'Danh mục',
  COL_PHONE: 'Liên hệ',
  COL_PERFORMANCE: 'Hiệu suất (OTD / Đánh giá)',
  COL_LIMIT: 'Hạn mức',
  COL_STATUS: 'Trạng thái',
  COL_ACTIONS: 'Thao tác',
  ACTION_CREATE_CONTRACT: 'Tạo hợp đồng',
  ACTION_EDIT: 'Sửa',
  ACTION_DELETE: 'Xóa',
  CONFIRM_DELETE_PREFIX: 'Xóa NCC',
  CONFIRM_DELETE_SUFFIX: 'Hành động này không thể hoàn tác.',
  EMPTY_STATE_TITLE_SEARCH: 'Không tìm thấy nhà cung cấp',
  EMPTY_STATE_TITLE_NO_DATA: 'Chưa có nhà cung cấp',
  EMPTY_STATE_DESC_SEARCH: 'Vui lòng thử điều chỉnh lại bộ lọc.',
  EMPTY_STATE_DESC_NO_DATA:
    'Nhấn nút thêm nhà cung cấp mới để lưu trữ thông tin liên hệ.',
  EMPTY_STATE_ADD: '+ Thêm NCC mới',
  PAGINATION_ITEM: 'nhà cung cấp',
  ERROR_PREFIX: 'Lỗi:',
  NOT_AVAILABLE: '—',
  CONTACT_PERSON_PREFIX: 'NLH:',
  LBL_OTD: 'OTD:',
  LBL_RATING: 'Đánh giá:',
};
