export const K80_QUICK_PRINT_LABELS = {
  PAGE_TITLE: 'Công Cụ In Nhanh',
  GENERAL_INFO: 'Thông tin chung',
  CUSTOMER: 'Khách hàng',
  SELECT_CUSTOMER: '— Chọn khách hàng —',
  SHIP_DATE: 'Ngày xuất',
  TICKET_NUMBER: 'Số phiếu',
  AUTO: 'Tự động',
  PRODUCT_DATA: 'Dữ liệu hàng hóa (Cột = Mã vải, Ô = Số Kg)',
  ADD_COLUMN: 'Thêm Cột',
  COLUMN: 'Mã vải #',
  FABRIC_CODE: 'Mã Vải',
  DELETE_COLUMN: 'Xóa cột',
  TIP_EXCEL:
    'Mẹo: Bạn có thể copy một cột dữ liệu từ Excel và dán trực tiếp vào ô số Kg. Hệ thống tự nhận diện dòng mới, dấu phẩy, khoảng trắng.',
  PROCESS_AND_PRINT: 'Xử Lý & In',
  CHECK_INFO: 'Kiểm tra thông tin trước khi in',
  SAVE_TO_DB: 'Lưu thành phiếu xuất kho',
  BTN_SAVE_PRINT_PREFIX: 'LƯU & IN',
  BTN_PRINT_ONLY_PREFIX: 'IN',
  BTN_PRINT_ONLY_SUFFIX: '(Không Lưu)',
  PREVIEW_TITLE: 'Xem trước bản in',
  PROCESSING: 'Đang xử lý...',
  PAPER_SIZE_K80: 'Giấy K80 (Mặc định)',
  PAPER_SIZE_A5: 'Giấy A5',
  BTN_EXPORT_EXCEL: 'Xuất Excel',
  BTN_SHARE_ZALO: 'Gửi Zalo (Copy Ảnh)',
};

export const K80_QUICK_PRINT_MESSAGES = {
  MAX_COLUMNS: 'Tối đa 5 mã vải trên 1 phiếu K80',
  REQUIRE_CUSTOMER: 'Vui lòng chọn khách hàng để lưu phiếu xuất',
  REQUIRE_DATA: 'Chưa có dữ liệu hàng hóa',
  INVALID_DATA: 'Chưa nhập dữ liệu cuộn vải hợp lệ',
  SAVE_SUCCESS: 'Lưu phiếu xuất kho thành công',
  SAVE_ERROR: 'Lỗi khi lưu phiếu:',
  PURPOSE_NOTE: 'In nhanh K80',
  EXPORT_SUCCESS: 'Xuất Excel thành công',
  EXPORT_ERROR: 'Lỗi khi xuất Excel:',
  ZALO_CREATING: 'Đang tạo ảnh...',
  ZALO_ERROR_CREATE: 'Không tạo được ảnh',
  ZALO_COPY_SUCCESS: 'Đã copy ảnh! Bạn có thể nhấn Ctrl+V để dán vào Zalo.',
  ZALO_DOWNLOAD_SUCCESS: 'Đã tải ảnh về máy! Bạn có thể gửi ảnh này qua Zalo.',
  ZALO_ERROR_GENERAL: 'Có lỗi xảy ra khi tạo ảnh. Vui lòng thử lại.',
  PLACEHOLDER_WEIGHTS: '24.5\n25.2\n24.8',
};

export const K80_PRINT_LAYOUT_LABELS = {
  COMPANY_NAME: 'VĨNH PHÁT TEXTILE',
  RECEIPT_TITLE: 'BẢNG KÊ XUẤT HÀNG',
  TICKET_NO: 'Số phiếu:',
  DATE: 'Ngày xuất:',
  EXPORT_TIME: 'Giờ xuất:',
  PRINT_TIME: 'In lúc:',
  PRINTED_BY: 'Người in:',
  CUSTOMER: 'Khách hàng:',
  NO_DATA: 'Chưa có dữ liệu',
  TOTAL_CODES: 'Số mã:',
  TOTAL_ROLLS: 'Tổng cuộn:',
  TOTAL_KG: 'Tổng KG:',
  SENDER: 'Người giao',
  RECEIVER: 'Người nhận',
  SIGN_INSTRUCTION: '(Ký, ghi rõ họ tên)',
  EMPTY_VALUE: '---',
  EMPTY_DASH: '-',
  ROLL_UNIT_ABBR: 'C',
  SEPARATOR_LINE: '=================',
};
