import { FABRIC_CATALOG_STATUS_LABELS } from '@/schema/fabric-catalog.schema';

export const UNIT_OPTIONS = [
  { value: 'kg', label: 'kg' },
  { value: 'm', label: 'mét (m)' },
  { value: 'cuộn', label: 'cuộn' },
];

export const STATUS_OPTIONS = (['active', 'inactive'] as const).map((s) => ({
  value: s,
  label: FABRIC_CATALOG_STATUS_LABELS[s],
}));

export const TECHNIQUE_OPTIONS = [
  { value: 'Single Jersey', label: 'Single Jersey' },
  { value: 'Interlock', label: 'Interlock' },
  { value: 'Rib', label: 'Rib' },
  { value: 'Pique', label: 'Pique' },
  { value: 'French Terry', label: 'French Terry' },
  { value: 'Fleece', label: 'Fleece' },
  { value: 'Polar Fleece', label: 'Polar Fleece' },
  { value: 'Waffle', label: 'Waffle' },
  { value: 'Jacquard', label: 'Jacquard' },
];

export const ORIGIN_OPTIONS = [
  { value: 'Việt Nam', label: 'Việt Nam' },
  { value: 'Trung Quốc', label: 'Trung Quốc' },
  { value: 'Hàn Quốc', label: 'Hàn Quốc' },
  { value: 'Đài Loan', label: 'Đài Loan' },
  { value: 'Nhật Bản', label: 'Nhật Bản' },
  { value: 'Thái Lan', label: 'Thái Lan' },
];

export const ROUTE_FABRIC_CATALOG = '/fabric-catalog';

export const LABELS = {
  SEARCH_PLACEHOLDER: 'Tìm kiếm...',
  SEARCH: 'Tìm kiếm',
  STATUS: 'Trạng thái',
  CODE: 'Mã',
  NAME: 'Tên loại vải',
  CATEGORY: 'Nhóm vải',
  CATEGORY_PLACEHOLDER: 'Chọn nhóm vải...',
  COMPOSITION: 'Thành phần',
  COMPOSITION_PLACEHOLDER: 'VD: Cotton...',
  SPECS: 'Quy cách (chuẩn)',
  WIDTH: 'Khổ',
  GSM: 'K/L',
  UNIT: 'Đơn vị',
  ACTIONS: 'Thao tác',
  EDIT: 'Chỉnh sửa',
  PRINT_QR: 'In Tem Mẫu',
  DELETE: 'Xóa',
  ADD_NEW: 'Thêm loại vải',
  TOTAL_CATALOGS: 'Tổng loại vải',
  TOTAL_CATALOGS_DESC: 'Toàn bộ danh mục hệ thống',
  ACTIVE: 'Đang hoạt động',
  ACTIVE_DESC: 'Trên trang hiện tại',
  MAIN_COMPOSITION: 'Thành phần chính',
  MAIN_COMPOSITION_DESC: 'Được ưa chuộng nhất',
  EMPTY_SEARCH: 'Không tìm thấy loại vải phù hợp',
  EMPTY_LIST: 'Chưa có loại vải nào',
  ADD_NEW_BTN: '+ Thêm loại vải',
  ITEM_LABEL: 'loại vải',
  BACK_TO_LIST: 'Danh mục vải',
  NOT_FOUND: 'Không tìm thấy loại vải hoặc có lỗi xảy ra.',
  BACK: 'Quay lại danh sách',
  NA: '—',
  UNSAVED: 'Chưa lưu',
  COPY_LINK: 'Sao chép',
  NOTES_LABEL: 'Ghi chú',
  NOTES_PLACEHOLDER: 'Ghi chú nội bộ...',

  // Info Tab
  LABEL_IMAGE: 'Ảnh mẫu vải',
  LABEL_COLOR: 'Màu sắc',
  LABEL_TECHNIQUE: 'Kỹ thuật',

  // B2B Config
  B2B_CONFIG_TITLE: 'Cấu hình B2B & Công khai',
  B2B_CONFIG_DESC: 'Quản lý cách mẫu vải hiển thị trên trang khách hàng',
  PUBLIC_URL_PREFIX: '/p/fabric/',
  QR_CODE_TITLE: 'Mã QR Sản Phẩm',
  QR_CODE_DESC:
    'Dùng mã QR này để in tem nhãn. Khách hàng quét mã sẽ được dẫn thẳng đến trang chi tiết sản phẩm.',

  // Form tabs
  TAB_INFO: 'Thông tin',
  TAB_PUBLIC: 'Công khai',
  TAB_GALLERY: 'Thư viện ảnh',
  TAB_ADMIN: 'Quản trị',
  ADMIN_GENERAL_CONFIG: 'Cấu hình chung',

  // Gallery UX
  GALLERY_TITLE: 'Thư viện ảnh sản phẩm',
  GALLERY_DESC: 'Kéo thả hoặc tải lên các ảnh chi tiết cho mẫu vải này.',
  GALLERY_UPLOAD: 'Tải ảnh lên',
  GALLERY_EMPTY: 'Chưa có ảnh nào trong thư viện',
  GALLERY_EMPTY_HINT: 'Nhấn Tải ảnh lên để bắt đầu',
  GALLERY_SEO_WARNING: 'Khuyến nghị SEO & Trải nghiệm khách hàng:',
  GALLERY_WARNING_SWATCH: 'Nên có ít nhất 1 ảnh Mẫu vải (SWATCH)',
  GALLERY_WARNING_SURFACE: 'Nên có ít nhất 1 ảnh Chi tiết bề mặt (SURFACE)',
  GALLERY_WARNING_APPLICATION:
    'Nên có ít nhất 1 ảnh Ứng dụng/Góc gấp (APPLICATION)',
  GALLERY_IMAGE_TYPE: 'Loại ảnh',
  GALLERY_IMAGE_POS: 'Vị trí',
  GALLERY_ALT_TEXT: 'Alt Text (SEO)',
  GALLERY_CAPTION: 'Caption',
  GALLERY_IS_PRIMARY: 'Ảnh chính',
  GALLERY_REMOVE_IMAGE: 'Xóa ảnh',
  GALLERY_ALT_PLACEHOLDER: 'VD: Vải nỉ bông màu xám...',
  GALLERY_CAPTION_PLACEHOLDER: 'VD: Chi tiết bề mặt sợi dệt...',
  GALLERY_DEFAULT_ALT: 'Ảnh mẫu vải',
  GALLERY_UPLOADING: 'Đang tải lên...',

  // Slug UX
  SLUG_LABEL: 'Đường dẫn tĩnh (Slug)',
  SLUG_AUTO_HINT: 'Tự động tạo từ mã vải',
  SLUG_EDIT: 'Sửa',
  SLUG_CANCEL: 'Hủy',

  // Public toggle
  PUBLIC_TITLE: 'Công khai cho khách hàng',
  PUBLIC_DESC: 'Khách hàng có thể quét QR và xem thông tin trực tuyến',
  PUBLIC_ON: 'Đang công khai',
  PUBLIC_OFF: 'Chưa công khai',
  PUBLIC_PAGE_LABEL: 'Trang công khai',

  // Preview card
  PREVIEW_TITLE: 'Xem trước trang công khai',
  PREVIEW_NO_IMAGE: 'Chưa có ảnh',
  PREVIEW_WIDTH_UNIT: 'cm',
  PREVIEW_GSM_UNIT: 'gsm',
  PREVIEW_KPI_MOQ: 'MOQ',
  PREVIEW_KPI_LEAD_TIME: 'Lead Time',
  PREVIEW_KPI_CAPACITY: 'Capacity',
  PREVIEW_KPI_CONSUMPTION: 'Định mức',
  PREVIEW_TRUST_SAMPLE: '✓ Có sẵn mẫu',
  PREVIEW_TRUST_FAST: '✓ Giao nhanh',
  PREVIEW_TRUST_TECH: '✓ Hỗ trợ kỹ thuật',
  PREVIEW_STOCK_QUANTITY: 'Còn hàng: {qty} kg (Giả lập)',
  PREVIEW_STOCK_STATUS: 'Có sẵn hàng',
  PREVIEW_PRICE_PREFIX: 'Từ',
  PREVIEW_PRICE_UNIT: 'đ/kg',
  PREVIEW_UNIT_KG: 'kg',
  PREVIEW_UNIT_DAY: 'ngày',
  PREVIEW_UNIT_CAPACITY: 'T/th',
  PREVIEW_UNIT_CONSUMPTION: 'kg/áo',
  PREVIEW_DESKTOP: 'Xem trên Desktop',
  PREVIEW_MOBILE: 'Xem trên Mobile',
  PREVIEW_GALLERY: 'Xem thư viện',
  PREVIEW_B2B_PORTAL: 'B2B Portal',
  PREVIEW_PRICE_REF: 'Giá sỉ tham khảo',
  PREVIEW_CONTACT_PRICE: 'Liên hệ báo giá',
  PREVIEW_MOQ_LABEL: 'Số lượng đặt tối thiểu',
  PREVIEW_STOCK_CONDITION: 'Tình trạng kho',
  PREVIEW_SERVICES: 'Dịch vụ đi kèm',
  PREVIEW_CONTACT_ORDER: 'Liên hệ / Đặt hàng',
  PREVIEW_HIDDEN: 'Đang ẩn',
  PREVIEW_HIDDEN_DESC:
    'Trang này chưa được công khai với khách hàng. Bật công khai để hiển thị.',

  // Readiness Score
  SCORE_TITLE: 'Public Readiness Score',
  SCORE_LIVE: 'Live',
  SCORE_DESC: 'Điều kiện để xuất bản lên trang khách hàng',
  SCORE_LAST_UPDATED: 'Cập nhật lần cuối:',
  SCORE_PUBLIC_ON: 'Đang Công Khai',
  SCORE_PUBLIC_OFF: 'Chưa Công Khai',
  SCORE_CHECK_IMAGE: 'Có ảnh chính',
  SCORE_CHECK_PLANNER: 'Cấu hình Planner',
  SCORE_CHECK_MOQ: 'MOQ hợp lệ',
  SCORE_CHECK_SEO: 'SEO Slug',
  SCORE_CHECK_GALLERY: 'Thư viện ảnh',
  SCORE_CHECK_PRICING: 'Bảng giá sỉ',

  // Tag inputs
  OLD_DATA_HINT: 'Dữ liệu cũ: ',
  COMPOSITION_TAG_PLACEHOLDER: 'VD: 65% Polyester, 35% Cotton (Nhấn Enter)',
  COLOR_TAG_PLACEHOLDER: 'VD: Trắng, Đen (Nhấn Enter)',

  // Accordion section titles
  SECTION_CUSTOMER: 'Công khai khách hàng',
  SECTION_PLANNER: 'Thông số Planner',
  SECTION_PRICING: 'Bảng giá',
  SECTION_SEO_QR: 'SEO & QR',

  // Stock display options
  STOCK_DISPLAY_NONE: 'Không hiển thị',
  STOCK_DISPLAY_STATUS: 'Chỉ hiển thị trạng thái',
  STOCK_DISPLAY_QUANTITY: 'Hiển thị số lượng thực',
  STOCK_DISPLAY_LABEL: 'Hiển thị tồn kho công khai',

  // Trust signals
  TRUST_HAS_SAMPLE: 'Có sẵn mẫu',
  TRUST_FAST_DELIVERY: 'Giao nhanh',
  TRUST_TECH_SUPPORT: 'Hỗ trợ kỹ thuật',
  TRUST_SIGNALS_LABEL: 'Đặc tính kinh doanh (Trust Signals)',

  // Planner groups
  PLANNER_REQUIRED: 'Bắt buộc',
  PLANNER_ADVANCED: 'Nâng cao',
  STANDARD_CONSUMPTION_LABEL: 'Định mức chuẩn (kg/áo)',
  STANDARD_CONSUMPTION_PLACEHOLDER: 'VD: 0.25',
  ORIGIN_PLACEHOLDER: 'VD: Việt Nam, Trung Quốc, Hàn Quốc...',
  ADVANCED_SETTINGS_TOGGLE: 'Cài đặt nâng cao',
  UNIT_TON_MONTH: 'tấn/tháng',
  UNIT_KG: 'kg',
  UNIT_DAY: 'ngày',
  UNIT_TON: 'tấn',

  // Pricing
  PRICING_LOWEST_PREFIX: 'Từ',
  PRICING_EMPTY: 'Chưa cấu hình bảng giá',

  // CTA
  VIEW_PUBLIC_PAGE: 'Xem trang công khai',

  // Extra strings from FabricPublicTab
  MOQ_LABEL: 'MOQ (kg)',
  LEAD_TIME_LABEL: 'Giao hàng (ngày)',
  CAPACITY_LABEL: 'Năng lực SX (tấn/tháng)',
  YIELD_LABEL: 'Hệ số hao hụt (0.5 - 2.0)',
  PRICING_EDIT_TITLE: 'Chỉnh sửa chi tiết bậc giá',
  PRICING_ADD_TIER: 'Thêm bậc giá',
  PRICING_COL_MIN: 'Từ số lượng',
  PRICING_COL_MAX: 'Đến số lượng',
  PRICING_COL_PRICE: 'Giá thật (VND)',
  PRICING_COL_LABEL: 'Nhãn hiển thị Public',
  PRICING_COL_PUBLIC: 'Public?',
  PRICING_MAX_PLACEHOLDER: 'Trở lên',
  PRICING_LABEL_PLACEHOLDER: 'VD: Liên hệ, Giá nhà máy',
  PRICING_MOQ_CONFLICT_WARNING:
    'Có bậc giá công khai bắt đầu từ số lượng nhỏ hơn MOQ ({moq} kg). Khách hàng sẽ không thể đặt hàng dưới mức MOQ này.',
  PRICING_DELETE_TIER: 'Xóa bậc giá',
  SLUG_PLACEHOLDER: 'VD: fc-001',
  ACTION_COPY: 'Sao chép',
  ACTION_OPEN_PAGE: 'Mở trang',
  ACTION_DOWNLOAD_QR: 'Tải QR (.png)',
  ACTION_PRINT_QR: 'In Tem Mẫu',

  // Form buttons & titles
  EDIT_TITLE: 'Sửa',
  UPDATE: 'Cập nhật',
  CANCEL: 'Hủy',
  ERROR_PREFIX: 'Lỗi:',

  // Extra strings from FabricInfoTab
  CODE_PLACEHOLDER: 'VD: FC-001',
  NAME_PLACEHOLDER: 'VD: Cotton TC 65/35',
  WIDTH_PLACEHOLDER: 'VD: 160',
  GSM_PLACEHOLDER: 'VD: 250',
  TECHNIQUE_PLACEHOLDER: 'Chọn kỹ thuật dệt...',
  COMBOBOX_DEFAULT_PLACEHOLDER: 'Chọn...',
} as const;

export const MESSAGES = {
  CONFIRM_DELETE: (name: string) =>
    `Xóa loại vải "${name}"? Hành động này không thể hoàn tác.`,
} as const;

export const HOTLINE = '0989072670';

export const PUBLIC_PAGE_LABELS = {
  loading: 'Đang tải thông tin...',
  notFound: 'Không tìm thấy mẫu vải',
  notFoundDesc: 'Mẫu vải không tồn tại hoặc đã ngừng kinh doanh.',
  backHome: 'Về trang chủ',
  callNow: 'Gọi',
  zaloQuote: 'Báo giá',
  zaloSample: 'Gửi mẫu',
  zaloQuoteMsg:
    'Xin chào,\nTôi muốn nhận báo giá:\n- Mã vải: {code}\n- Tên: {name}\n- Màu: {color}\n- MOQ: {moq}\nVui lòng tư vấn giúp.',
  zaloSampleMsg:
    'Xin chào,\nTôi muốn nhận mẫu:\n- Mã vải: {code}\n- Tên: {name}\n- Màu: {color}\nVui lòng hướng dẫn thủ tục nhận mẫu.',
  composition: 'Thành phần',
  specs: 'Quy cách kỹ thuật',
  specsCommercial: 'Thông tin thương mại',
  weavePattern: 'Kiểu dệt',
  machineType: 'Kỹ thuật',
  fabricType: 'Nhóm vải',
  yieldMetersPerKg: 'Định mức (m/kg)',
  knitted: 'Dệt kim',
  woven: 'Dệt thoi',
  noImage: 'Chưa có hình ảnh',
  width: 'Khổ rộng',
  gsm: 'Định lượng',
  stretch: 'Co giãn',
  thickness: 'Độ dày',
  applications: 'Ứng dụng may mặc',
  characteristics: 'Đặc tính nổi bật',
  moq: 'MOQ tiêu chuẩn',
  moqStock: 'MOQ hàng sẵn',
  moqCustom: 'MOQ đặt sản xuất',
  leadTime: 'Thời gian giao hàng',
  leadTimeStock: 'Thời gian giao hàng sẵn',
  leadTimeCustom: 'Thời gian sản xuất',
  relatedProducts: 'Có thể bạn quan tâm',
  alsoViewedProducts: 'Khách hàng khác cũng xem',
  viewCountPrefix: 'Đã xem bởi',
  viewCountSuffix: 'khách hàng',
  colorViewing: 'Màu đang xem:',
  brandName: 'Vĩnh Phát Textile',
  colorSectionTitle: 'Bảng màu & Biến thể',
  na: 'N/A',
  unitCm: 'cm',
  unitGsm: 'gsm',
  noImageIcon: '📸',
  origin: 'Xuất xứ',
  sampleStatusLabel: 'Tình trạng mẫu',
  stockStatusLabel: 'Tình trạng hàng',
  copiedLink: 'Đã sao chép liên kết chia sẻ!',
  shareTitle: 'Chia sẻ mẫu vải',
  inquiryCartTitle: 'Giỏ Yêu Cầu',
  inquiryCartEmpty: 'Chưa có sản phẩm nào trong giỏ.',
  inquiryCartContinue: 'Tiếp tục xem danh mục',
  inquiryCartRemoveTitle: 'Xóa khỏi giỏ',
  inquiryCartNotice:
    'Yêu cầu sẽ được gửi đến bộ phận chăm sóc khách hàng của Vĩnh Phát.',
  inquiryCartBatchRequest: 'Gửi yêu cầu cả giỏ hàng',
  compareTitle: 'So sánh thông số vải',
  compareEmpty: 'Chọn từ 2 mẫu vải trở lên để tiến hành so sánh.',
  compareLimit: 'Chỉ có thể so sánh tối đa 3 mẫu vải cùng lúc.',
  requestSampleTitle: 'Yêu cầu nhận mẫu vải',
  requestSampleDesc:
    'Vĩnh Phát hỗ trợ gửi mẫu vải miễn phí (Khổ A4/Bản cắt) cho doanh nghiệp và xưởng may.',
  contactNameLabel: 'Họ và tên người nhận',
  contactPhoneLabel: 'Số điện thoại liên hệ',
  contactAddressLabel: 'Địa chỉ nhận mẫu',
  companyNameLabel: 'Tên công ty / Thương hiệu (nếu có)',
  submitRequest: 'Gửi yêu cầu nhận mẫu',
  requestSuccess:
    'Gửi yêu cầu nhận mẫu thành công! Nhân viên Vĩnh Phát sẽ liên hệ xác nhận sớm nhất.',
  requestPending: 'Đang xử lý...',
  saveInquiryCart: 'Thêm vào giỏ',
  savedInquiryCart: 'Đã thêm',
  addToCompare: 'So sánh',
  addedCompare: 'Đã thêm',
  clearAll: 'Xóa tất cả',
  close: 'Đóng',
  volumePricing: 'Bảng giá sỉ & Đại lý',
  pricingTierColQty: 'Số lượng (kg)',
  pricingTierColPrice: 'Đơn giá / kg',
  calculatorTitle: 'Bộ công cụ dự toán chi phí B2B',
  calculatorQtyLabel: 'Nhập số lượng cần mua (kg)',
  calculatorEstPrice: 'Đơn giá dự toán:',
  calculatorEstTotal: 'Tổng chi phí ước tính:',
  calculatorMoqWarning:
    '⚠️ Số lượng dưới mức MOQ ({moq} kg) cho biến thể màu này!',
  rfqBtn: 'Yêu cầu báo giá',
  rfqModalTitle: 'Yêu cầu báo giá chính thức',
  rfqModalDesc:
    'Vui lòng cung cấp thông tin liên hệ và số lượng mong muốn để nhận bảng báo giá chi tiết kèm chiết khấu tốt nhất.',
  rfqTargetPriceLabel: 'Giá kỳ vọng (đ/kg, nếu có)',
  rfqDeliveryDateLabel: 'Ngày mong muốn giao hàng',
  rfqEmailLabel: 'Địa chỉ Email liên hệ',
  rfqSuccess:
    'Gửi yêu cầu báo giá thành công! Đội ngũ Sales sẽ gửi file báo giá chính thức trong vòng 24 giờ.',
  noPricingTiersDesc:
    'Liên hệ bộ phận Sales của Vĩnh Phát để nhận báo giá sỉ & chiết khấu đại lý tốt nhất.',
  contactQuote: 'Liên hệ',
  fabricDetailHeader: 'CHI TIẾT VẢI:',
  requestedQty: 'Số lượng yêu cầu:',
  validationNameRequired: 'Họ tên là bắt buộc',
  validationPhoneRequired: 'Số điện thoại là bắt buộc',
  validationQtyInvalid: 'Số lượng phải là số',
  validationQtyPositive: 'Số lượng phải lớn hơn 0',
  validationEmailInvalid: 'Email không đúng định dạng',
  validationTargetPricePositive: 'Giá kỳ vọng phải lớn hơn 0',
  loginToViewPrice: 'Đăng nhập để xem giá sỉ & đại lý',
  wholesaleOnly: 'Dành cho khách hàng sỉ & đại lý',
  loginBtn: 'Đăng nhập B2B',
  logoutBtn: 'Đăng xuất',
  goToPortal: 'Cổng Portal',
  openInErp: 'Mở trong ERP',
  welcomeCustomer: 'Xin chào,',
  stockAvailableDetail: 'Sẵn có: {qty} {unit} ({rolls} cuộn)',
  orderViaPortal: 'Đặt hàng qua Portal',
  badgePublic: 'Công khai',
  badgeDealer: 'Dealer',
  badgeVIP: 'VIP',
  badgeFactory: 'Factory',
  removeInquiryCartSuccess: 'Đã xóa khỏi giỏ yêu cầu.',
  addInquiryCartSuccess: 'Đã thêm vào giỏ yêu cầu.',
  removeCompareSuccess: 'Đã xóa khỏi danh sách so sánh.',
  addCompareSuccess: 'Đã thêm vào danh sách so sánh.',
  inStock: 'Hàng sẵn',
  customProduction: 'Đặt sản xuất',
  production: 'Sản xuất',
  b2bPlannerTool: 'Công cụ B2B Planner',
  stockStatusColor: 'Trạng thái kho ({color})',
  available: 'Sẵn có',
  outOfStock: 'Hết hàng',
  pricingTierTitle: 'Bảng giá bậc thang',
  loginToViewDiscount:
    'Đăng nhập tài khoản B2B để xem chiết khấu theo số lượng.',
  fromTo: 'Từ {min} - {max}',
  from: 'Từ {min}',
  buyQty: 'Mua {range} {unit}',
  // RFQ Modal & Intents
  rfqIntentQuote: 'Báo giá thương mại',
  rfqIntentQuoteDesc: 'MOQ từ 100kg, giá sỉ theo số lượng',
  rfqIntentBulk: 'Báo giá số lượng lớn',
  rfqIntentBulkDesc: 'Trên 1 tấn, chiết khấu đặc biệt',
  rfqIntentOem: 'Sản xuất OEM',
  rfqIntentOemDesc: 'Đặt riêng theo yêu cầu thương hiệu',
  rfqIntentProcessing: 'Gia công hoàn thiện',
  rfqIntentProcessingDesc: 'Nhuộm, in, xử lý bề mặt',
  rfqWhatDoYouNeed: 'Bạn cần gì?',
  rfqFabricRequested: 'MÃ VẢI YÊU CẦU:',
  rfqPlaceholderName: 'VD: Nguyễn Văn A',
  rfqPlaceholderPhone: 'VD: 0989xxxxxx',
  rfqPlaceholderEmail: 'VD: khachhang@gmail.com',
  rfqPlaceholderCompany: 'VD: Thời trang Tấn Phát',
  rfqSubmitBtn: 'Gửi yêu cầu',
  rfqSubmitFailed: 'Gửi yêu cầu báo giá thất bại:',
  rfqZaloFallbackMsg:
    'Xin chào,\nTôi muốn nhận báo giá:\n- Mã vải: {code}\n- Tên: {name}\n- Màu: {color}\nVui lòng tư vấn giúp.',
  rfqSuccessTitle: 'Đã gửi thành công!',
  rfqLeadId: 'Mã yêu cầu:',
  rfqSuccessWait1: 'Đội ngũ Sales Vĩnh Phát sẽ liên hệ phản hồi bạn trong vòng',
  rfqSuccessWait2: '< 24 giờ',
  rfqSuccessWait3: 'làm việc.',
  rfqViewMore: 'Xem thêm mẫu vải',
  rfqCloseBtn: 'Đóng',
  rfqAllColors: 'Tất cả màu',
  rfqZaloQuick: 'Liên hệ nhanh qua Zalo',
  orOption: 'hoặc',
  fromPrefix: 'Từ',
} as const;

export const IMAGE_TYPE_MAP: Record<string, string> = {
  SWATCH: 'Mẫu vải',
  SURFACE: 'Chi tiết sợi',
  BACK: 'Mặt trái',
  STRETCH: 'Độ co giãn',
  APPLICATION: 'Ứng dụng',
  COMPOSITION: 'Thành phần',
  CERTIFICATE: 'Chứng nhận',
};

export const STRETCH_TYPE_MAP: Record<string, string> = {
  NONE: 'Không co giãn',
  HORIZONTAL: 'Co giãn ngang',
  VERTICAL: 'Co giãn dọc',
  TWO_WAY: 'Co giãn 2 chiều',
  FOUR_WAY: 'Co giãn 4 chiều',
};

export const THICKNESS_MAP: Record<string, string> = {
  THIN: 'Mỏng',
  MEDIUM: 'Trung bình',
  THICK: 'Dày',
  EXTRA_THICK: 'Rất dày',
};

export const LEAD_TIME_UNIT_MAP: Record<string, string> = {
  day: 'ngày',
  week: 'tuần',
  month: 'tháng',
  DAY: 'ngày',
  WEEK: 'tuần',
  MONTH: 'tháng',
};
