import type { FilterFieldConfig } from '@/shared/components';

export const YARN_CATALOG_MESSAGES = {
  EMPTY_TITLE: 'Chưa có loại sợi nào',
  EMPTY_DESC: 'Nhấn "+ Thêm loại sợi" để bắt đầu quản lý danh mục sợi.',
  NOT_FOUND_TITLE: 'Không tìm thấy loại sợi phù hợp',
  NOT_FOUND_DESC: 'Thử điều chỉnh bộ lọc.',
  BTN_ADD: '+ Thêm loại sợi',
  LOAD_ERROR: 'Lỗi tải dữ liệu',
  DELETE_ERROR: 'Lỗi xóa',
  DELETE_CONFIRM: 'Xóa loại sợi "{name}"? Hành động này không thể hoàn tác.',
  EXPORT_FILENAME: 'Danh_Muc_Soi',
  PAGINATION_LABEL: 'loại sợi',
  ARIA_LIST_CONTAINER: 'Danh sách danh mục sợi',
  ARIA_ADD_NEW: 'Thêm loại sợi mới',
  ARIA_FILTER_BAR: 'Bộ lọc danh sách',
  ARIA_DATA_TABLE: 'Bảng dữ liệu mã sợi',

  KPI_TOTAL: 'Tổng mã sợi',
  KPI_TOTAL_DESC: 'Trong danh mục hệ thống',
  KPI_COLOR: 'Màu sắc',
  KPI_COLOR_DESC: 'Đa dạng phân loại màu',
  KPI_ACTIVE: 'Đang hoạt động',
  KPI_ACTIVE_DESC: 'Sẵn dụng cho nghiệp vụ',

  PAGE_TITLE: 'Sợi',
  PAGE_SUBTITLE: 'Quản lý danh mục sợi',

  ERROR_GENERIC: 'Có lỗi xảy ra',
  UNSAVED_WARNING: 'Bạn có thông tin chưa lưu. Bạn có chắc chắn muốn đóng?',
  UNSAVED_TITLE: 'Chưa lưu',
  BTN_CONTINUE_EDIT: 'Tiếp tục chỉnh sửa',
  BTN_CLOSE: 'Đóng',
  MSG_UPDATE_SUCCESS: 'Cập nhật thành công',
  MSG_CREATE_SUCCESS: 'Thêm mới thành công',
  ERROR_PREFIX: 'Lỗi: ',
  FORM_TITLE_EDIT: 'Sửa:',
  FORM_TITLE_NEW: 'Thêm loại sợi',
  BTN_UPDATE: 'Cập nhật',
  BTN_CREATE: 'Thêm loại sợi',
  BTN_EDIT: 'Sửa',

  SECTION_CERT: 'Chứng chỉ quốc tế',
  SECTION_ADDITIONAL: 'Thông tin bổ sung',
  LBL_LOT_NO: 'Mã lô (Lot No)',
  LBL_GRADE: 'Phân loại (Grade)',
  LBL_UNIT: 'Đơn vị',
  LBL_STATUS: 'Trạng thái',
  PLACEHOLDER_SELECT: 'Chọn...',
  LBL_NOTES: 'Ghi chú',
  PLACEHOLDER_NOTES: 'Ghi chú về loại sợi...',
  LBL_LOT_GRADE: 'Mã lô / Loại',

  SECTION_GENERAL: 'Thông tin chung',
  LBL_CODE: 'Mã sợi',
  LBL_NAME: 'Tên loại sợi',
  LBL_COMPOSITION: 'Thành phần',

  SECTION_TECH: 'Phân loại kỹ thuật',
  LBL_CATEGORY: 'Chất liệu (Level 1)',
  LBL_YARN_TYPE: 'Loại sợi (Level 2)',
  LBL_COUNT_NE: 'Chi số (Ne)',
  LBL_SPINNING: 'Phương pháp kéo sợi',
  LBL_DENIER: 'Denier',
  LBL_FILAMENT: 'Filament',
  LBL_TENSILE: 'Cường lực',
  LBL_TWIST: 'Hướng xoắn / Kiểu xoắn',
  LBL_FANCY: 'Sợi Fancy (Slub, Injection...)',
  LBL_FANCY_DETAIL: 'Chi tiết Fancy',
  SECTION_EFFECT: 'Hiệu ứng & Màu sắc',
  LBL_FINISH: 'Finish (Bề mặt)',
  LBL_COLOR_STATUS: 'Trạng thái màu',
  LBL_COLOR_NAME: 'Màu mặc định',
  LBL_INTERMINGLE: 'Độ đan gút (Intermingle)',

  SECTION_KNITTING: 'Kỹ thuật dệt (Engineering Matrix)',
  EMPTY_KNITTING_TITLE: 'Sợi chưa được lưu',
  EMPTY_KNITTING_DESC:
    'Bạn cần lưu Thông tin Sợi này trước khi có thể cấu hình Kỹ thuật dệt (Machine Spec).',
  LBL_KNITTING_LIST: 'Danh sách cấu hình máy dệt',
  BTN_ADD_KNITTING: 'Thêm cấu hình',
  EMPTY_MATRIX_TITLE: 'Chưa có cấu hình',
  EMPTY_MATRIX_DESC: 'Chưa có cấu hình máy dệt nào được thiết lập.',
  VAL_UNKNOWN: 'Không rõ',
  VAL_EMPTY_CONFIG: 'Cấu hình trống',
  CONFIRM_DEL_MATRIX_TITLE: 'Xóa cấu hình',
  CONFIRM_DEL_MATRIX_DESC: 'Bạn có chắc chắn muốn xóa cấu hình máy dệt này?',
  BTN_DELETE: 'Xóa',
  BTN_CANCEL: 'Hủy',
  COL_ACTIONS: 'Thao tác',
  COL_LEVEL: 'Mức độ',
  COL_RPM: 'RPM',
  MATRIX_HINT:
    'Cấu hình này sẽ được sử dụng để gợi ý máy dệt và thiết lập thông số tự động trên ứng dụng MES.',

  MATRIX_TITLE_EDIT: 'Cập nhật cấu hình máy dệt',
  MATRIX_TITLE_NEW: 'Thêm cấu hình máy dệt',
  MATRIX_LBL_STRUCTURE: 'Kiểu dệt',
  MATRIX_LBL_MACHINE: 'Cấu hình máy',
  MATRIX_LBL_LEVEL: 'Mức độ tương thích',
  MATRIX_VAL_UNKNOWN: 'Chưa xác định',
  MATRIX_VAL_POSITIVE: 'Tích cực (Positive)',
  MATRIX_VAL_NEGATIVE: 'Tiêu cực (Negative)',
  MATRIX_VAL_AUTO: 'Tự động (Auto)',
  MATRIX_LBL_FEEDING: 'Kiểu cấp sợi (Feeding Type)',
  MATRIX_LBL_REC_RPM: 'Tốc độ (RPM) khuyên dùng',
  MATRIX_LBL_MAX_RPM: 'Tốc độ (RPM) tối đa',
  MATRIX_LBL_EFFICIENCY: 'Hiệu suất kỳ vọng (0-1)',
  MATRIX_LBL_WASTE: 'Tỷ lệ hao hụt dự kiến (0-1)',
  MATRIX_LBL_TENSION: 'Sức căng khuyên dùng',
  MATRIX_LBL_STITCH: 'Stitch Length khuyên dùng (mm)',
  MATRIX_LBL_SPECIAL_FEEDER: 'Cần Feeder đặc biệt',
  MATRIX_LBL_LYCRA: 'Cần đính kèm Lycra (Spandex)',
  MATRIX_LBL_NOTES: 'Ghi chú sản xuất',
  MATRIX_BTN_SAVE: 'Lưu cấu hình',
} as const;

export const YARN_CATALOG_FILTER_SCHEMA: FilterFieldConfig[] = [
  {
    key: 'search',
    type: 'search',
    label: 'Tìm kiếm',
    placeholder: 'Tên, mã, thành phần...',
  },
  {
    key: 'status',
    type: 'combobox',
    label: 'Trạng thái',
    options: [
      {
        value: 'active',
        label: 'Đang dùng',
      },
      {
        value: 'inactive',
        label: 'Ngừng dùng',
      },
    ],
  },
  {
    key: 'lot_no',
    type: 'search',
    label: 'Mã lô',
    placeholder: 'Tìm theo lô...',
  },
  {
    key: 'grade',
    type: 'search',
    label: 'Phân loại',
    placeholder: 'Loại A, B...',
  },
];
