import type { DocumentType, FieldDefinition } from './types';

export const FIELD_REGISTRY: FieldDefinition[] = [
  // Company
  {
    id: 'company.name',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Tên Doanh Nghiệp',
    category: 'company',
    sampleValue: 'CÔNG TY TNHH DỆT MAY VĨNH PHÁT',
  },
  {
    id: 'company.address',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Địa Chỉ Nhà Máy',
    category: 'company',
    sampleValue: 'Lô 12 Đường Số 3, KCN Tân Bình, Tây Thạnh, TP.HCM',
  },
  {
    id: 'company.tax_code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Mã Số Thuế',
    category: 'company',
    sampleValue: '0314567890',
  },
  {
    id: 'company.phone',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Hotline / Điện Thoại',
    category: 'company',
    sampleValue: '028 3815 1234',
  },

  // Document
  {
    id: 'shipment.code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Mã Phiếu Xuất',
    category: 'document',
    sampleValue: 'XK2604-0001',
  },
  {
    id: 'shipment.date',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'date',
    label: 'Ngày Xuất Kho',
    category: 'document',
    sampleValue: '2026-04-02',
  },
  {
    id: 'shipment.order_code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Đơn Hàng Gốc',
    category: 'document',
    sampleValue: 'DH2604-0012',
  },

  // Customer
  {
    id: 'customer.name',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Tên Khách Hàng',
    category: 'customer',
    sampleValue: 'Công ty TNHH May Mặc Thời Trang Á Đông',
  },
  {
    id: 'customer.code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Mã Khách Hàng',
    category: 'customer',
    sampleValue: 'KH-ADONG-01',
  },
  {
    id: 'customer.delivery_address',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Địa Chỉ Giao Hàng',
    category: 'customer',
    sampleValue: '456 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
  },
  {
    id: 'customer.contact_phone',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Số Điện Thoại Nhận',
    category: 'customer',
    sampleValue: '0909 123 456',
  },

  // Transport
  {
    id: 'transport.carrier',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Xe Vận Chuyển / Lái Xe',
    category: 'transport',
    sampleValue: 'Xe tải Vĩnh Phát (51C-123.45)',
  },

  // Collection
  {
    id: 'shipment.items',
    documentType: 'shipment_delivery',
    kind: 'collection',
    dataType: 'array',
    label: 'Danh Sách Cây Vải',
    category: 'items',
    sampleValue: [
      {
        roll_number: 'C01',
        fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
        color_name: 'Trắng Sứ (W-01)',
        quantity: 120.5,
        unit: 'm',
      },
      {
        roll_number: 'C02',
        fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
        color_name: 'Trắng Sứ (W-01)',
        quantity: 118.0,
        unit: 'm',
      },
      {
        roll_number: 'C03',
        fabric_type: 'Vải CVC 65/35 Cá Sấu 4 chiều',
        color_name: 'Xanh Navy (NV-09)',
        quantity: 145.2,
        unit: 'm',
      },
    ],
  },

  // Computed Totals
  {
    id: 'shipment.totals.rolls_count',
    documentType: 'shipment_delivery',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Số Cây Vải',
    category: 'totals',
    sampleValue: 3,
  },
  {
    id: 'shipment.totals.total_meters',
    documentType: 'shipment_delivery',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Chiều Dài (m)',
    category: 'totals',
    sampleValue: 383.7,
  },
  {
    id: 'shipment.totals.total_weight_kg',
    documentType: 'shipment_delivery',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Khối Lượng (Kg)',
    category: 'totals',
    sampleValue: 88.25,
  },

  // ── Bảng kê danh sách cây vải (packing_list) ──
  {
    id: 'document.number',
    documentType: 'packing_list',
    kind: 'scalar',
    dataType: 'string',
    label: 'Số Bảng Kê',
    category: 'document',
    sampleValue: 'PKL-2026-001',
  },
  {
    id: 'document.date',
    documentType: 'packing_list',
    kind: 'scalar',
    dataType: 'date',
    label: 'Ngày Lập Bảng Kê',
    category: 'document',
    sampleValue: '2026-09-27',
  },
  {
    id: 'customer.name',
    documentType: 'packing_list',
    kind: 'scalar',
    dataType: 'string',
    label: 'Đơn Vị Nhận Hàng',
    category: 'customer',
    sampleValue: 'Công ty TNHH May Mặc Đối Tác',
  },
  {
    id: 'transport.license_plate',
    documentType: 'packing_list',
    kind: 'scalar',
    dataType: 'string',
    label: 'Biển Số Xe',
    category: 'transport',
    sampleValue: '51D-12345',
  },
  {
    id: 'transport.driver_name',
    documentType: 'packing_list',
    kind: 'scalar',
    dataType: 'string',
    label: 'Tài Xế Giao Nhận',
    category: 'transport',
    sampleValue: 'Nguyễn Văn A',
  },
  {
    id: 'packing_list.rolls',
    documentType: 'packing_list',
    kind: 'collection',
    dataType: 'array',
    label: 'Danh Sách Cây Vải',
    category: 'items',
    sampleValue: [
      {
        roll_code: 'C01',
        fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
        color_name: 'Trắng Sứ (W-01)',
        length_meters: 120.5,
        weight_kg: 23.5,
        grade: 'A',
      },
      {
        roll_code: 'C02',
        fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
        color_name: 'Trắng Sứ (W-01)',
        length_meters: 118.0,
        weight_kg: 24.5,
        grade: 'B',
      },
    ],
  },
  {
    id: 'packing_list.totals.total_rolls',
    documentType: 'packing_list',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Số Cây Vải',
    category: 'totals',
    sampleValue: 2,
  },
  {
    id: 'packing_list.totals.total_weight_kg',
    documentType: 'packing_list',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Khối Lượng (Kg)',
    category: 'totals',
    sampleValue: 48.0,
  },
];

export function getFieldsForDocument(docType: DocumentType): FieldDefinition[] {
  return FIELD_REGISTRY.filter(
    (f) => f.documentType === docType || f.category === 'company',
  );
}
