import type {
  DocumentType,
  FieldDefinition,
  PrintTemplateEntity,
} from './types';

export const FIELD_REGISTRY: FieldDefinition[] = [
  // Company
  {
    id: 'company.name',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Tên Doanh Nghiệp',
    category: 'company',
    sampleValue: 'CÔNG TY TNHH DỆT MAY VĨNH PHÁT',
  },
  {
    id: 'company.address',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Địa Chỉ Nhà Máy',
    category: 'company',
    sampleValue: 'Lô 12 Đường Số 3, KCN Tân Bình, Tây Thạnh, TP.HCM',
  },
  {
    id: 'company.tax_code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Mã Số Thuế',
    category: 'company',
    sampleValue: '0314567890',
  },
  {
    id: 'company.phone',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Hotline / Điện Thoại',
    category: 'company',
    sampleValue: '028 3815 1234',
  },

  // Document
  {
    id: 'shipment.code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Mã Phiếu Xuất',
    category: 'document',
    sampleValue: 'XK2604-0001',
  },
  {
    id: 'shipment.date',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'date',
    label: 'Ngày Xuất Kho',
    category: 'document',
    sampleValue: '2026-04-02',
  },
  {
    id: 'shipment.order_code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Đơn Hàng Gốc',
    category: 'document',
    sampleValue: 'DH2604-0012',
  },

  // Customer
  {
    id: 'customer.name',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Tên Khách Hàng',
    category: 'customer',
    sampleValue: 'Công ty TNHH May Mặc Thời Trang Á Đông',
  },
  {
    id: 'customer.code',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Mã Khách Hàng',
    category: 'customer',
    sampleValue: 'KH-ADONG-01',
  },
  {
    id: 'customer.delivery_address',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Địa Chỉ Giao Hàng',
    category: 'customer',
    sampleValue: '456 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
  },
  {
    id: 'customer.contact_phone',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Số Điện Thoại Nhận',
    category: 'customer',
    sampleValue: '0909 123 456',
  },

  // Transport
  {
    id: 'transport.carrier',
    documentType: 'shipment_delivery',
    kind: 'scalar',
    dataType: 'string',
    label: 'Xe Vận Chuyển / Lái Xe',
    category: 'transport',
    sampleValue: 'Xe tải Vĩnh Phát (51C-123.45)',
  },

  // Collection
  {
    id: 'shipment.items',
    documentType: 'shipment_delivery',
    kind: 'collection',
    dataType: 'array',
    label: 'Danh Sách Cây Vải',
    category: 'items',
    sampleValue: [
      {
        roll_number: 'C01',
        fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
        color_name: 'Trắng Sứ (W-01)',
        quantity: 120.5,
        unit: 'm',
      },
      {
        roll_number: 'C02',
        fabric_type: 'Vải Cotton 100% 2 chiều 230gsm',
        color_name: 'Trắng Sứ (W-01)',
        quantity: 118.0,
        unit: 'm',
      },
      {
        roll_number: 'C03',
        fabric_type: 'Vải CVC 65/35 Cá Sấu 4 chiều',
        color_name: 'Xanh Navy (NV-09)',
        quantity: 145.2,
        unit: 'm',
      },
    ],
  },

  // Computed Totals
  {
    id: 'shipment.totals.rolls_count',
    documentType: 'shipment_delivery',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Số Cây Vải',
    category: 'totals',
    sampleValue: 3,
  },
  {
    id: 'shipment.totals.total_meters',
    documentType: 'shipment_delivery',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Chiều Dài (m)',
    category: 'totals',
    sampleValue: 383.7,
  },
  {
    id: 'shipment.totals.total_weight_kg',
    documentType: 'shipment_delivery',
    kind: 'computed',
    dataType: 'number',
    label: 'Tổng Khối Lượng (Kg)',
    category: 'totals',
    sampleValue: 88.25,
  },
];

export function getFieldsForDocument(docType: DocumentType): FieldDefinition[] {
  return FIELD_REGISTRY.filter(
    (f) => f.documentType === docType || f.category === 'company',
  );
}

export const DEFAULT_PRINT_TEMPLATES_SEED: PrintTemplateEntity[] = [
  {
    id: 'tpl-shipment-a5-dot-matrix',
    code: 'XK_DOT_MATRIX_A5',
    name: 'Phiếu Xuất Kho Giao Hàng (In Kim 3 Liên)',
    description:
      'Mẫu in chuyên dụng cho máy in kim Epson LQ-310 trên giấy đục lỗ liên tục A5',
    artifactType: 'document',
    documentType: 'shipment_delivery',
    targetPrinterProfile: 'dot_matrix',
    paperFormat: 'A5',
    orientation: 'landscape',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 200,
        heightMm: 148,
        marginTopMm: 4,
        marginBottomMm: 4,
        marginLeftMm: 3,
        marginRightMm: 3,
      },
      styles: {
        fontFamily: 'Courier_Mono',
        baseFontSizePt: 9,
        showTractorHoles: true,
      },
      blocks: [
        {
          id: 'b-header',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'CÔNG TY TNHH DỆT MAY VĨNH PHÁT',
          fontSizePt: 11,
          fontWeight: 'bold',
          align: 'left',
        },
        {
          id: 'b-title',
          order: 2,
          enabled: true,
          type: 'text',
          content: 'PHIẾU XUẤT KHO KIÊM BIÊN BẢN BÀN GIAO',
          fontSizePt: 13,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-meta',
          order: 3,
          enabled: true,
          type: 'text',
          content:
            'Khách hàng: {{customer.name}} | Số phiếu: {{shipment.code}}',
          fontSizePt: 9,
          fontWeight: 'normal',
          align: 'left',
        },
        {
          id: 'b-table',
          order: 4,
          enabled: true,
          type: 'table',
          collectionBinding: 'shipment.items',
          rowHeightMm: 6,
          borderStyle: 'dashed',
          showTotalRow: true,
          columns: [
            {
              key: 'stt',
              label: 'STT',
              widthPercent: 8,
              align: 'center',
              fieldBinding: 'index',
            },
            {
              key: 'roll_number',
              label: 'Mã Cây',
              widthPercent: 15,
              align: 'center',
              fieldBinding: 'roll_number',
            },
            {
              key: 'fabric_type',
              label: 'Tên Hàng / Quy Cách',
              widthPercent: 40,
              align: 'left',
              fieldBinding: 'fabric_type',
            },
            {
              key: 'color_name',
              label: 'Màu Sắc',
              widthPercent: 20,
              align: 'left',
              fieldBinding: 'color_name',
            },
            {
              key: 'quantity',
              label: 'Số Mét',
              widthPercent: 17,
              align: 'right',
              fieldBinding: 'quantity',
              formatter: 'length_m',
            },
          ],
        },
        {
          id: 'b-signatures',
          order: 5,
          enabled: true,
          type: 'signature',
          slots: [
            { title: 'Người Lập Phiếu', subtitle: '(Ký, ghi rõ họ tên)' },
            { title: 'Thủ Kho Xuất', subtitle: '(Ký, đóng dấu)' },
            { title: 'Người Nhận Hàng', subtitle: '(Ký, ghi rõ họ tên)' },
          ],
        },
        {
          id: 'b-footer',
          order: 6,
          enabled: true,
          type: 'text',
          content:
            'Vui lòng kiểm tra kỹ số lượng và chất lượng trước khi rời kho.',
          fontSizePt: 8,
          fontWeight: 'normal',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-shipment-a4-laser',
    code: 'XK_LASER_A4',
    name: 'Phiếu Xuất Kho A4 (Laser / PDF Văn Phòng)',
    description:
      'Mẫu in khổ A4 đứng tiêu chuẩn kèm Logo thương hiệu và Mã QR bảo mật',
    artifactType: 'document',
    documentType: 'shipment_delivery',
    targetPrinterProfile: 'laser',
    paperFormat: 'A4',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 297,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 10,
        marginRightMm: 10,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 10,
        showTractorHoles: false,
      },
      blocks: [
        {
          id: 'b-header-logo',
          order: 1,
          enabled: true,
          type: 'image',
          fallbackUrl: '/favicon.svg',
          fit: 'contain',
        },
        {
          id: 'b-header',
          order: 2,
          enabled: true,
          type: 'text',
          content: 'CÔNG TY TNHH DỆT MAY VĨNH PHÁT',
          fontSizePt: 14,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-title',
          order: 3,
          enabled: true,
          type: 'text',
          content: 'PHIẾU XUẤT KHO GIAO HÀNG',
          fontSizePt: 16,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-table',
          order: 4,
          enabled: true,
          type: 'table',
          collectionBinding: 'shipment.items',
          rowHeightMm: 8,
          borderStyle: 'solid',
          showTotalRow: true,
          columns: [
            {
              key: 'stt',
              label: 'STT',
              widthPercent: 8,
              align: 'center',
              fieldBinding: 'index',
            },
            {
              key: 'roll_number',
              label: 'Mã Cây',
              widthPercent: 17,
              align: 'center',
              fieldBinding: 'roll_number',
            },
            {
              key: 'fabric_type',
              label: 'Loại Vải',
              widthPercent: 40,
              align: 'left',
              fieldBinding: 'fabric_type',
            },
            {
              key: 'color_name',
              label: 'Màu Sắc',
              widthPercent: 20,
              align: 'left',
              fieldBinding: 'color_name',
            },
            {
              key: 'quantity',
              label: 'Số Mét (m)',
              widthPercent: 15,
              align: 'right',
              fieldBinding: 'quantity',
              formatter: 'length_m',
            },
          ],
        },
        {
          id: 'b-qr',
          order: 5,
          enabled: true,
          type: 'qr',
          valueBinding: 'shipment.code',
          sizeMm: 25,
        },
        {
          id: 'b-signatures',
          order: 6,
          enabled: true,
          type: 'signature',
          slots: [
            { title: 'Người Lập Phiếu' },
            { title: 'Thủ Kho Xuất' },
            { title: 'Lái Xe / Giao Hàng' },
            { title: 'Khách Hàng Ký Nhận' },
          ],
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-roll-tag-barcode',
    code: 'TEM_CAY_VAI_K80',
    name: 'Tem Nhãn Cuộn Vải Barcode (K80 / Decal Nhiệt)',
    description: 'Tem nhãn dán đầu cây vải kiểm soát kho với mã vạch Code128',
    artifactType: 'label',
    documentType: 'roll_tag',
    targetPrinterProfile: 'thermal_label',
    paperFormat: 'DECAL_CUSTOM',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 80,
        heightMm: 60,
        marginTopMm: 2,
        marginBottomMm: 2,
        marginLeftMm: 2,
        marginRightMm: 2,
        gapMm: 3,
        isContinuous: false,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 9,
      },
      blocks: [
        {
          id: 'b-tag-company',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'DỆT MAY VĨNH PHÁT',
          fontSizePt: 10,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-tag-barcode',
          order: 2,
          enabled: true,
          type: 'barcode',
          format: 'CODE128',
          valueBinding: 'roll.number',
          showText: true,
        },
        {
          id: 'b-tag-meta',
          order: 3,
          enabled: true,
          type: 'text',
          content:
            'Cây: {{roll.number}} | Dài: {{roll.meters}}m | Nặng: {{roll.weight}}kg',
          fontSizePt: 8,
          fontWeight: 'bold',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-inventory-receipt-a4',
    code: 'NK_LASER_A4',
    name: 'Phiếu Nhập Kho Sợi & Hóa Chất (A4 Laser)',
    description:
      'Mẫu nhập kho nghiệm thu nguyên vật liệu sợi dệt và thuốc nhuộm',
    artifactType: 'document',
    documentType: 'inventory_receipt',
    targetPrinterProfile: 'laser',
    paperFormat: 'A4',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 297,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 10,
        marginRightMm: 10,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 10,
      },
      blocks: [
        {
          id: 'b-title',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'PHIẾU NHẬP KHO NGUYÊN PHỤ LIỆU',
          fontSizePt: 16,
          fontWeight: 'bold',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-production-order-a4',
    code: 'SX_LENH_DET_A4',
    name: 'Lệnh Sản Xuất Dệt & Công Thức Nhuộm (A4 Laser)',
    description: 'Bản giao ca xưởng dệt và lệnh nhuộm hoàn tất',
    artifactType: 'document',
    documentType: 'production_order',
    targetPrinterProfile: 'laser',
    paperFormat: 'A4',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 297,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 10,
        marginRightMm: 10,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 10,
      },
      blocks: [
        {
          id: 'b-title',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'LỆNH SẢN XUẤT DỆT & HOÀN TẤT',
          fontSizePt: 16,
          fontWeight: 'bold',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
