// Fabric roll packing list templates (A5 landscape matrix, laser + dot-matrix).
import type { PrintTemplateEntity } from './types';

export const PACKING_LIST_TEMPLATES: PrintTemplateEntity[] = [
  {
    id: 'tpl-packing-list-a5-laser',
    code: 'BKCAY_LASER_A5',
    name: 'Bảng Kê Cây Vải A5 Ngang (Laser / PDF)',
    description:
      'Bảng kê danh sách cây vải dạng ma trận 10 cây/dòng khổ A5 ngang, in trên máy laser hoặc xuất PDF',
    artifactType: 'document',
    documentType: 'packing_list',
    targetPrinterProfile: 'laser',
    paperFormat: 'A5',
    orientation: 'landscape',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 148,
        marginTopMm: 6,
        marginBottomMm: 6,
        marginLeftMm: 8,
        marginRightMm: 8,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 9,
      },
      blocks: [
        {
          id: 'b-header',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'CÔNG TY TNHH SX TM DỆT MAY VĨNH PHÁT',
          fontSizePt: 10,
          fontWeight: 'bold',
          align: 'left',
        },
        {
          id: 'b-title',
          order: 2,
          enabled: true,
          type: 'text',
          content: 'BẢNG KÊ CÂY VẢI (PACKING LIST)',
          fontSizePt: 12,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-meta',
          order: 3,
          enabled: true,
          type: 'text',
          content:
            'Số: {{document.number}} | Khách hàng: {{customer.name}} | Xe: {{transport.license_plate}}',
          fontSizePt: 8,
          fontWeight: 'normal',
          align: 'left',
        },
        {
          id: 'b-table',
          order: 4,
          enabled: true,
          type: 'table',
          collectionBinding: 'packing_list.rolls',
          rowHeightMm: 8,
          borderStyle: 'solid',
          showTotalRow: true,
          columns: [
            {
              key: 'stt',
              label: 'STT',
              widthPercent: 6,
              align: 'center',
              fieldBinding: 'index',
            },
            {
              key: 'roll_code',
              label: 'Mã Cây',
              widthPercent: 22,
              align: 'center',
              fieldBinding: 'roll_code',
            },
            {
              key: 'fabric_type',
              label: 'Loại Vải',
              widthPercent: 24,
              align: 'left',
              fieldBinding: 'fabric_type',
            },
            {
              key: 'color_name',
              label: 'Màu',
              widthPercent: 18,
              align: 'left',
              fieldBinding: 'color_name',
            },
            {
              key: 'length_meters',
              label: 'Dài (m)',
              widthPercent: 13,
              align: 'right',
              fieldBinding: 'length_meters',
              formatter: 'length_m',
            },
            {
              key: 'weight_kg',
              label: 'Nặng (kg)',
              widthPercent: 12,
              align: 'right',
              fieldBinding: 'weight_kg',
              formatter: 'weight_kg',
            },
            {
              key: 'grade',
              label: 'Loại',
              widthPercent: 5,
              align: 'center',
              fieldBinding: 'grade',
            },
          ],
        },
        {
          id: 'b-signatures',
          order: 5,
          enabled: true,
          type: 'signature',
          slots: [
            { title: 'Người Lập Bảng', subtitle: '(Ký, họ tên)' },
            { title: 'Thủ Kho Xuất', subtitle: '(Ký, họ tên)' },
            { title: 'Tài Xế Giao Nhận', subtitle: '(Ký, họ tên)' },
            { title: 'Đại Diện Khách Hàng', subtitle: '(Ký, nhận đủ cây)' },
          ],
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-packing-list-a5-dot-matrix',
    code: 'BKCAY_DOT_MATRIX_A5',
    name: 'Bảng Kê Cây Vải (In Kim 3 Liên A5)',
    description:
      'Mẫu in kim liên tục cho bảng kê cây vải xuất xưởng, tối ưu máy in Epson LQ-310',
    artifactType: 'document',
    documentType: 'packing_list',
    targetPrinterProfile: 'dot_matrix',
    paperFormat: 'A5',
    orientation: 'landscape',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 200,
        heightMm: 148,
        marginTopMm: 4,
        marginBottomMm: 4,
        marginLeftMm: 3,
        marginRightMm: 3,
      },
      styles: {
        fontFamily: 'Courier_Mono',
        baseFontSizePt: 8,
        showTractorHoles: true,
      },
      blocks: [
        {
          id: 'b-header',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'CÔNG TY TNHH SX TM DỆT MAY VĨNH PHÁT',
          fontSizePt: 9,
          fontWeight: 'bold',
          align: 'left',
        },
        {
          id: 'b-title',
          order: 2,
          enabled: true,
          type: 'text',
          content: 'BẢNG KÊ CÂY VẢI',
          fontSizePt: 11,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-meta',
          order: 3,
          enabled: true,
          type: 'text',
          content: 'Số: {{document.number}} | Xe: {{transport.license_plate}}',
          fontSizePt: 8,
          fontWeight: 'normal',
          align: 'left',
        },
        {
          id: 'b-table',
          order: 4,
          enabled: true,
          type: 'table',
          collectionBinding: 'packing_list.rolls',
          rowHeightMm: 6,
          borderStyle: 'dashed',
          showTotalRow: true,
          columns: [
            {
              key: 'stt',
              label: 'STT',
              widthPercent: 7,
              align: 'center',
              fieldBinding: 'index',
            },
            {
              key: 'roll_code',
              label: 'Mã Cây',
              widthPercent: 24,
              align: 'center',
              fieldBinding: 'roll_code',
            },
            {
              key: 'fabric_type',
              label: 'Loại Vải',
              widthPercent: 26,
              align: 'left',
              fieldBinding: 'fabric_type',
            },
            {
              key: 'color_name',
              label: 'Màu',
              widthPercent: 18,
              align: 'left',
              fieldBinding: 'color_name',
            },
            {
              key: 'weight_kg',
              label: 'Nặng (kg)',
              widthPercent: 15,
              align: 'right',
              fieldBinding: 'weight_kg',
              formatter: 'weight_kg',
            },
            {
              key: 'grade',
              label: 'Loại',
              widthPercent: 10,
              align: 'center',
              fieldBinding: 'grade',
            },
          ],
        },
        {
          id: 'b-signatures',
          order: 5,
          enabled: true,
          type: 'signature',
          slots: [
            { title: 'Người Lập Bảng' },
            { title: 'Thủ Kho Xuất' },
            { title: 'Tài Xế Giao Nhận' },
            { title: 'Khách Hàng Nhận' },
          ],
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
