// Roll tag, inventory receipt and production order print templates.
import type { PrintTemplateEntity } from './types';

export const LABEL_AND_RECEIPT_TEMPLATES: PrintTemplateEntity[] = [
  {
    id: 'tpl-roll-tag-barcode',
    code: 'TEM_CAY_VAI_K80',
    name: 'Tem Nhãn Cuộn Vải Barcode (K80 / Decal Nhiệt)',
    description: 'Tem nhãn dán đầu cây vải kiểm soát kho với mã vạch Code128',
    artifactType: 'label',
    documentType: 'roll_tag',
    targetPrinterProfile: 'thermal_label',
    paperFormat: 'DECAL_CUSTOM',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 80,
        heightMm: 60,
        marginTopMm: 2,
        marginBottomMm: 2,
        marginLeftMm: 2,
        marginRightMm: 2,
        gapMm: 3,
        isContinuous: false,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 9,
      },
      blocks: [
        {
          id: 'b-tag-company',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'DỆT MAY VĨNH PHÁT',
          fontSizePt: 10,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-tag-barcode',
          order: 2,
          enabled: true,
          type: 'barcode',
          format: 'CODE128',
          valueBinding: 'roll.number',
          showText: true,
        },
        {
          id: 'b-tag-meta',
          order: 3,
          enabled: true,
          type: 'text',
          content:
            'Cây: {{roll.number}} | Dài: {{roll.meters}}m | Nặng: {{roll.weight}}kg',
          fontSizePt: 8,
          fontWeight: 'bold',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-inventory-receipt-a4',
    code: 'NK_LASER_A4',
    name: 'Phiếu Nhập Kho Sợi & Hóa Chất (A4 Laser)',
    description:
      'Mẫu nhập kho nghiệm thu nguyên vật liệu sợi dệt và thuốc nhuộm',
    artifactType: 'document',
    documentType: 'inventory_receipt',
    targetPrinterProfile: 'laser',
    paperFormat: 'A4',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 297,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 10,
        marginRightMm: 10,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 10,
      },
      blocks: [
        {
          id: 'b-title',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'PHIẾU NHẬP KHO NGUYÊN PHỤ LIỆU',
          fontSizePt: 16,
          fontWeight: 'bold',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-production-order-a4',
    code: 'SX_LENH_DET_A4',
    name: 'Lệnh Sản Xuất Dệt & Công Thức Nhuộm (A4 Laser)',
    description: 'Bản giao ca xưởng dệt và lệnh nhuộm hoàn tất',
    artifactType: 'document',
    documentType: 'production_order',
    targetPrinterProfile: 'laser',
    paperFormat: 'A4',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 297,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 10,
        marginRightMm: 10,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 10,
      },
      blocks: [
        {
          id: 'b-title',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'LỆNH SẢN XUẤT DỆT & HOÀN TẤT',
          fontSizePt: 16,
          fontWeight: 'bold',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
