// Shipment delivery print templates (A5 dot-matrix + A4 laser).
import type { PrintTemplateEntity } from './types';

export const SHIPMENT_TEMPLATES: PrintTemplateEntity[] = [
  {
    id: 'tpl-shipment-a5-dot-matrix',
    code: 'XK_DOT_MATRIX_A5',
    name: 'Phiếu Xuất Kho Giao Hàng (In Kim 3 Liên)',
    description:
      'Mẫu in chuyên dụng cho máy in kim Epson LQ-310 trên giấy đục lỗ liên tục A5',
    artifactType: 'document',
    documentType: 'shipment_delivery',
    targetPrinterProfile: 'dot_matrix',
    paperFormat: 'A5',
    orientation: 'landscape',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 200,
        heightMm: 148,
        marginTopMm: 4,
        marginBottomMm: 4,
        marginLeftMm: 3,
        marginRightMm: 3,
      },
      styles: {
        fontFamily: 'Courier_Mono',
        baseFontSizePt: 9,
        showTractorHoles: true,
      },
      blocks: [
        {
          id: 'b-header',
          order: 1,
          enabled: true,
          type: 'text',
          content: 'CÔNG TY TNHH DỆT MAY VĨNH PHÁT',
          fontSizePt: 11,
          fontWeight: 'bold',
          align: 'left',
        },
        {
          id: 'b-title',
          order: 2,
          enabled: true,
          type: 'text',
          content: 'PHIẾU XUẤT KHO KIÊM BIÊN BẢN BÀN GIAO',
          fontSizePt: 13,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-meta',
          order: 3,
          enabled: true,
          type: 'text',
          content:
            'Khách hàng: {{customer.name}} | Số phiếu: {{shipment.code}}',
          fontSizePt: 9,
          fontWeight: 'normal',
          align: 'left',
        },
        {
          id: 'b-table',
          order: 4,
          enabled: true,
          type: 'table',
          collectionBinding: 'shipment.items',
          rowHeightMm: 6,
          borderStyle: 'dashed',
          showTotalRow: true,
          columns: [
            {
              key: 'stt',
              label: 'STT',
              widthPercent: 8,
              align: 'center',
              fieldBinding: 'index',
            },
            {
              key: 'roll_number',
              label: 'Mã Cây',
              widthPercent: 15,
              align: 'center',
              fieldBinding: 'roll_number',
            },
            {
              key: 'fabric_type',
              label: 'Tên Hàng / Quy Cách',
              widthPercent: 40,
              align: 'left',
              fieldBinding: 'fabric_type',
            },
            {
              key: 'color_name',
              label: 'Màu Sắc',
              widthPercent: 20,
              align: 'left',
              fieldBinding: 'color_name',
            },
            {
              key: 'quantity',
              label: 'Số Mét',
              widthPercent: 17,
              align: 'right',
              fieldBinding: 'quantity',
              formatter: 'length_m',
            },
          ],
        },
        {
          id: 'b-signatures',
          order: 5,
          enabled: true,
          type: 'signature',
          slots: [
            { title: 'Người Lập Phiếu', subtitle: '(Ký, ghi rõ họ tên)' },
            { title: 'Thủ Kho Xuất', subtitle: '(Ký, đóng dấu)' },
            { title: 'Người Nhận Hàng', subtitle: '(Ký, ghi rõ họ tên)' },
          ],
        },
        {
          id: 'b-footer',
          order: 6,
          enabled: true,
          type: 'text',
          content:
            'Vui lòng kiểm tra kỹ số lượng và chất lượng trước khi rời kho.',
          fontSizePt: 8,
          fontWeight: 'normal',
          align: 'center',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-shipment-a4-laser',
    code: 'XK_LASER_A4',
    name: 'Phiếu Xuất Kho A4 (Laser / PDF Văn Phòng)',
    description:
      'Mẫu in khổ A4 đứng tiêu chuẩn kèm Logo thương hiệu và Mã QR bảo mật',
    artifactType: 'document',
    documentType: 'shipment_delivery',
    targetPrinterProfile: 'laser',
    paperFormat: 'A4',
    orientation: 'portrait',
    revision: 1,
    status: 'active',
    isSystem: true,
    layout: {
      schemaVersion: 1,
      coordinateSystem: 'mm',
      page: {
        widthMm: 210,
        heightMm: 297,
        marginTopMm: 10,
        marginBottomMm: 10,
        marginLeftMm: 10,
        marginRightMm: 10,
      },
      styles: {
        fontFamily: 'Inter',
        baseFontSizePt: 10,
        showTractorHoles: false,
      },
      blocks: [
        {
          id: 'b-header-logo',
          order: 1,
          enabled: true,
          type: 'image',
          fallbackUrl: '/favicon.svg',
          fit: 'contain',
        },
        {
          id: 'b-header',
          order: 2,
          enabled: true,
          type: 'text',
          content: 'CÔNG TY TNHH DỆT MAY VĨNH PHÁT',
          fontSizePt: 14,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-title',
          order: 3,
          enabled: true,
          type: 'text',
          content: 'PHIẾU XUẤT KHO GIAO HÀNG',
          fontSizePt: 16,
          fontWeight: 'bold',
          align: 'center',
        },
        {
          id: 'b-table',
          order: 4,
          enabled: true,
          type: 'table',
          collectionBinding: 'shipment.items',
          rowHeightMm: 8,
          borderStyle: 'solid',
          showTotalRow: true,
          columns: [
            {
              key: 'stt',
              label: 'STT',
              widthPercent: 8,
              align: 'center',
              fieldBinding: 'index',
            },
            {
              key: 'roll_number',
              label: 'Mã Cây',
              widthPercent: 17,
              align: 'center',
              fieldBinding: 'roll_number',
            },
            {
              key: 'fabric_type',
              label: 'Loại Vải',
              widthPercent: 40,
              align: 'left',
              fieldBinding: 'fabric_type',
            },
            {
              key: 'color_name',
              label: 'Màu Sắc',
              widthPercent: 20,
              align: 'left',
              fieldBinding: 'color_name',
            },
            {
              key: 'quantity',
              label: 'Số Mét (m)',
              widthPercent: 15,
              align: 'right',
              fieldBinding: 'quantity',
              formatter: 'length_m',
            },
          ],
        },
        {
          id: 'b-qr',
          order: 5,
          enabled: true,
          type: 'qr',
          valueBinding: 'shipment.code',
          sizeMm: 25,
        },
        {
          id: 'b-signatures',
          order: 6,
          enabled: true,
          type: 'signature',
          slots: [
            { title: 'Người Lập Phiếu' },
            { title: 'Thủ Kho Xuất' },
            { title: 'Lái Xe / Giao Hàng' },
            { title: 'Khách Hàng Ký Nhận' },
          ],
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
