import { Controller } from 'react-hook-form';
import type { UseFormRegister, Control, FieldErrors } from 'react-hook-form';

import { Combobox } from '@/shared/components/Combobox';
import type { RawFabricFormValues } from '@/schema/raw-fabric.schema';
import { RAW_FABRIC_MESSAGES as MSG } from '@/features/raw-fabric/raw-fabric.constants';
import { LengthInput, WeightInput } from '@/shared/value';

type RawFabricFormStep1GeneralProps = {
  register: UseFormRegister<RawFabricFormValues>;
  control: Control<RawFabricFormValues>;
  errors: FieldErrors<RawFabricFormValues>;
  isLotAutoGenerated: boolean;
  colorComboboxOptions: { value: string; label: string; code?: string }[];
};

export function RawFabricFormStep1General({
  register,
  control,
  errors,
  isLotAutoGenerated,
  colorComboboxOptions,
}: RawFabricFormStep1GeneralProps) {
  return (
    <div className="form-grid">
      <div className="form-field">
        <label htmlFor="lot_number">{MSG.LBL_LOT_NUMBER}</label>
        <input
          id="lot_number"
          className="field-input disabled:bg-surface-subtle disabled:cursor-not-allowed"
          type="text"
          placeholder="VD: LOT-2026-001"
          {...register('lot_number')}
          disabled={isLotAutoGenerated}
        />
        <span className="field-hint">
          {isLotAutoGenerated ? MSG.LBL_LOT_AUTO_HINT : MSG.LBL_LOT_MANUAL_HINT}
        </span>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="roll_number">
            {MSG.LBL_ROLL_NUMBER} <span className="field-required">*</span>
          </label>
          <input
            id="roll_number"
            className={`field-input${errors.roll_number ? ' border-danger' : ''}`}
            type="text"
            placeholder="VD: RM-2024-001"
            {...register('roll_number')}
          />
          {errors.roll_number && (
            <span className="field-error">{errors.roll_number.message}</span>
          )}
        </div>

        <div className="form-field">
          <label htmlFor="fabric_type">
            {MSG.LBL_FABRIC_TYPE} <span className="field-required">*</span>
          </label>
          <input
            id="fabric_type"
            className={`field-input${errors.fabric_type ? ' border-danger' : ''}`}
            type="text"
            placeholder="VD: Dệt thoi 60/40 TC"
            {...register('fabric_type')}
          />
          {errors.fabric_type && (
            <span className="field-error">{errors.fabric_type.message}</span>
          )}
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="color_name">{MSG.LBL_COLOR_NAME}</label>
          <Controller
            name="color_name"
            control={control}
            render={({ field }) => (
              <Combobox
                options={colorComboboxOptions}
                value={field.value ?? ''}
                onChange={field.onChange}
                placeholder={MSG.PLACEHOLDER_COLOR}
              />
            )}
          />
        </div>

        <div className="form-field">
          <label htmlFor="color_code">{MSG.LBL_COLOR_CODE}</label>
          <input
            id="color_code"
            className="field-input"
            type="text"
            placeholder="VD: TC-01"
            {...register('color_code')}
          />
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <Controller
          name="width_cm"
          control={control}
          render={({ field }) => (
            <LengthInput
              id="width_cm"
              className={`field-input${errors.width_cm ? ' border-danger' : ''}`}
              step="0.01"
              min="0"
              placeholder="VD: 150"
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
            />
          )}
        />

        <Controller
          name="length_m"
          control={control}
          render={({ field }) => (
            <LengthInput
              id="length_m"
              className={`field-input${errors.length_m ? ' border-danger' : ''}`}
              step="0.001"
              min="0"
              placeholder="VD: 50"
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
            />
          )}
        />
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <Controller
          name="weight_kg"
          control={control}
          render={({ field }) => (
            <WeightInput
              id="weight_kg"
              className={`field-input${errors.weight_kg ? ' border-danger' : ''}`}
              step="0.001"
              min="0"
              placeholder="VD: 25.5"
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
            />
          )}
        />

        <div className="form-field">
          <label htmlFor="production_date">{MSG.LBL_PRODUCTION_DATE}</label>
          <input
            id="production_date"
            className="field-input"
            type="date"
            {...register('production_date')}
          />
        </div>
      </div>
    </div>
  );
}
