import {
  useFormContext,
  type UseFormRegister,
  type FieldErrors,
} from 'react-hook-form';
import { Controller } from 'react-hook-form';

import type { BulkInputFormValues } from '@/schema/raw-fabric.schema';
import { NumericInput, QuantityInput } from '@/shared/value';

type RawFabricBulkFormStep1ConfigProps = {
  register: UseFormRegister<BulkInputFormValues>;
  errors: FieldErrors<BulkInputFormValues>;
  isPrefixAutoGenerated: boolean;
};

export function RawFabricBulkFormStep1Config({
  register,
  errors,
  isPrefixAutoGenerated,
}: RawFabricBulkFormStep1ConfigProps) {
  const { control } = useFormContext();

  return (
    <fieldset className="bulk-section">
      <legend>Cấu hình Mã Cuộn & Nhảy số</legend>
      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="bulk_roll_prefix">
            Tiền tố mã cuộn <span className="field-required">*</span>
          </label>
          <input
            id="bulk_roll_prefix"
            className={`field-input ${errors.roll_prefix ? 'border-danger' : ''} ${isPrefixAutoGenerated ? 'bg-[var(--surface-subtle)] cursor-not-allowed' : ''}`}
            type="text"
            placeholder="VD: RM-"
            {...register('roll_prefix')}
            disabled={isPrefixAutoGenerated}
          />
          {isPrefixAutoGenerated ? (
            <span className="field-hint">Tự động sinh theo Lot number.</span>
          ) : errors.roll_prefix ? (
            <span className="field-error">{errors.roll_prefix.message}</span>
          ) : null}
        </div>

        <Controller
          name="start_number"
          control={control}
          render={({ field }) => (
            <NumericInput
              id="bulk_start_number"
              className={`field-input${errors.start_number ? ' border-danger' : ''}`}
              min="1"
              step="1"
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
            />
          )}
        />

        <Controller
          name="expected_rolls"
          control={control}
          render={({ field }) => (
            <QuantityInput
              id="bulk_expected_rolls"
              className="field-input"
              min="1"
              max="500"
              step="1"
              placeholder="VD: 20"
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
            />
          )}
        />
      </div>
    </fieldset>
  );
}
