import type { UseFormRegister, FieldErrors } from 'react-hook-form';

import type { BulkInputFormValues } from '@/schema/raw-fabric.schema';

type RawFabricBulkFormStep1ConfigProps = {
  register: UseFormRegister<BulkInputFormValues>;
  errors: FieldErrors<BulkInputFormValues>;
  isPrefixAutoGenerated: boolean;
};

export function RawFabricBulkFormStep1Config({
  register,
  errors,
  isPrefixAutoGenerated,
}: RawFabricBulkFormStep1ConfigProps) {
  return (
    <fieldset className="bulk-section">
      <legend>Cấu hình Mã Cuộn & Nhảy số</legend>
      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="bulk_roll_prefix">
            Tiền tố mã cuộn <span className="field-required">*</span>
          </label>
          <input
            id="bulk_roll_prefix"
            className={`field-input ${errors.roll_prefix ? 'border-danger' : ''} ${isPrefixAutoGenerated ? 'bg-[var(--surface-subtle)] cursor-not-allowed' : ''}`}
            type="text"
            placeholder="VD: RM-"
            {...register('roll_prefix')}
            disabled={isPrefixAutoGenerated}
          />
          {isPrefixAutoGenerated ? (
            <span className="field-hint">Tự động sinh theo Lot number.</span>
          ) : errors.roll_prefix ? (
            <span className="field-error">{errors.roll_prefix.message}</span>
          ) : null}
        </div>

        <div className="form-field">
          <label htmlFor="bulk_start_number">Số bắt đầu</label>
          <input
            id="bulk_start_number"
            className={`field-input${errors.start_number ? ' border-danger' : ''}`}
            type="number"
            min="1"
            step="1"
            {...register('start_number')}
          />
          {errors.start_number && (
            <span className="field-error">{errors.start_number.message}</span>
          )}
        </div>

        <div className="form-field">
          <label htmlFor="bulk_expected_rolls">Số cuộn dự kiến</label>
          <input
            id="bulk_expected_rolls"
            className="field-input"
            type="number"
            min="1"
            max="500"
            step="1"
            placeholder="VD: 20"
            {...register('expected_rolls')}
          />
          <span className="field-hint text-[0.78rem] text-muted-foreground block mt-1">
            Hệ thống tự tạo sẵn lưới trống theo số lượng này.
          </span>
        </div>
      </div>
    </fieldset>
  );
}
