import { Controller } from 'react-hook-form';
import type {
  UseFormRegister,
  Control,
  FieldErrors,
  UseFormWatch,
} from 'react-hook-form';

import { Combobox } from '@/shared/components/Combobox';
import type { BulkInputFormValues } from '@/schema/raw-fabric.schema';
import { RAW_FABRIC_MESSAGES as MSG } from '@/features/raw-fabric/raw-fabric.constants';
import { LengthInput } from '@/shared/value';

type RawFabricBulkFormStep1GeneralProps = {
  register: UseFormRegister<BulkInputFormValues>;
  control: Control<BulkInputFormValues>;
  errors: FieldErrors<BulkInputFormValues>;
  watch: UseFormWatch<BulkInputFormValues>;
  fabricCatalogOptions: { value: string; label: string; code?: string }[];
  colorComboboxOptions: { value: string; label: string; code?: string }[];
  qualityOptions: { value: string; label: string }[];
  statusOptions: { value: string; label: string }[];
  workOrderOptions: { value: string; label: string }[];
  weavingPartnerOptions: { value: string; label: string }[];
  yarnReceiptOptions: { value: string; label: string }[];
  handleWoWpYrChange: (
    name: 'work_order_id' | 'weaving_partner_id' | 'yarn_receipt_id',
    val: string,
  ) => void;
};

export function RawFabricBulkFormStep1General({
  register,
  control,
  errors,
  watch,
  fabricCatalogOptions,
  colorComboboxOptions,
  qualityOptions,
  statusOptions,
  workOrderOptions,
  weavingPartnerOptions,
  yarnReceiptOptions,
  handleWoWpYrChange,
}: RawFabricBulkFormStep1GeneralProps) {
  const isLotAutoGenerated = !!(
    watch('work_order_id') &&
    watch('weaving_partner_id') &&
    watch('yarn_receipt_id') &&
    watch('production_date')
  );

  return (
    <fieldset className="bulk-section">
      <legend>Thông tin đồng loạt</legend>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label>
            {MSG.LBL_FABRIC_TYPE} <span className="field-required">*</span>
          </label>
          <Controller
            control={control}
            name="fabric_type"
            render={({ field }) => (
              <Combobox
                options={fabricCatalogOptions}
                value={field.value || ''}
                onChange={field.onChange}
                onBlur={field.onBlur}
                placeholder="Chọn hoặc nhập loại vải..."
                hasError={!!errors.fabric_type}
                allowInput
              />
            )}
          />
          {errors.fabric_type && (
            <span className="field-error">{errors.fabric_type.message}</span>
          )}
        </div>

        <div className="form-field">
          <label htmlFor="bulk_warehouse_location">
            {MSG.LBL_WAREHOUSE_LOCATION}
          </label>
          <input
            id="bulk_warehouse_location"
            className="field-input"
            type="text"
            placeholder="VD: A1-R3-S2"
            {...register('warehouse_location')}
          />
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="bulk_color_name">{MSG.LBL_COLOR_NAME}</label>
          <Controller
            name="color_name"
            control={control}
            render={({ field }) => (
              <Combobox
                options={colorComboboxOptions}
                value={field.value ?? ''}
                onChange={field.onChange}
                placeholder={MSG.PLACEHOLDER_COLOR}
              />
            )}
          />
        </div>
        <div className="form-field">
          <label htmlFor="bulk_color_code">{MSG.LBL_COLOR_CODE}</label>
          <input
            id="bulk_color_code"
            className="field-input"
            type="text"
            placeholder="VD: TC-01"
            {...register('color_code')}
          />
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <Controller
          name="width_cm"
          control={control}
          render={({ field }) => (
            <LengthInput
              id="bulk_width_cm"
              className={`field-input${errors.width_cm ? ' border-danger' : ''}`}
              step="0.01"
              min="0"
              placeholder="VD: 150"
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
            />
          )}
        />

        <div className="form-field">
          <label htmlFor="bulk_quality_grade">Chất lượng mặc định</label>
          <Controller
            name="quality_grade"
            control={control}
            render={({ field }) => (
              <Combobox
                options={qualityOptions}
                value={field.value}
                onChange={field.onChange}
              />
            )}
          />
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="bulk_status">{MSG.LBL_STATUS}</label>
          <Controller
            name="status"
            control={control}
            render={({ field }) => (
              <Combobox
                options={statusOptions}
                value={field.value}
                onChange={field.onChange}
              />
            )}
          />
        </div>

        <div className="form-field">
          <label htmlFor="bulk_production_date">
            {MSG.LBL_PRODUCTION_DATE}
          </label>
          <input
            id="bulk_production_date"
            className="field-input"
            type="date"
            {...register('production_date')}
          />
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="bulk_work_order_id">{MSG.LBL_WORK_ORDER}</label>
          <Controller
            name="work_order_id"
            control={control}
            render={({ field }) => (
              <Combobox
                options={workOrderOptions}
                value={field.value}
                onChange={(val) => handleWoWpYrChange('work_order_id', val)}
                placeholder={MSG.VAL_NO_WO}
              />
            )}
          />
        </div>

        <div className="form-field">
          <label htmlFor="bulk_weaving_partner_id">
            {MSG.LBL_WEAVING_PARTNER}
          </label>
          <Controller
            name="weaving_partner_id"
            control={control}
            render={({ field }) => (
              <Combobox
                options={weavingPartnerOptions}
                value={field.value}
                onChange={(val) =>
                  handleWoWpYrChange('weaving_partner_id', val)
                }
                placeholder={MSG.VAL_CHOOSE_WEAVER}
              />
            )}
          />
        </div>
      </div>

      <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
        <div className="form-field">
          <label htmlFor="bulk_yarn_receipt_id">{MSG.LBL_YARN_RECEIPT}</label>
          <Controller
            name="yarn_receipt_id"
            control={control}
            render={({ field }) => (
              <Combobox
                options={yarnReceiptOptions}
                value={field.value}
                onChange={(val) => handleWoWpYrChange('yarn_receipt_id', val)}
                placeholder={MSG.VAL_CHOOSE_YARN}
              />
            )}
          />
        </div>

        <div className="form-field">
          <label htmlFor="bulk_lot_number">{MSG.LBL_LOT_NUMBER}</label>
          <input
            id="bulk_lot_number"
            className="field-input disabled:bg-surface-subtle disabled:cursor-not-allowed"
            type="text"
            placeholder="VD: LOT-2026-001"
            {...register('lot_number')}
            disabled={isLotAutoGenerated}
          />
          <span className="field-hint">
            {isLotAutoGenerated
              ? MSG.LBL_LOT_AUTO_HINT
              : MSG.LBL_LOT_MANUAL_HINT}
          </span>
        </div>
      </div>
    </fieldset>
  );
}
