import type { FeaturePlugin } from '@/shared/lib/FeatureRegistry'
import { FeatureRegistry } from '@/shared/lib/FeatureRegistry'

/**
 * Plugin Registry — Đăng ký tất cả features vào hệ thống.
 *
 * Để bật/tắt một feature, chỉ cần comment hoặc xóa dòng tương ứng.
 * Không cần chỉnh sửa routes.tsx hay Sidebar.
 *
 * Thứ tự plugins = thứ tự hiển thị trên menu (dùng field `order`).
 */

const plugins: FeaturePlugin[] = [
  // ── SALES ──
  {
    key: 'quotations',
    route: 'quotations',
    label: 'Báo giá',
    shortLabel: 'Báo giá',
    description: 'Tạo và quản lý báo giá, VAT, chiết khấu, chuyển thành đơn hàng.',
    icon: 'file-text',
    primaryMobile: true,
    requiredRoles: ['admin', 'manager', 'sale'],
    group: 'sales',
    order: 10,
    component: () => import('@/features/quotations').then((m) => ({ default: m.QuotationsPage })),
    printRoutes: [
      {
        path: 'print/quotation/:id',
        component: () => import('@/features/quotations').then((m) => ({ default: m.QuotationPrint })),
      },
    ],
  },
  {
    key: 'orders',
    route: 'orders',
    label: 'Đơn hàng',
    shortLabel: 'Orders',
    description: 'Quản lý đơn hàng, chi tiết dòng hàng, giữ chỗ và ngày giao.',
    icon: 'shopping-cart',
    primaryMobile: true,
    group: 'sales',
    order: 20,
    component: () => import('@/features/orders').then((m) => ({ default: m.OrdersPage })),
  },
  {
    key: 'order-progress',
    route: 'order-progress',
    label: 'Tiến độ đơn hàng',
    shortLabel: 'Progress',
    description: 'Timeline và cập nhật tiến độ cho từng dòng hàng.',
    icon: 'trending-up',
    primaryMobile: true,
    group: 'sales',
    order: 25,
    component: () => import('@/features/order-progress').then((m) => ({ default: m.OrderProgressPage })),
  },
  {
    key: 'order-kanban',
    route: 'order-kanban',
    label: 'Kanban Đơn Hàng',
    shortLabel: 'Kanban',
    description: 'Quản lý đơn hàng theo trạng thái trực quan.',
    icon: 'kanban',
    requiredRoles: ['admin', 'manager', 'sale'],
    group: 'sales',
    order: 27,
    component: () => import('@/features/order-kanban').then((m) => ({ default: m.OrderKanbanPage })),
  },
  {
    key: 'customers',
    route: 'customers',
    label: 'Khách hàng',
    shortLabel: 'Customers',
    description: 'Quản lý khách hàng, liên hệ và công nợ.',
    icon: 'users',
    group: 'sales',
    order: 30,
    component: () => import('@/features/customers').then((m) => ({ default: m.CustomersPage })),
  },
  {
    key: 'shipments',
    route: 'shipments',
    label: 'Xuất kho',
    shortLabel: 'Ship',
    description: 'Tạo phiếu xuất từ đơn hàng và đồng bộ tồn kho.',
    icon: 'truck',
    primaryMobile: true,
    group: 'sales',
    order: 35,
    component: () => import('@/features/shipments').then((m) => ({ default: m.ShipmentsPage })),
  },

  // ── PRODUCTION ──
  {
    key: 'yarn-receipts',
    route: 'yarn-receipts',
    label: 'Nhập sợi',
    shortLabel: 'Yarn',
    description: 'Nhập nguyên liệu sợi và tạo phiếu nhập kho.',
    icon: 'package-plus',
    group: 'production',
    order: 40,
    component: () => import('@/features/yarn-receipts').then((m) => ({ default: m.YarnReceiptsPage })),
  },
  {
    key: 'bom',
    route: 'bom',
    label: 'Định mức (BOM)',
    shortLabel: 'BOM',
    description: 'Cấu hình định mức nguyên vật liệu sợi cho từng mã vải mộc.',
    icon: 'layers',
    requiredRoles: ['admin', 'manager'],
    routeGuard: 'manager',
    group: 'production',
    order: 45,
    component: () => import('@/features/bom').then((m) => ({ default: m.BomPage })),
  },
  {
    key: 'work-orders',
    route: 'work-orders',
    label: 'Lệnh sản xuất',
    shortLabel: 'Lệnh SX',
    description: 'Chỉ đạo sản xuất và tự động phân bổ nguồn lực sợi.',
    icon: 'clipboard-list',
    group: 'production',
    order: 50,
    component: () => import('@/features/work-orders').then((m) => ({ default: m.WorkOrdersPage })),
  },
  {
    key: 'raw-fabric',
    route: 'raw-fabric',
    label: 'Nhập vải mộc',
    shortLabel: 'Raw',
    description: 'Theo dõi lô vải mộc và mapping với nguyên liệu, nhà dệt.',
    icon: 'scroll',
    group: 'production',
    order: 55,
    component: () => import('@/features/raw-fabric').then((m) => ({ default: m.RawFabricPage })),
  },
  {
    key: 'weaving-invoices',
    route: 'weaving-invoices',
    label: 'Phiếu gia công',
    shortLabel: 'Gia công',
    description: 'Quản lý phiếu gia công dệt theo lô — tính công nợ nhà dệt tự động.',
    icon: 'receipt',
    group: 'production',
    order: 57,
    component: () => import('@/features/weaving-invoices/WeavingInvoicesPage').then((m) => ({ default: m.WeavingInvoicesPage })),
  },
  {
    key: 'finished-fabric',
    route: 'finished-fabric',
    label: 'Vải thành phẩm',
    shortLabel: 'Finished',
    description: 'Nhập thành phẩm và cập nhật sản lượng đã xử lý.',
    icon: 'check-square',
    group: 'production',
    order: 60,
    component: () => import('@/features/finished-fabric').then((m) => ({ default: m.FinishedFabricPage })),
  },

  // ── MASTER DATA ──
  {
    key: 'suppliers',
    route: 'suppliers',
    label: 'Nhà cung cấp',
    shortLabel: 'Suppliers',
    description: 'Quản lý nhà cung cấp sợi, dệt, nhuộm và logistics.',
    icon: 'building',
    group: 'master-data',
    order: 70,
    component: () => import('@/features/suppliers').then((m) => ({ default: m.SuppliersPage })),
  },
  {
    key: 'yarn-catalog',
    route: 'yarn-catalog',
    label: 'Danh mục sợi',
    shortLabel: 'Danh mục',
    description: 'Quản lý danh mục loại sợi — nền cho luồng nhập sợi.',
    icon: 'database',
    group: 'master-data',
    order: 75,
    component: () => import('@/features/yarn-catalog').then((m) => ({ default: m.YarnCatalogPage })),
  },
  {
    key: 'fabric-catalog',
    route: 'fabric-catalog',
    label: 'Danh mục vải',
    shortLabel: 'Vải',
    description: 'Quản lý danh mục loại vải — dùng chung cho vải mộc và thành phẩm.',
    icon: 'layout-grid',
    group: 'master-data',
    order: 76,
    component: () => import('@/features/fabric-catalog').then((m) => ({ default: m.FabricCatalogPage })),
  },
  {
    key: 'inventory',
    route: 'inventory',
    label: 'Tồn kho',
    shortLabel: 'Stock',
    description: 'Tồn khả dụng, tồn giữ chỗ, cảnh báo tồn thấp và truy vết.',
    icon: 'warehouse',
    primaryMobile: true,
    group: 'master-data',
    order: 80,
    component: () => import('@/features/inventory').then((m) => ({ default: m.InventoryPage })),
  },

  // ── SYSTEM ──
  {
    key: 'payments',
    route: 'payments',
    label: 'Thu Chi',
    shortLabel: 'Thu Chi',
    description: 'Quản lý thu chi, phiếu thu, phiếu chi, dòng tiền và công nợ.',
    icon: 'wallet',
    group: 'system',
    order: 90,
    component: () => import('@/features/payments').then((m) => ({ default: m.PaymentsPage })),
  },
  {
    key: 'reports',
    route: 'reports',
    label: 'Báo cáo',
    shortLabel: 'Reports',
    description: 'Dashboard KPI, đơn hàng trễ, doanh thu và sức khoẻ kho.',
    icon: 'bar-chart-3',
    requiredRoles: ['admin', 'manager'],
    routeGuard: 'manager',
    group: 'system',
    order: 95,
    component: () => import('@/features/reports').then((m) => ({ default: m.ReportsPage })),
  },
  {
    key: 'shipping-rates',
    route: 'shipping-rates',
    label: 'Giá cước vận chuyển',
    shortLabel: 'Cước VC',
    description: 'Quản lý bảng giá cước vận chuyển theo khu vực.',
    icon: 'map-pin',
    requiredRoles: ['admin'],
    routeGuard: 'admin',
    group: 'system',
    order: 96,
    component: () => import('@/features/shipping-rates').then((m) => ({ default: m.ShippingRatesPage })),
  },
  {
    key: 'settings',
    route: 'settings',
    label: 'Cài đặt',
    shortLabel: 'Settings',
    description: 'Cấu hình môi trường, phân quyền, đồng bộ và triển khai.',
    icon: 'settings',
    requiredRoles: ['admin'],
    routeGuard: 'admin',
    group: 'system',
    order: 99,
    component: () => import('@/features/settings').then((m) => ({ default: m.SettingsPage })),
  },
]

// Register all plugins
FeatureRegistry.registerAll(plugins)

export { FeatureRegistry }
