export const LOOM_MESSAGES = {
  PAGE_TITLE: 'Máy dệt (MES)',
  PAGE_SUBTITLE:
    'Quản lý hiệu suất, trạng thái thời gian thực và thông số kỹ thuật.',
  TAB_LOOMS: 'Máy dệt (Looms)',
  TAB_SPECS: 'Cấu hình máy (Machine Specs)',
  BTN_CREATE: 'Thêm máy dệt',
  KPI_TOTAL: 'Tổng số máy',
  KPI_RUNNING: 'Đang chạy (Running)',
  KPI_IDLE: 'Chờ việc (Idle)',
  KPI_BREAKDOWN: 'Lỗi/Hỏng (Breakdown)',
  FILTER_SEARCH_LABEL: 'Tìm kiếm',
  FILTER_SEARCH_PLACEHOLDER: 'Mã, tên máy dệt...',
  FILTER_STATUS_LABEL: 'Trạng thái',
  FILTER_TYPE_LABEL: 'Loại máy',
  EMPTY_STATE_FILTER_TITLE: 'Không tìm thấy máy dệt phù hợp',
  EMPTY_STATE_TITLE: 'Chưa có máy dệt nào',
  PAGINATION_LABEL: 'máy dệt',
  CONFIRM_DELETE_MSG: (name: string) =>
    `Xóa máy dệt "${name}"? Hành động này không thể hoàn tác.`,
  SPEC_PAGE_TITLE: 'Cấu hình máy dệt',
  SPEC_PAGE_SUBTITLE:
    'Quản lý cấu hình Master Data kỹ thuật cho quá trình sản xuất',
  BTN_SPEC_CREATE: 'Thêm cấu hình',
  BTN_SPEC_EDIT: 'Sửa',
  BTN_SPEC_EDIT_TOOLTIP: 'Sửa cấu hình',
  BTN_SPEC_RESTORE: 'Khôi phục cấu hình',
  BTN_SPEC_HIDE: 'Ẩn cấu hình',
  CONFIRM_SPEC_RESTORE_TITLE: 'Khôi phục cấu hình',
  CONFIRM_SPEC_HIDE_TITLE: 'Ẩn cấu hình',
  CONFIRM_SPEC_RESTORE_MSG:
    'Bạn có chắc chắn muốn khôi phục cấu hình máy dệt này?',
  CONFIRM_SPEC_HIDE_MSG:
    'Cấu hình này sẽ bị ẩn khỏi các danh sách chọn. Bạn có chắc chắn?',
  CONFIRM_SPEC_RESTORE_BTN: 'Khôi phục',
  CONFIRM_SPEC_HIDE_BTN: 'Ẩn',
  BTN_CANCEL: 'Hủy',
  COL_SPEC_CODE: 'Mã cấu hình',
  COL_SPEC_TYPE: 'Loại máy',
  COL_SPEC_SIZE: 'Kích thước & Kim',
  COL_SPEC_FEEDER: 'Feeder',
  COL_SPEC_MANUFACTURER: 'Hãng / Nhóm',
  COL_SPEC_STATUS: 'Trạng thái',
  ERR_SPEC_TOGGLE: 'Không thể thay đổi trạng thái. ',
  ERR_UNKNOWN_TYPE: 'Không xác định',
  STATUS_ACTIVE: 'Đang sử dụng',
  STATUS_INACTIVE: 'Đã ẩn',
  ERR_TITLE: 'Lỗi',
  ERR_DELETE_LOOM: 'Không thể xóa máy dệt. ',
  BTN_CLOSE: 'Đóng',

  // Form strings
  FORM_TITLE_EDIT: (name: string) => `Sửa: ${name}`,
  FORM_TITLE_CREATE: 'Thêm máy dệt',
  BTN_SUBMIT_EDIT: 'Cập nhật',
  BTN_SUBMIT_CREATE: 'Thêm máy dệt',
  ERR_FORM_PREFIX: 'Lỗi: ',
  WARN_TECH_LOCKED_TITLE: 'Máy đang HOẠT ĐỘNG!',
  WARN_TECH_LOCKED_DESC:
    'Không thể sửa đổi thông số kỹ thuật (Loại máy, số kim, v.v.) để tránh sai lệch dữ liệu sản xuất. Hãy chuyển trạng thái sang "Bảo trì" hoặc "Ngừng dùng" nếu muốn chỉnh sửa.',
};
