import { PAYMENT_METHOD_LABELS } from '@/schema/payment.schema';

/** Centralized labels for the Deposit (advance payment) form. */
export const DEPOSIT_FORM_LABELS = {
  title: 'Nạp tiền khách hàng',
  receiptNumber: 'Số phiếu thu',
  autoGenerated: 'Tự động',
  dateLabel: 'Ngày nạp',
  amountLabel: 'Số tiền nạp (đ)',
  amountPlaceholder: 'VD: 5.000.000',
  methodLabel: 'Hình thức',
  referenceLabel: 'Số chứng từ / ghi chú nạp tiền',
  referencePlaceholder: 'Chuyển khoản cọc trước, ghi chú...',
  cancelButton: 'Hủy',
  submitButton: 'Xác nhận nạp',
  submittingButton: 'Đang lưu...',
  errorPrefix: 'Lỗi:',
  balanceColumnHeader: 'Số dư (đ)',
} as const;

/**
 * Payment method options for deposit form.
 * Excludes 'customer_balance' since deposits are real money inflows.
 */
export const DEPOSIT_PAYMENT_METHOD_OPTIONS = Object.entries(
  PAYMENT_METHOD_LABELS,
)
  .filter(([key]) => key !== 'customer_balance')
  .map(([value, label]) => ({ value, label }));

/** Centralized labels for Customer Groups CRM CRUD. */
export const CUSTOMER_GROUP_LABELS = {
  title: 'Danh mục nhóm khách hàng',
  createBtn: 'Thêm nhóm mới',
  editBtn: 'Chỉnh sửa',
  deleteBtn: 'Xóa',
  codeLabel: 'Mã nhóm (viết liền, không dấu, duy nhất)',
  codePlaceholder: 'VD: VIP, DEALER_SOUTH, OEM_KEY',
  nameLabel: 'Tên nhóm',
  namePlaceholder: 'VD: Khách hàng VIP, Đại lý miền Nam',
  descriptionLabel: 'Mô tả nhóm',
  descriptionPlaceholder: 'VD: Khách hàng sỉ đạt hạn mức lớn...',
  statusLabel: 'Trạng thái hoạt động',
  statusActive: 'Hoạt động',
  statusInactive: 'Ngưng hoạt động',
  saveBtn: 'Lưu nhóm',
  cancelBtn: 'Hủy',
  saving: 'Đang lưu...',
  confirmDeleteTitle: 'Xác nhận xóa nhóm khách hàng',
  confirmDeleteMessage:
    'Bạn có chắc chắn muốn xóa nhóm này? Thao tác này sẽ bị chặn nếu nhóm đang có thành viên hoặc bảng giá liên kết.',
  deleteSuccess: 'Xóa nhóm khách hàng thành công!',
  saveSuccess: 'Lưu nhóm khách hàng thành công!',
  deleteErrorRestrict:
    'Không thể xóa nhóm khách hàng này vì đang có khách hàng hoặc bảng giá sử dụng. Vui lòng chuyển trạng thái sang ngưng hoạt động (inactive).',
  generalError: 'Đã xảy ra lỗi. Vui lòng thử lại.',
  codeRequired: 'Mã nhóm không được để trống',
  codeInvalid: 'Mã nhóm chỉ được chứa chữ cái viết hoa, số và dấu gạch dưới',
  nameRequired: 'Tên nhóm không được để trống',
  noGroups: 'Chưa có nhóm khách hàng nào được cấu hình.',
  searchPlaceholder: 'Tìm kiếm nhóm khách hàng...',
  codeExistsError: 'Mã nhóm đã tồn tại trên hệ thống!',
  confirmDeleteAction: 'Xác nhận xóa',
  cancelAction: 'Quay lại',
  updatePrefix: 'Cập nhật:',
} as const;

export const CUSTOMER_FORM_LABELS = {
  successUpdate: 'Cập nhật khách hàng thành công',
  successCreate: 'Tạo khách hàng mới thành công',
  errorPrefix: 'Lỗi:',
  codeLabel: 'Mã khách hàng',
  codePlaceholder: 'VD: KH-001',
  nameLabel: 'Tên khách hàng',
  namePlaceholder: 'VD: Công ty TNHH ABC',
  phoneLabel: 'Số điện thoại',
  phonePlaceholder: 'VD: 0901 234 567',
  emailLabel: 'Email',
  emailPlaceholder: 'VD: lienhe@congty.vn',
  addressLabel: 'Địa chỉ',
  addressPlaceholder: 'VD: 123 Đường Lê Lợi, Q.1, TP.HCM',
  taxCodeLabel: 'Mã số thuế',
  taxCodePlaceholder: 'VD: 0312345678',
  contactPersonLabel: 'Người liên hệ',
  contactPersonPlaceholder: 'VD: Nguyễn Văn A',
  sourceLabel: 'Nguồn khách hàng',
  statusLabel: 'Trạng thái',
  leadStatusLabel: 'Phễu CRM',
  salespersonLabel: 'Nhân viên phụ trách',
  unassigned: '(Chưa phân công)',
  notesLabel: 'Ghi chú',
  notesPlaceholder: 'Ghi chú thêm về khách hàng...',
  groupsLabel: 'Nhóm khách hàng (Phân hạng sỉ)',
  noGroups: 'Chưa có nhóm nào được định nghĩa trên hệ thống.',
  portalLabel: 'Tài khoản Customer Portal',
  portalPending: 'Tài khoản Portal sẽ khả dụng sau khi lưu khách hàng.',
  timelineLabel: 'Lịch sử tương tác (Leads)',
  cancelBtn: 'Hủy',
  updateBtn: 'Cập nhật',
  createBtn: 'Tạo mới',
  statusActive: 'Hoạt động',
  statusInactive: 'Ngừng hoạt động',
} as const;

export const CUSTOMERS_PAGE_LABELS = {
  tabCustomers: 'Khách hàng',
  tabGroups: 'Nhóm khách hàng',
  editPrefix: 'Sửa:',
  createTitle: 'Thêm khách hàng mới',
  createContractTitle: 'Tạo hợp đồng',
  chatSubtitle: 'Trò chuyện trực tiếp',
} as const;

export const CUSTOMER_TIMELINE_LABELS = {
  empty: 'Khách hàng chưa có lịch sử tương tác nào',
  other: 'Khác',
  rfqPrefix: 'Báo giá',
  samplePrefix: 'Xin mẫu',
  contactGeneral: 'Liên hệ chung',
  sourcePrefix: 'Khách hàng từ nguồn:',
  sourceDirect: 'Trực tiếp',
} as const;
