import dayjs from 'dayjs';

import { PAYMENT_METHOD_LABELS } from '@/schema/payment.schema';
import type { CustomersFilter } from '@/domain/crm/customers.types';

/** Tab keys hợp lệ cho danh sách khách hàng. */
export type CustomerTab = 'all' | 'mine' | 'new';

export const CUSTOMER_TABS = [
  'all',
  'mine',
  'new',
] as const satisfies readonly CustomerTab[];

/**
 * getTabPreset — Pure function trả về filter preset cho mỗi tab.
 *
 * Tách biệt hoàn toàn khỏi UI component, có thể test độc lập.
 * Kết quả được merge vào effectiveFilters: tabPreset < userFilters.
 *
 * @param tab        Tab key đang active.
 * @param employeeId Employee ID của user hiện tại (dùng cho tab 'mine').
 */
export function getTabPreset(
  tab: CustomerTab,
  employeeId: string | undefined,
): Partial<CustomersFilter> {
  switch (tab) {
    case 'mine':
      return employeeId ? { salesperson_id: employeeId } : {};
    case 'new':
      return { created_from: dayjs().startOf('week').toISOString() };
    default:
      return {};
  }
}

/** Centralized labels for the Deposit (advance payment) form. */
export const DEPOSIT_FORM_LABELS = {
  title: 'Nạp tiền khách hàng',
  receiptNumber: 'Số phiếu thu',
  autoGenerated: 'Tự động',
  dateLabel: 'Ngày nạp',
  amountLabel: 'Số tiền nạp (đ)',
  amountPlaceholder: 'VD: 5.000.000',
  methodLabel: 'Hình thức',
  referenceLabel: 'Số chứng từ / ghi chú nạp tiền',
  referencePlaceholder: 'Chuyển khoản cọc trước, ghi chú...',
  cancelButton: 'Hủy',
  submitButton: 'Xác nhận nạp',
  submittingButton: 'Đang lưu...',
  errorPrefix: 'Lỗi:',
  balanceColumnHeader: 'Số dư (đ)',
} as const;

/**
 * Payment method options for deposit form.
 * Excludes 'customer_balance' since deposits are real money inflows.
 */
export const DEPOSIT_PAYMENT_METHOD_OPTIONS = Object.entries(
  PAYMENT_METHOD_LABELS,
)
  .filter(([key]) => key !== 'customer_balance')
  .map(([value, label]) => ({ value, label }));

/** Centralized labels for Customer Groups CRM CRUD. */
export const CUSTOMER_GROUP_LABELS = {
  title: 'Danh mục nhóm khách hàng',
  createBtn: 'Thêm nhóm mới',
  editBtn: 'Chỉnh sửa',
  deleteBtn: 'Xóa',
  codeLabel: 'Mã nhóm (viết liền, không dấu, duy nhất)',
  codePlaceholder: 'VD: VIP, DEALER_SOUTH, OEM_KEY',
  nameLabel: 'Tên nhóm',
  namePlaceholder: 'VD: Khách hàng VIP, Đại lý miền Nam',
  descriptionLabel: 'Mô tả nhóm',
  descriptionPlaceholder: 'VD: Khách hàng sỉ đạt hạn mức lớn...',
  statusLabel: 'Trạng thái hoạt động',
  statusActive: 'Hoạt động',
  statusInactive: 'Ngưng hoạt động',
  saveBtn: 'Lưu nhóm',
  cancelBtn: 'Hủy',
  saving: 'Đang lưu...',
  confirmDeleteTitle: 'Xác nhận xóa nhóm khách hàng',
  confirmDeleteMessage:
    'Bạn có chắc chắn muốn xóa nhóm này? Thao tác này sẽ bị chặn nếu nhóm đang có thành viên hoặc bảng giá liên kết.',
  deleteSuccess: 'Xóa nhóm khách hàng thành công!',
  saveSuccess: 'Lưu nhóm khách hàng thành công!',
  deleteErrorRestrict:
    'Không thể xóa nhóm khách hàng này vì đang có khách hàng hoặc bảng giá sử dụng. Vui lòng chuyển trạng thái sang ngưng hoạt động (inactive).',
  generalError: 'Đã xảy ra lỗi. Vui lòng thử lại.',
  codeRequired: 'Mã nhóm không được để trống',
  codeInvalid: 'Mã nhóm chỉ được chứa chữ cái viết hoa, số và dấu gạch dưới',
  nameRequired: 'Tên nhóm không được để trống',
  noGroups: 'Chưa có nhóm khách hàng nào được cấu hình.',
  searchPlaceholder: 'Tìm kiếm nhóm khách hàng...',
  codeExistsError: 'Mã nhóm đã tồn tại trên hệ thống!',
  confirmDeleteAction: 'Xác nhận xóa',
  cancelAction: 'Quay lại',
  updatePrefix: 'Cập nhật:',
} as const;

export const CUSTOMER_FORM_LABELS = {
  successUpdate: 'Cập nhật khách hàng thành công',
  successCreate: 'Tạo khách hàng mới thành công',
  errorPrefix: 'Lỗi:',
  codeLabel: 'Mã khách hàng',
  codePlaceholder: 'VD: KH-001',
  nameLabel: 'Tên khách hàng',
  namePlaceholder: 'VD: Công ty TNHH ABC',
  phoneLabel: 'Số điện thoại',
  phonePlaceholder: 'VD: 0901 234 567',
  emailLabel: 'Email',
  emailPlaceholder: 'VD: lienhe@congty.vn',
  addressLabel: 'Địa chỉ',
  addressPlaceholder: 'VD: 123 Đường Lê Lợi, Q.1, TP.HCM',
  taxCodeLabel: 'Mã số thuế',
  taxCodePlaceholder: 'VD: 0312345678',
  contactPersonLabel: 'Người liên hệ',
  contactPersonPlaceholder: 'VD: Nguyễn Văn A',
  sourceLabel: 'Nguồn khách hàng',
  statusLabel: 'Trạng thái',
  leadStatusLabel: 'Phễu CRM',
  salespersonLabel: 'Nhân viên phụ trách',
  unassigned: '(Chưa phân công)',
  notesLabel: 'Ghi chú',
  notesPlaceholder: 'Ghi chú thêm về khách hàng...',
  groupsLabel: 'Nhóm khách hàng (Mô hình KD)',
  noGroups: 'Chưa có nhóm nào được định nghĩa trên hệ thống.',
  portalLabel: 'Tài khoản Customer Portal',
  portalPending: 'Tài khoản Portal sẽ khả dụng sau khi lưu khách hàng.',
  timelineLabel: 'Lịch sử tương tác (Leads)',
  cancelBtn: 'Hủy',
  updateBtn: 'Cập nhật',
  createBtn: 'Tạo mới',
  statusActive: 'Hoạt động',
  statusInactive: 'Ngừng hoạt động',
} as const;

export const CUSTOMERS_PAGE_LABELS = {
  tabCustomers: 'Khách hàng',
  tabGroups: 'Nhóm khách hàng',
  editPrefix: 'Sửa:',
  createTitle: 'Thêm khách hàng mới',
  createContractTitle: 'Tạo hợp đồng',
  chatSubtitle: 'Trò chuyện trực tiếp',
  guideTitle: 'Mẹo phân nhóm theo Mô hình kinh doanh',
  guideIntro:
    'Phân loại nhóm giúp hệ thống tối ưu bảng giá và chính sách công nợ tự động:',
  guideTypeDealer: 'Đại lý / Chợ đầu mối',
  guideDescDealer: 'Cần giá tốt, hàng sẵn số lượng lớn, đẩy tồn kho nhanh.',
  guideTypeWorkshop: 'Xưởng may',
  guideDescWorkshop:
    'Cần độ ổn định tuyệt đối về chất lượng và định lượng vải.',
  guideTypeBrand: 'Local Brand / Studio',
  guideDescBrand:
    'Cần mẫu mã độc lạ, thường xuyên gửi sample, chấp nhận giá cao.',
} as const;

export const CUSTOMER_TIMELINE_LABELS = {
  empty: 'Khách hàng chưa có lịch sử tương tác nào',
  other: 'Khác',
  rfqPrefix: 'Báo giá',
  samplePrefix: 'Xin mẫu',
  contactGeneral: 'Liên hệ chung',
  sourcePrefix: 'Khách hàng từ nguồn:',
  sourceDirect: 'Trực tiếp',
} as const;

export const CUSTOMER_LIST_LABELS = {
  title: 'Danh sách khách hàng',
  subtitle: 'Quản lý thông tin khách hàng',
  addCustomerBtn: 'Thêm khách hàng',
  kpiTotal: 'Tổng khách hàng',
  kpiTotalDesc: 'Cơ sở dữ liệu khách hàng',
  kpiActive: 'Đang hoạt động',
  kpiActiveDesc: 'Khách hàng có giao dịch',
  kpiNew: 'Khách hàng mới',
  kpiNewDesc: 'Đã thêm trong kỳ',
  searchPlaceholder: 'Tìm theo tên, mã KH, sđt...',
  searchLabel: 'Tìm kiếm khách hàng',
  statusLabel: 'Trạng thái',
  salespersonLabel: 'Phụ trách',
  tabAll: 'Tất cả khách hàng',
  tabMine: 'Khách của tôi',
  tabNew: 'Khách mới tuần này',
  deleteConfirmMsg:
    'Xóa khách hàng "{name}"? Hành động này không thể hoàn tác.',
  bulkAssignLabel: 'Đổi người phụ trách',
  bulkStatusLabel: 'Cập nhật trạng thái',
  bulkEmailLabel: 'Gửi SMS/Email',
  bulkEmailDevAlert:
    'Tính năng gửi SMS/Email cho {count} khách hàng đang được phát triển.',
  emptyFilterTitle: 'Không tìm thấy khách hàng',
  emptyFilterDesc: 'Vui lòng thử điều chỉnh lại bộ lọc.',
  emptyTitle: 'Chưa có thông tin khách hàng',
  emptyDesc: 'Hãy thêm khách hàng mới để quản lý thông tin.',
  emptyAddBtn: '+ Thêm khách hàng',
  exportFileName: 'DanhSachKhachHang',
  itemLabel: 'khách hàng',
  bulkAssignTitle: 'Đổi người phụ trách',
  bulkAssignDesc: 'Bạn đang chọn {count} khách hàng để chuyển người phụ trách.',
  bulkAssignFieldLabel: 'Nhân viên phụ trách mới',
  bulkAssignPlaceholder: 'Chọn nhân viên...',
  bulkAssignSubmit: 'Xác nhận',
  bulkStatusTitle: 'Cập nhật trạng thái',
  bulkStatusDesc:
    'Bạn đang chọn {count} khách hàng để cập nhật trạng thái CRM.',
  bulkStatusFieldLabel: 'Trạng thái mới',
  bulkStatusPlaceholder: 'Chọn trạng thái...',
  bulkStatusSubmit: 'Cập nhật',
  cancelBtn: 'Hủy',
} as const;

export const CUSTOMER_COLUMNS_LABELS = {
  code: 'Mã KH',
  nameAndAddress: 'Tên & Địa chỉ',
  contact: 'Liên hệ',
  phoneCallTitle: 'Gọi điện thoại',
  zaloMessageTitle: 'Nhắn tin Zalo',
  source: 'Nguồn',
  leadStatus: 'Phễu CRM',
  status: 'Trạng thái',
  salesperson: 'Phụ trách',
  actions: 'Thao tác',
  actionMessage: 'Nhắn tin',
  actionDeposit: 'Nạp tiền',
  actionContract: 'Tạo hợp đồng',
  actionEdit: 'Chỉnh sửa',
  actionDelete: 'Xóa khách hàng',
} as const;

export const CUSTOMER_PORTAL_LABELS = {
  successCreated: 'Tài khoản Portal đã được tạo cho {name}.',
  errorCreateFailed: 'Tạo tài khoản thất bại.',
  deactivateTitle: 'Vô hiệu hóa tài khoản',
  deactivateConfirmMsg:
    'Bạn có chắc chắn muốn vô hiệu hóa tài khoản Portal của {name}?',
  deactivateBtn: 'Vô hiệu hóa',
  cancelBtn: 'Hủy',
  successDeactivated: 'Tài khoản đã bị vô hiệu hóa.',
  successReactivated: 'Tài khoản đã được kích hoạt lại.',
  loadingCheck: 'Đang kiểm tra tài khoản Portal…',
  statusActive: 'Hoạt động',
  statusDeactivated: 'Vô hiệu hóa',
  noAccountMsg: 'Khách hàng chưa có tài khoản Portal.',
  createAccountBtn: '+ Tạo tài khoản',
  emailLabel: 'Email',
  emailPlaceholder: 'khachhang@email.com',
  passwordLabel: 'Mật khẩu',
  passwordPlaceholder: 'Tối thiểu 8 ký tự',
  submitCreating: 'Đang tạo…',
  submitConfirm: 'Xác nhận',
  actionProcessing: 'Đang xử lý…',
  actionDeactivate: '⊘ Vô hiệu hóa tài khoản',
  actionReactivate: '↺ Kích hoạt lại',
} as const;

export const CUSTOMER_MODULE_LABELS = {
  title: 'Khách hàng',
  description: 'Danh mục khách hàng và quản lý công nợ khách hàng.',
  subTitle:
    'Quản lý danh sách khách hàng, hợp đồng, bảng giá và phân hạng đối tác.',
  menuAllCustomers: 'Tổng khách hàng',
  menuActiveCustomers: 'Đang hoạt động',
  featureRanking: 'Phân hạng Gold/Silver/Bronze.',
  featureDebtWarning: 'Cảnh báo hạn mức nợ.',
  featureSalesTracking: 'Theo dõi doanh số luỹ kế.',
  featureCRM: 'Tính năng CRM chăm sóc khách hàng tự động.',
  featurePortal: 'Portal khách hàng tra cứu đơn hàng.',
} as const;
