import { PAYMENT_METHOD_LABELS } from '@/schema/payment.schema';

/** Centralized labels for the Deposit (advance payment) form. */
export const DEPOSIT_FORM_LABELS = {
  title: 'Nạp tiền khách hàng',
  receiptNumber: 'Số phiếu thu',
  autoGenerated: 'Tự động',
  dateLabel: 'Ngày nạp',
  amountLabel: 'Số tiền nạp (đ)',
  amountPlaceholder: 'VD: 5.000.000',
  methodLabel: 'Hình thức',
  referenceLabel: 'Số chứng từ / ghi chú nạp tiền',
  referencePlaceholder: 'Chuyển khoản cọc trước, ghi chú...',
  cancelButton: 'Hủy',
  submitButton: 'Xác nhận nạp',
  submittingButton: 'Đang lưu...',
  errorPrefix: 'Lỗi:',
  balanceColumnHeader: 'Số dư (đ)',
} as const;

/**
 * Payment method options for deposit form.
 * Excludes 'customer_balance' since deposits are real money inflows.
 */
export const DEPOSIT_PAYMENT_METHOD_OPTIONS = Object.entries(
  PAYMENT_METHOD_LABELS,
)
  .filter(([key]) => key !== 'customer_balance')
  .map(([value, label]) => ({ value, label }));
