import { zodResolver } from '@hookform/resolvers/zod';
import { useForm, Controller } from 'react-hook-form';

import { AdaptiveSheet } from '@/shared/components/AdaptiveSheet';
import { Combobox } from '@/shared/components/Combobox';
import { Button } from '@/shared/components';
import { CurrencyInput } from '@/shared/components/CurrencyInput';
import { paymentsSchema, paymentsDefaultValues } from '@/schema/payment.schema';
import type { PaymentsFormValues } from '@/schema/payment.schema';
import { useCreatePayment } from '@/application/payments';
import { getErrorMessage } from '@/shared/utils/error';

import {
  DEPOSIT_FORM_LABELS,
  DEPOSIT_PAYMENT_METHOD_OPTIONS,
} from './customers.constants';

type DepositFormProps = {
  customerId: string;
  customerName: string;
  onClose: () => void;
};

export function DepositForm({
  customerId,
  customerName,
  onClose,
}: DepositFormProps) {
  const createMutation = useCreatePayment();

  const {
    register,
    handleSubmit,
    control,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<PaymentsFormValues>({
    resolver: zodResolver(paymentsSchema),
    defaultValues: {
      ...paymentsDefaultValues,
      customerId,
    },
  });

  async function onSubmit(values: PaymentsFormValues) {
    await createMutation.mutateAsync({
      ...values,
      orderId: values.orderId || undefined,
    });
    reset();
    onClose();
  }

  return (
    <AdaptiveSheet
      open={true}
      onClose={onClose}
      title={`${DEPOSIT_FORM_LABELS.title} — ${customerName}`}
    >
      <form id="deposit-form" onSubmit={handleSubmit(onSubmit)}>
        {createMutation.error && (
          <p className="error-inline mb-4">
            {DEPOSIT_FORM_LABELS.errorPrefix}{' '}
            {getErrorMessage(createMutation.error)}
          </p>
        )}

        <div className="form-grid">
          {/* Payment number + date */}
          <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
            <div className="form-field">
              <label>{DEPOSIT_FORM_LABELS.receiptNumber}</label>
              <input
                className="field-input field-input--readonly"
                value={DEPOSIT_FORM_LABELS.autoGenerated}
                readOnly
                disabled
              />
            </div>
            <div className="form-field">
              <label>
                {DEPOSIT_FORM_LABELS.dateLabel}{' '}
                <span className="field-required">*</span>
              </label>
              <input
                className={`field-input${errors.paymentDate ? ' is-error' : ''}`}
                type="date"
                {...register('paymentDate')}
              />
              {errors.paymentDate && (
                <p className="field-error">{errors.paymentDate.message}</p>
              )}
            </div>
          </div>

          {/* Amount + method */}
          <div className="form-grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))]">
            <div className="form-field">
              <label>
                {DEPOSIT_FORM_LABELS.amountLabel}{' '}
                <span className="field-required">*</span>
              </label>
              <Controller
                name="amount"
                control={control}
                render={({ field }) => (
                  <CurrencyInput
                    className={`field-input${errors.amount ? ' is-error' : ''}`}
                    value={field.value}
                    onChange={(v) => field.onChange(v ?? 0)}
                    onBlur={field.onBlur}
                    placeholder={DEPOSIT_FORM_LABELS.amountPlaceholder}
                  />
                )}
              />
              {errors.amount && (
                <p className="field-error">{errors.amount.message}</p>
              )}
            </div>
            <div className="form-field">
              <label>
                {DEPOSIT_FORM_LABELS.methodLabel}{' '}
                <span className="field-required">*</span>
              </label>
              <Controller
                name="paymentMethod"
                control={control}
                render={({ field }) => (
                  <Combobox
                    options={DEPOSIT_PAYMENT_METHOD_OPTIONS}
                    value={field.value}
                    onChange={field.onChange}
                    hasError={!!errors.paymentMethod}
                  />
                )}
              />
            </div>
          </div>

          {/* Reference */}
          <div className="form-field">
            <label>{DEPOSIT_FORM_LABELS.referenceLabel}</label>
            <input
              className="field-input"
              {...register('referenceNumber')}
              placeholder={DEPOSIT_FORM_LABELS.referencePlaceholder}
            />
          </div>
        </div>

        {/* Actions */}
        <div className="mt-8 pt-4 border-t border-border flex flex-col-reverse sm:flex-row sm:justify-end gap-3">
          <Button
            variant="secondary"
            type="button"
            onClick={onClose}
            disabled={isSubmitting || createMutation.isPending}
            className="w-full sm:w-auto justify-center"
          >
            {DEPOSIT_FORM_LABELS.cancelButton}
          </Button>
          <Button
            variant="primary"
            type="submit"
            disabled={isSubmitting || createMutation.isPending}
            className="w-full sm:w-auto justify-center"
          >
            {createMutation.isPending
              ? DEPOSIT_FORM_LABELS.submittingButton
              : DEPOSIT_FORM_LABELS.submitButton}
          </Button>
        </div>
      </form>
    </AdaptiveSheet>
  );
}
