export const COSTING_LABELS = {
  MODAL_TITLE: 'Máy tính Giá Vải Mộc (Costing Studio)',
  BTN_CLOSE: 'Đóng',
  STEP_1_BOM: '1. Chọn Định mức (BOM)',
  BOM_PLACEHOLDER: '-- Chọn BOM đã duyệt để giả lập --',
  LOADING_BOM: 'Đang tải chi tiết BOM và giá sợi mới nhất...',
  TAB_SIMULATOR: 'Giả lập giá (Simulator)',
  TAB_HISTORY: 'Lịch sử (Snapshots)',
  WEAVING_PRICE: 'Đơn giá dệt',
  LOSS_PCT: 'Hao hụt chuẩn (%)',
  PROFIT_MARGIN_PCT: 'Biên Lợi Nhuận (%)',
  SUGGESTED_PRICE: 'Giá Bán Đề Xuất',
  UNIT_PRICE: 'đ/m',
  BTN_SAVING: 'Đang lưu...',
  BTN_SAVE_SNAPSHOT: 'Lưu Snapshot lên Cloud',
  BTN_CREATE_WORK_ORDER: 'Tạo Lệnh Sản Xuất',
  COST_STRUCTURE: 'Cơ cấu giá vốn',
  COMPONENT: 'Thành phần',
  PERCENTAGE: 'Tỷ lệ',
  VALUE_VND: 'Giá trị (VNĐ)',
  TOTAL_COST: 'Tổng giá vốn (Total Cost)',
  YARN_COST_TITLE: 'Đơn giá sợi thành phần (VNĐ/kg)',
  CONSUMPTION: 'Định mức: ',
  KG_PER_M: ' kg/m',
  OVERRIDE_PRICE_MANUAL: 'Ghi đè giá thủ công',
  ENTER_NEW_PRICE: 'Nhập giá mới...',
  LOADING_HISTORY: 'Đang tải lịch sử tính giá...',
  EMPTY_HISTORY: 'Chưa có lịch sử tính giá (snapshot) nào.',
  COL_VERSION: 'Phiên bản',
  COL_DATE: 'Ngày lưu',
  COL_YARN: 'Tiền sợi',
  COL_TOTAL_GREIGE: 'Giá mộc tổng',
  COL_SUGGESTED: 'Giá đề xuất',
  COL_ACTIONS: 'Thao tác',
  BADGE_CURRENT: 'Đang chọn',
  TITLE_RESTORE: 'Phục hồi tham số từ phiên bản này',
  TITLE_NO_RESTORE: 'Không có dữ liệu tham số để phục hồi',
  CURRENCY_SYMBOL: 'đ',
  YARN_PREFIX: 'Sợi ',
  WEAVING_COST_LABEL: 'Công dệt',
} as const;

export const COSTING_MESSAGES = {
  SAVE_SUCCESS: 'Đã lưu snapshot thành công!',
  SAVE_ERROR: 'Có lỗi xảy ra khi lưu snapshot giả lập trên Cloud.',
} as const;
