import fs from 'fs';
import path from 'path';

const FEATURES_DIR = 'src/features/orders';

// Define the exact mapping
const MAPPING = {
  // FORM LABELS
  TITLE_EDIT: 'ORDERS_FORM_LABELS',
  TITLE_NEW: 'ORDERS_FORM_LABELS',
  UNSAVED_WARNING: 'ORDERS_FORM_LABELS',
  ERROR_PREFIX: 'ORDERS_FORM_LABELS',
  FIELD_ORDER_NUMBER: 'ORDERS_FORM_LABELS',
  FIELD_ORDER_TYPE: 'ORDERS_FORM_LABELS',
  FIELD_ORDER_DATE: 'ORDERS_FORM_LABELS',
  FIELD_CUSTOMER: 'ORDERS_FORM_LABELS',
  FIELD_DELIVERY_DATE: 'ORDERS_FORM_LABELS',
  FIELD_NOTES: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_NOTES: 'ORDERS_FORM_LABELS',
  SECTION_ITEMS: 'ORDERS_FORM_LABELS',
  ITEM_ROW_PREFIX: 'ORDERS_FORM_LABELS',
  BTN_REMOVE: 'ORDERS_FORM_LABELS',
  BTN_REMOVE_TITLE: 'ORDERS_FORM_LABELS',
  FIELD_FABRIC_TYPE: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_FABRIC: 'ORDERS_FORM_LABELS',
  FIELD_COLOR: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_COLOR: 'ORDERS_FORM_LABELS',
  FIELD_COLOR_CODE: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_COLOR_CODE: 'ORDERS_FORM_LABELS',
  FIELD_UNIT: 'ORDERS_FORM_LABELS',
  BTN_ADD_ITEM: 'ORDERS_FORM_LABELS',
  BTN_SAVE: 'ORDERS_FORM_LABELS',
  BTN_CREATE: 'ORDERS_FORM_LABELS',
  TXT_TOTAL: 'ORDERS_FORM_LABELS',
  AUTO_NUMBER: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_CUSTOMER: 'ORDERS_FORM_LABELS',
  FIELD_QUANTITY: 'ORDERS_FORM_LABELS',
  FIELD_PRICE: 'ORDERS_FORM_LABELS',
  LBL_TOTAL_AMOUNT: 'ORDERS_FORM_LABELS',
  LBL_BALANCE_DUE: 'ORDERS_FORM_LABELS',
  LBL_DELIVERY: 'ORDERS_FORM_LABELS',
  BADGE_TRADING: 'ORDERS_FORM_LABELS',
  FIELD_PRODUCT_CATEGORY: 'ORDERS_FORM_LABELS',
  FIELD_STOCK_SOURCE: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_SELECT_YARN: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_SELECT_FABRIC: 'ORDERS_FORM_LABELS',
  FIELD_LOT: 'ORDERS_FORM_LABELS',
  PLACEHOLDER_LOT: 'ORDERS_FORM_LABELS',
  FIELD_AUTO_YARN_NAME: 'ORDERS_FORM_LABELS',
  ERR_STOCK_EXCEEDED: 'ORDERS_FORM_LABELS',

  // LIST LABELS
  SEARCH_LABEL: 'ORDERS_LIST_LABELS',
  SEARCH_PLACEHOLDER: 'ORDERS_LIST_LABELS',
  ERR_DELETE_ONLY_DRAFT: 'ORDERS_LIST_LABELS',
  CONFIRM_DELETE: 'ORDERS_LIST_LABELS',
  PAGE_TITLE: 'ORDERS_LIST_LABELS',
  PAGE_SUBTITLE: 'ORDERS_LIST_LABELS',
  BTN_PROGRESS: 'ORDERS_LIST_LABELS',
  BTN_CREATE_ORDER: 'ORDERS_LIST_LABELS',
  BTN_CREATE_ORDER_PLUS: 'ORDERS_LIST_LABELS',
  ERR_LOAD_DATA: 'ORDERS_LIST_LABELS',
  EMPTY_SEARCH_TITLE: 'ORDERS_LIST_LABELS',
  EMPTY_NO_DATA_TITLE: 'ORDERS_LIST_LABELS',
  EMPTY_SEARCH_DESC: 'ORDERS_LIST_LABELS',
  EMPTY_NO_DATA_DESC: 'ORDERS_LIST_LABELS',
  PAGINATION_LABEL: 'ORDERS_LIST_LABELS',
  ERR_NOT_FOUND: 'ORDERS_LIST_LABELS',
  CONFIRM_TRADING: 'ORDERS_LIST_LABELS',
  CONFIRM_PRODUCTION: 'ORDERS_LIST_LABELS',
  CONFIRM_CANCEL_TRADING: 'ORDERS_LIST_LABELS',
  CONFIRM_CANCEL: 'ORDERS_LIST_LABELS',
  CONFIRM_COMPLETE: 'ORDERS_LIST_LABELS',
  CONFIRM_APPROVE_REQ: 'ORDERS_LIST_LABELS',
  CONFIRM_REJECT_REQ: 'ORDERS_LIST_LABELS',
  BTN_BACK: 'ORDERS_LIST_LABELS',
  TYPE_PRODUCTION: 'ORDERS_LIST_LABELS',
  LBL_ORDER_DATE: 'ORDERS_LIST_LABELS',
  LBL_DELIVERY_DATE: 'ORDERS_LIST_LABELS',
  LBL_PAID_AMOUNT: 'ORDERS_LIST_LABELS',
  LBL_NOTES_PREFIX: 'ORDERS_LIST_LABELS',
  LBL_PAYMENT_PROGRESS: 'ORDERS_LIST_LABELS',
  BTN_APPROVE_REQ: 'ORDERS_LIST_LABELS',
  BTN_REJECT_REQ: 'ORDERS_LIST_LABELS',
  BTN_EDIT: 'ORDERS_LIST_LABELS',
  BTN_CONFIRM_TRADING: 'ORDERS_LIST_LABELS',
  BTN_CONFIRM: 'ORDERS_LIST_LABELS',
  BTN_SHIP: 'ORDERS_LIST_LABELS',
  BTN_PAY: 'ORDERS_LIST_LABELS',
  BTN_COMPLETE: 'ORDERS_LIST_LABELS',
  BTN_CONTRACT: 'ORDERS_LIST_LABELS',
  BTN_CANCEL: 'ORDERS_LIST_LABELS',
  EMPTY_ITEMS: 'ORDERS_LIST_LABELS',
  COL_SOURCE: 'ORDERS_LIST_LABELS',
  TYPE_FABRIC: 'ORDERS_LIST_LABELS',
  COL_PRICE: 'ORDERS_LIST_LABELS',
  COL_AMOUNT: 'ORDERS_LIST_LABELS',
  COL_ORDER_CUSTOMER: 'ORDERS_LIST_LABELS',
  COL_ORDER_DATE: 'ORDERS_LIST_LABELS',
  COL_DELIVERY_DATE: 'ORDERS_LIST_LABELS',
  COL_TOTAL: 'ORDERS_LIST_LABELS',
  COL_BALANCE: 'ORDERS_LIST_LABELS',
  COL_STATUS: 'ORDERS_LIST_LABELS',
  COL_ACTIONS: 'ORDERS_LIST_LABELS',
  AUDIT_LOG_TITLE: 'ORDERS_LIST_LABELS',

  // PROG LABELS
  PROG_LOADING: 'ORDERS_PROG_LABELS',
  PROG_EMPTY_ACTIVE: 'ORDERS_PROG_LABELS',
  PROG_EMPTY_AUDIT: 'ORDERS_PROG_LABELS',
  PROG_OVERDUE: 'ORDERS_PROG_LABELS',
  PROG_READY_TO_SHIP: 'ORDERS_PROG_LABELS',
  PROG_IN_PROGRESS: 'ORDERS_PROG_LABELS',
  PROG_WAITING: 'ORDERS_PROG_LABELS',
  PROG_SECTION_OVERDUE: 'ORDERS_PROG_LABELS',
  PROG_SECTION_READY: 'ORDERS_PROG_LABELS',
  PROG_SECTION_WAITING: 'ORDERS_PROG_LABELS',
  PROG_LATE_DAYS: 'ORDERS_PROG_LABELS',
  PROG_LATE_SUFFIX: 'ORDERS_PROG_LABELS',
  PROG_TIMELINE_TITLE: 'ORDERS_PROG_LABELS',
  PROG_EXPECTED: 'ORDERS_PROG_LABELS',
  PROG_ACTUAL: 'ORDERS_PROG_LABELS',
  PROG_BOARD_TITLE: 'ORDERS_PROG_LABELS',
  PROG_PAGE_TITLE: 'ORDERS_PROG_LABELS',
  PROG_FILTER_STAGE: 'ORDERS_PROG_LABELS',
  PROG_FILTER_STATUS: 'ORDERS_PROG_LABELS',
  PROG_FILTER_ALL: 'ORDERS_PROG_LABELS',
  PROG_STATUS_PENDING: 'ORDERS_PROG_LABELS',
  PROG_STATUS_DOING: 'ORDERS_PROG_LABELS',
  PROG_STATUS_DONE: 'ORDERS_PROG_LABELS',
  PROG_STATUS_SKIPPED: 'ORDERS_PROG_LABELS',
  PROG_BTN_START: 'ORDERS_PROG_LABELS',
  PROG_BTN_COMPLETE: 'ORDERS_PROG_LABELS',
  PROG_BTN_SKIP: 'ORDERS_PROG_LABELS',
  PROG_BTN_SAVE: 'ORDERS_PROG_LABELS',
  PROG_BTN_CANCEL: 'ORDERS_PROG_LABELS',
  PROG_PLACEHOLDER_NOTE: 'ORDERS_PROG_LABELS',
  PROG_ERROR_UPDATE: 'ORDERS_PROG_LABELS',
  PROG_STANDALONE_WO: 'ORDERS_PROG_LABELS',
  PROG_EMPTY_FILTER: 'ORDERS_PROG_LABELS',
  PROG_EMPTY_CONFIRMED: 'ORDERS_PROG_LABELS',
  PROG_BTN_CLEAR_FILTER: 'ORDERS_PROG_LABELS',
  PROG_AUDIT_LOG_TITLE: 'ORDERS_PROG_LABELS',
  PROG_AUDIT_LOG_RECENT: 'ORDERS_PROG_LABELS',
  PROG_TAB_DASHBOARD: 'ORDERS_PROG_LABELS',
  PROG_TAB_BOARD: 'ORDERS_PROG_LABELS',
  PROG_TAB_AUDIT: 'ORDERS_PROG_LABELS',

  // RES LABELS
  RES_TAB_PREFIX: 'ORDERS_RES_LABELS',
  RES_SUM_RESERVED: 'ORDERS_RES_LABELS',
  RES_SUM_LENGTH: 'ORDERS_RES_LABELS',
  RES_SUM_WEIGHT: 'ORDERS_RES_LABELS',
  RES_COL_ROLL: 'ORDERS_RES_LABELS',
  RES_COL_FABRIC: 'ORDERS_RES_LABELS',
  RES_COL_COLOR: 'ORDERS_RES_LABELS',
  RES_COL_LENGTH: 'ORDERS_RES_LABELS',
  RES_COL_WEIGHT: 'ORDERS_RES_LABELS',
  RES_COL_LOCATION: 'ORDERS_RES_LABELS',
  RES_COL_GRADE: 'ORDERS_RES_LABELS',
  RES_TITLE: 'ORDERS_RES_LABELS',
  RES_REQUIRED: 'ORDERS_RES_LABELS',
  RES_RESERVED_LIST_TITLE: 'ORDERS_RES_LABELS',
  RES_AVAILABLE_LIST_TITLE: 'ORDERS_RES_LABELS',
  RES_BTN_UNRESERVE: 'ORDERS_RES_LABELS',
  RES_BTN_RESERVE: 'ORDERS_RES_LABELS',
  RES_BTN_PROCESSING: 'ORDERS_RES_LABELS',
  RES_EMPTY_AVAILABLE: 'ORDERS_RES_LABELS',
  RES_FOR: 'ORDERS_RES_LABELS',
  RES_BTN_CLOSE: 'ORDERS_RES_LABELS',

  // OVERRIDE
  OVERRIDE_DIALOG_TITLE: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_DIALOG_WARNING: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_MSG_ADMIN_ONLY: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_MSG_SALE_ONLY: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_BTN_CONFIRM: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_BTN_CANCEL: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_TITLE_OVERDUE: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_TITLE_LIMIT: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_SUB_OVERDUE: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_SUB_LIMIT: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_CLOSE: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_STAT_OVERDUE: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_STAT_CURRENT: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_STAT_NEW: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_STAT_PROJECTED: 'ORDERS_OVERRIDE_LABELS',
  OVERRIDE_STAT_LIMIT: 'ORDERS_OVERRIDE_LABELS',

  // DASHBOARD
  KPI_PENDING_APPROVAL: 'ORDERS_DASHBOARD_LABELS',
  KPI_EXPECTED_REVENUE: 'ORDERS_DASHBOARD_LABELS',
  KPI_TOTAL_DEBT: 'ORDERS_DASHBOARD_LABELS',
  KPI_PENDING_DESC: 'ORDERS_DASHBOARD_LABELS',
  KPI_REVENUE_DESC: 'ORDERS_DASHBOARD_LABELS',
  KPI_DEBT_DESC: 'ORDERS_DASHBOARD_LABELS',
  DASHBOARD_TABLE_TITLE: 'ORDERS_DASHBOARD_LABELS',
  DASH_TAB_ALL: 'ORDERS_DASHBOARD_LABELS',
  DASH_TAB_IN_PROGRESS: 'ORDERS_DASHBOARD_LABELS',
  DASH_TAB_OVERDUE: 'ORDERS_DASHBOARD_LABELS',
  DASH_TAB_FULFILLED: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_ORDER: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_CUSTOMER: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_STATUS: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_PCT: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_WO: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_PROGRESS: 'ORDERS_DASHBOARD_LABELS',
  DASH_COL_DELIVERY: 'ORDERS_DASHBOARD_LABELS',
  COL_ORDER_CODE: 'ORDERS_DASHBOARD_LABELS',
  COL_STAGE: 'ORDERS_DASHBOARD_LABELS',
  LBL_LATE: 'ORDERS_DASHBOARD_LABELS',
  LBL_ON_TIME: 'ORDERS_DASHBOARD_LABELS',
  LBL_WARNING: 'ORDERS_DASHBOARD_LABELS',
  KPI_TOTAL_ORDERS: 'ORDERS_DASHBOARD_LABELS',
  KPI_ON_TIME: 'ORDERS_DASHBOARD_LABELS',
  KPI_LATE: 'ORDERS_DASHBOARD_LABELS',
  KPI_WARNING: 'ORDERS_DASHBOARD_LABELS',
  KPI_COMPLETED_TODAY: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_TOTAL_PROC: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_FULFILLED: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_PROD_DONE: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_ORDERS: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_LATE_DELIV: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_URGENT: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_GOOD: 'ORDERS_DASHBOARD_LABELS',
  DASH_KPI_AVG_PCT: 'ORDERS_DASHBOARD_LABELS',

  // AUDIT
  AUDIT_LBL_USER: 'ORDERS_AUDIT_LABELS',
  AUDIT_LBL_ACTION: 'ORDERS_AUDIT_LABELS',
  AUDIT_LBL_TIME: 'ORDERS_AUDIT_LABELS',
  AUDIT_LBL_DETAILS: 'ORDERS_AUDIT_LABELS',
  AUDIT_EMPTY: 'ORDERS_AUDIT_LABELS',
  AUDIT_LOADING: 'ORDERS_AUDIT_LABELS',
  AUDIT_ERROR: 'ORDERS_AUDIT_LABELS',
  AUDIT_DEFAULT_ACTOR: 'ORDERS_AUDIT_LABELS',
  AUDIT_EVENT_ORDER_CREATED: 'ORDERS_AUDIT_LABELS',
  AUDIT_EVENT_ORDER_CREATED_DETAIL: 'ORDERS_AUDIT_LABELS',
  AUDIT_EVENT_REQ_CREATED: 'ORDERS_AUDIT_LABELS',
  AUDIT_EVENT_REQ_CREATED_DETAIL: 'ORDERS_AUDIT_LABELS',
  AUDIT_EVENT_STATUS_CHANGED: 'ORDERS_AUDIT_LABELS',
};

function walkDir(dir, callback) {
  fs.readdirSync(dir).forEach(f => {
    let dirPath = path.join(dir, f);
    let isDirectory = fs.statSync(dirPath).isDirectory();
    isDirectory ? walkDir(dirPath, callback) : callback(dirPath);
  });
}

walkDir(FEATURES_DIR, function(filePath) {
  if (filePath.endsWith('.tsx') || filePath.endsWith('.ts')) {
    if (filePath.includes('orders.constants.ts')) return;

    let content = fs.readFileSync(filePath, 'utf8');
    let original = content;
    let usedScopes = new Set();

    // Replace MSG.xxx or ORDER_MESSAGES.xxx
    content = content.replace(/\b(MSG|ORDER_MESSAGES)\.([A-Z0-9_]+)/g, (match, prefix, key) => {
      if (MAPPING[key]) {
        usedScopes.add(MAPPING[key]);
        return `${MAPPING[key]}.${key}`;
      }
      return match;
    });

    if (usedScopes.size > 0) {
      // Find existing import of these scopes OR the old import
      const scopesArr = Array.from(usedScopes).sort();
      const newImportString = `import { ${scopesArr.join(', ')} } from '@/features/orders/orders.constants';`;

      const existingImportRegex = /import\s+\{([^}]+)\}\s+from\s+['"]([^'"]*orders\.constants)['"];?/g;
      
      let matched = false;
      content = content.replace(existingImportRegex, (match, imports, source) => {
        if (!matched) {
            matched = true;
            // merge existing named imports with our used scopes
            const existingImports = imports.split(',').map(s => s.trim()).filter(Boolean);
            const allImports = new Set([...existingImports, ...scopesArr]);
            
            // remove 'ORDER_MESSAGES' and 'ORDER_MESSAGES as MSG'
            const cleanImports = [];
            for (const imp of allImports) {
               if (imp === 'ORDER_MESSAGES' || imp.includes('ORDER_MESSAGES as MSG') || imp.includes('ORDERS_LIST_LABELS as MSG')) continue;
               cleanImports.push(imp);
            }
            
            return `import { ${cleanImports.join(', ')} } from '${source}';`;
        }
        return match; // only replace first one
      });

      if (!matched) {
          content = newImportString + '\n' + content;
      }
    }

    if (content !== original) {
      fs.writeFileSync(filePath, content, 'utf8');
      console.log('Updated ' + filePath);
    }
  }
});
