/**
 * generate-migration.ts
 * Tự động sinh file SQL migration cho MISSING và PARAM_MISMATCH issues.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import path from 'path';

import { RpcCall, ParamType } from './parse-rpc-calls';
import { SyncIssue } from './check-rpc-sync';

const MIGRATIONS_DIR = path.resolve('./supabase/migrations');

// ──────────────────────────────────────────────
// Map inferred type → SQL declaration
// ──────────────────────────────────────────────
function toSqlType(type: ParamType): string {
  const map: Record<ParamType, string> = {
    uuid:        'uuid',
    text:        'text',
    int:         'integer',
    numeric:     'numeric',
    boolean:     'boolean',
    timestamptz: 'timestamptz',
    jsonb:       'jsonb',
  };
  return map[type] ?? 'text';
}

// ──────────────────────────────────────────────
// Infer tên bảng từ tên function
// update_supplier → suppliers
// create_order_item → order_items
// delete_product → products
// get_next_supplier_code → (không update, trả về text)
// ──────────────────────────────────────────────
function inferTableName(fnName: string): string {
  const withoutPrefix = fnName.replace(/^(update|create|delete|insert|upsert)_/, '');
  // Pluralize đơn giản: thêm 's' (hoặc 'es' nếu kết thúc bằng s/x/z/ch/sh)
  if (/[sxz]$|[cs]h$/.test(withoutPrefix)) return withoutPrefix + 'es';
  return withoutPrefix + 's';
}

// ──────────────────────────────────────────────
// Infer loại operation từ tên function
// ──────────────────────────────────────────────
type Operation = 'UPDATE' | 'INSERT' | 'DELETE' | 'SELECT' | 'UNKNOWN';

function inferOperation(fnName: string): Operation {
  if (fnName.startsWith('update_'))  return 'UPDATE';
  if (fnName.startsWith('create_') || fnName.startsWith('insert_')) return 'INSERT';
  if (fnName.startsWith('delete_') || fnName.startsWith('remove_')) return 'DELETE';
  if (fnName.startsWith('get_') || fnName.startsWith('fetch_') || fnName.startsWith('list_')) return 'SELECT';
  return 'UNKNOWN';
}

// ──────────────────────────────────────────────
// Build SQL body dựa theo operation
// ──────────────────────────────────────────────
function buildSqlBody(call: RpcCall, operation: Operation): { body: string; returnType: string } {
  const tableName = inferTableName(call.fnName);
  const idParam = call.params.find((p) => p.name === 'p_id' || p.name === 'id');
  const dataParams = call.params.filter((p) => p.name !== 'p_id' && p.name !== 'id');

  switch (operation) {
    case 'UPDATE': {
      const setLines = dataParams.map((p) => {
        const col = p.name.replace(/^p_/, '');
        const val = p.optional ? `NULLIF(${p.name}, '')` : p.name;
        return `    ${col.padEnd(20)} = ${val}`;
      });
      // updated_at nếu có — thêm vào, dev có thể xóa nếu không cần
      setLines.push(`    ${'updated_at'.padEnd(20)} = now()`);

      return {
        returnType: 'void',
        body: `
  UPDATE public.${tableName}
  SET
${setLines.join(',\n')}
  WHERE ${idParam ? `id = ${idParam.name}` : '/* TODO: add WHERE clause */'};
`.trimStart(),
      };
    }

    case 'INSERT': {
      const colNames = dataParams.map((p) => p.name.replace(/^p_/, ''));
      const colValues = dataParams.map((p) =>
        p.optional ? `NULLIF(${p.name}, '')` : p.name
      );

      return {
        returnType: 'void',
        body: `
  INSERT INTO public.${tableName} (${colNames.join(', ')})
  VALUES (${colValues.join(', ')});
`.trimStart(),
      };
    }

    case 'DELETE': {
      return {
        returnType: 'void',
        body: `
  DELETE FROM public.${tableName}
  WHERE ${idParam ? `id = ${idParam.name}` : '/* TODO: add WHERE clause */'};
`.trimStart(),
      };
    }

    default: {
      // Fallback: sinh template trống để dev tự điền
      return {
        returnType: 'void',
        body: `
  -- TODO: implement function body
  -- Table: public.${tableName}
  NULL;
`.trimStart(),
      };
    }
  }
}

// ──────────────────────────────────────────────
// Build toàn bộ SQL function
// ──────────────────────────────────────────────
function buildSql(call: RpcCall): string {
  const operation = inferOperation(call.fnName);
  const { body, returnType } = buildSqlBody(call, operation);

  // Phần khai báo params
  const paramLines = call.params.map((p) => {
    const sqlType = toSqlType(p.type);
    const defaultClause = p.optional ? '  DEFAULT NULL' : '';
    return `  ${p.name.padEnd(22)} ${sqlType}${defaultClause}`;
  });

  const header = [
    `-- Generated by rpc-sync at ${new Date().toISOString()}`,
    `-- Source: ${call.sourceFile}:${call.line}`,
    `-- Operation inferred: ${operation}`,
    '',
    `CREATE OR REPLACE FUNCTION public.${call.fnName}(`,
    paramLines.join(',\n'),
    `)`,
    `RETURNS ${returnType}`,
    `LANGUAGE sql`,
    `AS $$`,
  ].join('\n');

  return `${header}\n  ${body}\n$$;\n`;
}

// ──────────────────────────────────────────────
// Main: tạo file migration
// ──────────────────────────────────────────────
export function generateMigration(call: RpcCall, issue: SyncIssue): string {
  if (!existsSync(MIGRATIONS_DIR)) {
    mkdirSync(MIGRATIONS_DIR, { recursive: true });
  }

  const timestamp = new Date()
    .toISOString()
    .replace(/[-T:.Z]/g, '')
    .slice(0, 14); // "20240523153045"

  const suffix = issue.kind === 'MISSING' ? 'create' : 'fix';
  const filename = `${timestamp}_${suffix}_${call.fnName}.sql`;
  const filepath = path.join(MIGRATIONS_DIR, filename);

  const sql = buildSql(call);
  writeFileSync(filepath, sql, 'utf-8');

  return filepath;
}
