import { type BadgeVariant } from '@/shared/components';

export const WEAVING_INVOICE_MESSAGES = {
  PAGE_TITLE: 'Hóa đơn dệt',
  PAGE_SUBTITLE: 'Quản lý hóa đơn dệt, thanh toán và nhập kho vải mộc.',
  BTN_CREATE: 'Tạo phiếu',
  KPI_TOTAL_TITLE: 'Tổng phiếu gia công',
  KPI_TOTAL_SUB: 'Tất cả phiếu nhập kho dệt',
  KPI_DRAFT_TITLE: 'Chờ xác nhận',
  KPI_DRAFT_SUB: 'Phiếu nháp chưa nhập kho',
  FILTER_SEARCH_LABEL: 'Tìm kiếm',
  FILTER_SEARCH_PLACEHOLDER: 'Số phiếu gia công...',
  FILTER_STATUS_LABEL: 'Trạng thái',
  EMPTY_STATE_FILTER_TITLE: 'Không tìm thấy phiếu gia công',
  EMPTY_STATE_FILTER_DESC: 'Thử điều chỉnh bộ lọc.',
  EMPTY_STATE_TITLE: 'Chưa có phiếu gia công nào',
  EMPTY_STATE_DESC: 'Nhấn "+ Tạo phiếu" để bắt đầu nhập cuộn vải từ nhà dệt.',
  COL_INVOICE: 'Số phiếu',
  COL_SUPPLIER: 'Nhà dệt',
  COL_FABRIC: 'Loại vải',
  COL_WEIGHT: 'Tổng KG',
  COL_AMOUNT: 'Thành tiền',
  COL_PAID: 'Đã trả',
  COL_STATUS: 'Trạng thái',
  COL_ACTIONS: 'Thao tác',
  BTN_EDIT: 'Sửa',
  BTN_CONFIRM: 'Xác nhận & nhập kho',
  BTN_DELETE: 'Xóa',
  BTN_LOOKUP: 'Tra cứu QR & in hóa đơn',
  ERR_LOAD: 'Lỗi tải dữ liệu:',
  ERR_CONFIRM: 'Lỗi xác nhận phiếu. ',
  ERR_DELETE: 'Lỗi xóa phiếu. ',
  ERR_TITLE: 'Lỗi',
  BTN_CLOSE: 'Đóng',
  CONFIRM_MSG: (no: string, count: number) =>
    `Xác nhận phiếu "${no}"? Hệ thống sẽ tự động nhập ${count} cuộn vào kho vải mộc.`,
  CONFIRM_SUCCESS: 'Nhập kho thành công',
  DELETE_MSG: (no: string) => `Xóa phiếu nháp "${no}"?`,
  DELETE_SUCCESS: 'Xóa phiếu thành công',
  STATUS_DRAFT: 'Nháp',
  STATUS_CONFIRMED: 'Đã xác nhận',
  STATUS_PAID: 'Đã thanh toán',
  UNSAVED_WARNING: 'Bạn có thông tin chưa lưu. Bạn có chắc chắn muốn đóng?',
  LOADING_INVOICE: 'Đang tải dữ liệu phiếu...',

  // WeavingInvoiceForm
  FORM_EDIT_TITLE: 'Sửa phiếu gia công',
  FORM_CREATE_TITLE: 'Tạo phiếu gia công',
  SECTION_INFO: 'Thông tin phiếu gia công',
  LABEL_INVOICE_NO: 'Số phiếu',
  LABEL_SUPPLIER: 'Nhà dệt',
  PLACEHOLDER_SUPPLIER: 'Chọn nhà dệt...',
  LABEL_DATE: 'Ngày',
  LABEL_WORK_ORDER: 'Lệnh dệt',
  PLACEHOLDER_WORK_ORDER: 'Chọn lệnh dệt...',
  PLACEHOLDER_WORK_ORDER_DISABLED: 'Chọn nhà dệt trước...',
  LABEL_FABRIC: 'Loại vải',
  PLACEHOLDER_FABRIC: 'Chọn loại vải...',
  LABEL_UNIT_PRICE: 'Đơn giá gia công (VNĐ/kg)',
  LABEL_TOTAL_WEIGHT: 'Tổng khối lượng:',
  LABEL_TOTAL_AMOUNT: 'Tổng tiền công:',
  BTN_IMPORT_ROLLS: 'Nhập từ Excel/Scanner',
  BTN_GENERATE_ROLLS: 'Tạo nhanh N cuộn',
  SECTION_ROLL_LIST: 'Chi tiết cuộn vải mộc',
  HINT_ROLL_LIST:
    'Sử dụng phím mũi tên Lên/Xuống để di chuyển nhanh giữa các dòng. Enter ở dòng cuối để thêm dòng mới.',
  COL_ROLL_ID: 'STT / Mã cuộn (Auto)',
  COL_WEIGHT_KG: 'Khối lượng (kg)',
  COL_LENGTH_M: 'Chiều dài (m)',
  COL_LOT: 'Số lô (Lot)',
  BTN_SUBMIT_UPDATE: 'Cập nhật',
  BTN_SUBMIT_CREATE: 'Lưu nháp',
  BTN_ADD_ROLL: '+ Thêm 1 cuộn',
  ERR_ROLLS_INVALID:
    // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
    '⚠️ Không thể lưu: Tồn tại {count} cuộn bị lỗi dữ liệu (chưa điền KG hoặc sai mã). Hãy điền đủ hoặc Xóa cuộn dư.',
  PLACEHOLDER_FABRIC_INPUT: 'Chọn hoặc nhập loại vải...',
  LABEL_NOTES: 'Ghi chú',
};

export function getStatusVariant(status: string): BadgeVariant {
  if (status === 'confirmed') return 'success';
  if (status === 'paid') return 'info';
  return 'gray';
}
