export const REPORT_LABELS = {
  PAGE_TITLE: 'Báo cáo CEO',
  PAGE_DESC: 'Phân tích hoạt động kinh doanh đa chiều theo thời gian cụ thể',
  TAB_OVERVIEW: 'Tổng quan CEO',
  TAB_REVENUE: 'Doanh thu',
  TAB_DEBT: 'Công nợ',
  TAB_PRODUCTION: 'Sản xuất',
  TAB_INVENTORY: 'Tồn kho',

  // DebtSection
  DEBT_SECTION_TITLE: 'Dư nợ khách hàng',
  TOTAL_DEBT: 'Tổng công nợ',
  CUSTOMER_OWE: 'Khách còn nợ',
  COL_CUSTOMER: 'Khách hàng',
  COL_CUSTOMER_CODE: 'Mã KH',
  COL_TOTAL_ORDERS: 'Số đơn',
  COL_TOTAL_AMOUNT: 'Tổng tiền',
  COL_PAID_AMOUNT: 'Đã thu',
  COL_BALANCE_DUE: 'Còn nợ',
  TOTAL: 'Tổng',
  // InventorySection
  INVENTORY_SECTION_TITLE: 'Cơ cấu kho hiện tại',
  RAW_ROLLS: 'Cuộn mộc',
  RAW_LENGTH: 'Mét mộc',
  FINISH_ROLLS: 'Cuộn TP',
  FINISH_LENGTH: 'Mét TP',
  RAW_FABRIC_TITLE: 'Vải mộc',
  RAW_FABRIC_EYEBROW: 'RAW FABRIC',
  FINISH_FABRIC_TITLE: 'Vải thành phẩm',
  FINISH_FABRIC_EYEBROW: 'FINISHED FABRIC',
  COL_FABRIC_TYPE: 'Loại vải',
  COL_COLOR: 'Màu',
  COL_QUALITY_GRADE: 'Phân loại',
  COL_ROLL_COUNT: 'Cuộn',
  COL_LENGTH_M: 'Mét',
  COL_WEIGHT_KG: 'Kg',
  // OverdueSection
  OVERDUE_SECTION_TITLE: 'Đơn hàng trễ hạn',
  OVERDUE_TOTAL_ORDERS: 'Tổng đơn trễ',
  OVERDUE_SEVERE: 'Trễ > 7 ngày',
  OVERDUE_TOTAL_DEBT: 'Tổng nợ trễ',
  OVERDUE_EMPTY_TITLE: 'Tuyệt vời! Không có đơn trễ hạn.',
  OVERDUE_EMPTY_DESC:
    'Tất cả các đơn hàng đều đang trong tiến độ giao hàng đúng hạn.',
  COL_ORDER: 'Đơn hàng',
  COL_DELIVERY_DATE: 'Hạn giao',
  COL_LATE: 'Trễ',
  DAYS: 'ngày',
  DEBT_LABEL: 'Nợ:',
  // ProductionSection
  PRODUCTION_SECTION_TITLE: 'Sản xuất & Giao hàng',
  PROD_ON_TIME: 'Giao đúng hạn',
  PROD_AVG_LATE: 'TB trễ (ngày)',
  PROD_WEAK_LINK: 'Mắc xích yếu',
  PROD_LATE_PCT: 'đơn bị trễ',
  PROD_TRACKED: 'Đơn theo dõi',
  COL_STAGE: 'Công đoạn',
  COL_ORDERS: 'Đơn',
  COL_ON_TIME: 'Đúng hạn',
  COL_LATE_PCT: '% Trễ',
  TOTAL_ORDERS: 'Tổng đơn',
  LATE_ORDERS: 'Trễ hạn',
  // RevenueSection
  REVENUE_SECTION_TITLE: 'Phân tích dòng tiền',
  REV_TOTAL: 'Tổng doanh thu',
  REV_PAID: 'Đã thu',
  REV_BALANCE: 'Còn nợ',
  REV_ORDER_COUNT: 'Số đơn hàng',
  COL_ORDER_DATE: 'Ngày đặt',
  // RevenueTrendSection
  TREND_SECTION_TITLE: 'Doanh thu & Thu tiền',
  TREND_RECOVERY_RATE: 'tỷ lệ thu hồi',
  TREND_GROWTH: 'Tăng trưởng',
  TREND_RECEIVABLE: 'Phải thu',
  TREND_MONTHLY_CHART: 'Doanh thu theo tháng',
  TREND_FABRIC_CHART: 'Cơ cấu loại vải (Top 10)',
  TREND_COLLECTION_EYEBROW: 'THU TIỀN',
  TREND_COLLECTION_TITLE: 'Phân bổ phương thức thanh toán',
  PAYMENT_METHOD_LABELS: {
    bank_transfer: 'Chuyển khoản',
    cash: 'Tiền mặt',
    card: 'Quẹt thẻ',
    debt: 'Ghi nợ',
  } as Record<string, string>,
  // Filter
  FILTER_FROM_DATE: 'Từ ngày',
  FILTER_TO_DATE: 'Đến ngày',
  FILTER_APPLY: 'Áp dụng',
  FILTER_RESET: 'Đặt lại',
} as const;
