-- Generated by rpc-sync at 2026-04-23T10:29:28.217Z
-- Source: D:/VinhPhatERP_v3/src/api/dyeing-orders.api.ts:117
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_create_dyeing_order(
  p_header               numeric,
  p_items                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_create_dyeing_orders
  NULL;

$$;
