-- Generated by rpc-sync at 2026-04-23T10:29:28.268Z
-- Source: D:/VinhPhatERP_v3/src/api/payments.api.ts:287
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_get_expense_by_category(
  p_from                 text,
  p_to                   text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_get_expense_by_categorys
  NULL;

$$;
