-- Generated by rpc-sync at 2026-04-23T10:29:28.296Z
-- Source: D:/VinhPhatERP_v3/src/api/work-orders.api.ts:342
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_update_work_order(
  p_wo_id                uuid,
  p_wo_data              jsonb,
  p_reqs_data            jsonb
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_update_work_orders
  NULL;

$$;
