-- Generated by rpc-sync at 2026-04-23T10:29:28.271Z
-- Source: D:/VinhPhatERP_v3/src/api/shipments.api.ts:409
-- Operation inferred: INSERT

CREATE OR REPLACE FUNCTION public.create_shipment_from_finished_fabric(
  p_customer_id          uuid,
  p_roll_ids             text,
  p_shipment_date        timestamptz
)
RETURNS void
LANGUAGE sql
AS $$
  INSERT INTO public.shipment_from_finished_fabrics (customer_id, roll_ids, shipment_date)
  VALUES (p_customer_id, p_roll_ids, p_shipment_date);

$$;
