-- Generated by rpc-sync at 2026-04-23T10:29:28.304Z
-- Source: D:/VinhPhatERP_v3/src/api/helpers/next-doc-number.ts:23
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_generate_next_doc_number(
  p_table                text,
  p_column               text,
  p_prefix               text,
  p_pad                  numeric
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_generate_next_doc_numbers
  NULL;

$$;
