-- Generated by rpc-sync at 2026-04-23T10:29:28.301Z
-- Source: D:/VinhPhatERP_v3/src/api/work-orders.api.ts:417
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_complete_work_order(
  p_wo_id                uuid,
  p_yield_m              numeric,
  p_today                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_complete_work_orders
  NULL;

$$;
