-- Generated by rpc-sync at 2026-04-23T10:29:28.238Z
-- Source: D:/VinhPhatERP_v3/src/api/dyeing-orders.api.ts:184
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_complete_dyeing_order(
  p_dyeing_order_id      uuid,
  p_actual_return_date   timestamptz
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_complete_dyeing_orders
  NULL;

$$;
