-- Generated by rpc-sync at 2026-04-23T10:29:28.269Z
-- Source: D:/VinhPhatERP_v3/src/api/quotations.api.ts:137
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_update_quotation(
  p_quotation_id         uuid,
  p_header               text,
  p_items                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_update_quotations
  NULL;

$$;
