-- Generated by rpc-sync at 2026-04-23T10:29:28.238Z
-- Source: D:/VinhPhatERP_v3/src/api/orders.api.ts:135
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_create_order(
  p_header               text,
  p_items                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_create_orders
  NULL;

$$;
