-- Generated by rpc-sync at 2026-04-23T10:29:28.294Z
-- Source: D:/VinhPhatERP_v3/src/api/weaving-invoices.api.ts:266
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_update_weaving_invoice(
  p_id                   uuid,
  p_header               numeric,
  p_rolls                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_update_weaving_invoices
  NULL;

$$;
