-- Generated by rpc-sync at 2026-04-23T10:29:28.270Z
-- Source: D:/VinhPhatERP_v3/src/api/shipments.api.ts:266
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_create_shipment(
  p_header               numeric,
  p_items                numeric,
  p_reserve_roll_ids     text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_create_shipments
  NULL;

$$;
