-- Generated by rpc-sync at 2026-04-23T10:29:28.281Z
-- Source: D:/VinhPhatERP_v3/src/api/suppliers.api.ts:161
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_update_supplier(
  p_id                   uuid
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_update_suppliers
  NULL;

$$;
