-- Generated by rpc-sync at 2026-04-23T10:29:28.214Z
-- Source: D:/VinhPhatERP_v3/src/api/driver-portal.api.ts:81
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_update_shipment_journey(
  p_shipment_id          uuid,
  p_journey_status       text,
  p_notes                text,
  p_updated_by           text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_update_shipment_journeys
  NULL;

$$;
