-- Generated by rpc-sync at 2026-06-24T11:15:44.038Z
-- Source: D:/VinhPhatERP_v3/src/api/fabric-catalog.api.ts:297
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_create_public_sample_request(
  p_fabric_catalog_id    uuid,
  p_contact_name         text,
  p_contact_phone        text,
  p_contact_address      text,
  p_company_name         text,
  p_selected_variants    text,
  p_sample_items         text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_create_public_sample_requests
  NULL;

$$;
