-- Generated by rpc-sync at 2026-04-23T10:29:28.188Z
-- Source: D:/VinhPhatERP_v3/src/api/bom.api.ts:268
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_update_bom(
  p_bom_id               uuid,
  p_header               text,
  p_items                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_update_boms
  NULL;

$$;
