-- Generated by rpc-sync at 2026-04-23T10:29:28.302Z
-- Source: D:/VinhPhatERP_v3/src/api/yarn-receipts.api.ts:172
-- Operation inferred: UNKNOWN

CREATE OR REPLACE FUNCTION public.rpc_create_yarn_receipt(
  p_header               text,
  p_items                text
)
RETURNS void
LANGUAGE sql
AS $$
  -- TODO: implement function body
  -- Table: public.rpc_create_yarn_receipts
  NULL;

$$;
