export const QUOTATION_LABELS = {
  PAGE_TITLE: 'Báo giá',
  PAGE_SUBTITLE: 'Quản lý các báo giá và đề xuất bán hàng',
  NEW_QUOTATION: 'Tạo báo giá',
  EDIT_QUOTATION: 'Sửa báo giá',
  QUOTATION_NUMBER: 'Số báo giá',
  QUOTATION_DATE: 'Ngày báo giá',
  CUSTOMER: 'Khách hàng',
  VALID_UNTIL: 'Hiệu lực đến',
  STATUS: 'Trạng thái',
  SUBTOTAL: 'Tạm tính',
  DISCOUNT: 'Chiết khấu',
  DISCOUNT_TYPE: 'Loại chiết khấu',
  DISCOUNT_VALUE: 'Giá trị chiết khấu',
  BEFORE_VAT: 'Trước VAT',
  VAT_RATE: 'Thuế VAT',
  VAT_AMOUNT: 'Tiền VAT',
  TOTAL: 'Tổng cộng',
  TERMS: 'Điều khoản',
  DELIVERY_TERMS: 'Điều kiện giao hàng',
  PAYMENT_TERMS: 'Điều kiện thanh toán',
  NOTES: 'Ghi chú',
  NOTES_LINE: 'Ghi chú dòng',

  // Items
  LINE_ITEMS: 'Dòng hàng',
  ADD_ITEM: 'Thêm dòng hàng',
  FABRIC_TYPE: 'Loại vải',
  COLOR: 'Màu',
  COLOR_CODE: 'Mã màu',
  WIDTH: 'Khổ vải (cm)',
  UNIT: 'Đơn vị',
  QUANTITY: 'Số lượng',
  UNIT_PRICE: 'Đơn giá',
  LEAD_TIME: 'Thời gian SX (ngày)',
  LEAD_TIME_SHORT: 'SX (ngày)',
  LINE: 'Dòng',
  AMOUNT: 'Thành tiền',
  FIXED_DISCOUNT: 'cố định',

  // Actions
  BTN_SAVE: 'Tạo báo giá',
  BTN_UPDATE: 'Cập nhật',
  BTN_PRINT: 'In báo giá',
  BTN_SEND: 'Gửi khách hàng',
  BTN_APPROVE: 'Duyệt báo giá',
  BTN_REJECT: 'Từ chối',
  BTN_CANCEL: 'Hủy báo giá',
  BTN_DELETE: 'Xóa',
  BTN_EDIT: 'Sửa',
  BTN_CUSTOMER_APPROVE: 'Khách duyệt',
  BTN_CUSTOMER_REJECT: 'Khách từ chối',
  BTN_EDIT_AGAIN: 'Sửa đổi',
  BTN_CONVERT_ORDER: 'Chuyển thành Đơn hàng',
  BTN_VIEW_ORDER: 'Xem Đơn hàng',

  // Tooltips
  PRINT_TOOLTIP: 'In Báo giá hoặc lưu PDF',

  // Statuses
  STATUS_DRAFT: 'Nháp',
  STATUS_SENT: 'Đã gửi',
  STATUS_APPROVED: 'Đã duyệt',
  STATUS_REJECTED: 'Đã từ chối',
  STATUS_EXPIRED: 'Hết hạn',
} as const;

export const QUOTATION_MESSAGES = {
  SAVE_SUCCESS: 'Đã lưu báo giá thành công',
  SAVE_ERROR: 'Lỗi khi lưu báo giá',
  DELETE_SUCCESS: 'Đã xóa báo giá',
  DELETE_ERROR: 'Lỗi khi xóa báo giá',
  DELETE_CONFIRM_TITLE: 'Xóa báo giá này?',
  DELETE_CONFIRM_DESC:
    'Bạn có chắc chắn muốn xóa báo giá này không? Hành động này không thể hoàn tác.',
  APPROVE_SUCCESS: 'Đã duyệt báo giá',
  REJECT_SUCCESS: 'Đã từ chối báo giá',
  STATUS_UPDATE_ERROR: 'Lỗi khi cập nhật trạng thái',
  NO_DATA: 'Chưa có báo giá nào',
  LOADING: 'Đang tải...',
  CONFIRM_SEND: 'Gửi báo giá này cho khách hàng?',
  CONFIRM_APPROVE: 'Xác nhận khách hàng đã duyệt báo giá này?',
  CONFIRM_REJECT: 'Khách hàng từ chối báo giá này?',
  CONFIRM_CONVERT:
    'Chuyển báo giá này thành đơn hàng? Hệ thống sẽ tạo đơn hàng mới ở trạng thái Nháp.',
  BTN_BACK: 'Quay lại',
  SENDING: 'Đang gửi...',
  PROCESSING: 'Đang xử lý...',
  CONVERTING: 'Đang chuyển...',
  ERROR_PREFIX: 'Lỗi:',
  EMPTY_ITEMS: 'Chưa có dòng hàng.',
} as const;

export const QUOTATION_PLACEHOLDERS = {
  AUTO_NUMBER: 'Tự động',
  SELECT_CUSTOMER: '— Chọn khách hàng —',
  FABRIC_TYPE: 'Chọn hoặc nhập loại vải',
  COLOR: 'Chọn hoặc nhập màu...',
  COLOR_CODE: 'VD: TC-01',
  WIDTH: '150',
  DELIVERY_TERMS: 'VD: Giao tại kho khách...',
  PAYMENT_TERMS: 'VD: Thanh toán 50% trước...',
  NOTES: 'Ghi chú về báo giá...',
  NOTES_LINE: 'Ghi chú...',
  SEARCH: 'Tìm theo số báo giá hoặc tên khách hàng...',
} as const;
