export const RAW_FABRIC_MESSAGES = {
  PAGE_TITLE: 'Kho Mộc',
  PAGE_SUBTITLE: 'Quản lý tồn kho vải mộc',

  BTN_NEW: 'Nhập kho',
  BTN_BULK_NEW: 'Nhập lô',
  BTN_EXPORT: 'Xuất Excel',

  STAT_TOTAL_ROLLS: 'Tổng số cuộn',
  STAT_TOTAL_ROLLS_DESC: 'Cuộn đang trong kho',
  STAT_TOTAL_LENGTH: 'Tổng chiều dài',
  STAT_TOTAL_LENGTH_DESC: 'Cuộn đang trong kho',
  STAT_TOTAL_WEIGHT: 'Trọng lượng tịnh',
  STAT_TOTAL_WEIGHT_DESC: 'Trọng lượng tịnh thực tế',

  EMPTY_STATE_FILTER_TITLE: 'Không tìm thấy cuộn vải phù hợp',
  EMPTY_STATE_DEFAULT_TITLE: 'Chưa có cuộn vải nào',
  EMPTY_STATE_FILTER_DESC: 'Không tìm thấy cuộn vải phù hợp.',
  EMPTY_STATE_DEFAULT_DESC: 'Chưa có cuộn vải nào.',

  COL_ROLL_NUMBER: 'Mã cuộn',
  COL_LOT_NUMBER: 'Số lô',
  COL_FABRIC_TYPE: 'Loại vải / Màu',
  COL_WEIGHT: 'Khối lượng',
  COL_LENGTH: 'Chiều dài',
  COL_STATUS: 'Trạng thái',
  COL_ACTIONS: 'Thao tác',

  LBL_LOT: 'Lô:',
  LBL_NO_LOT: 'KHÔNG CÓ LÔ',
  LBL_CLEAR_FILTER: 'Xóa bộ lọc',
  BTN_EDIT_TITLE: 'Chỉnh sửa',

  ERR_LOAD: 'Lỗi tải dữ liệu:',
  ERR_EXPORT: 'Lỗi xuất Excel:',

  // FORM MESSAGES & LABELS
  FORM_TITLE_EDIT: 'Sửa cuộn:',
  FORM_TITLE_NEW: 'Nhập cuộn vải mộc mới',
  ERR_UNSAVED: 'Bạn có thông tin chưa lưu. Bạn có chắc chắn muốn đóng?',
  LBL_LOT_NUMBER: 'Số lô (Lot number)',
  LBL_LOT_AUTO_HINT:
    'Tự động tạo từ Lệnh sản xuất + Nhà dệt + Phiếu sợi + Ngày dệt.',
  LBL_LOT_MANUAL_HINT: 'Nhóm các cuộn cùng lô sản xuất.',
  LBL_ROLL_NUMBER: 'Mã cuộn',
  LBL_FABRIC_TYPE: 'Loại vải',
  LBL_COLOR_NAME: 'Màu vải',
  LBL_COLOR_CODE: 'Mã màu',
  LBL_WIDTH_CM: 'Khổ vải (cm)',
  LBL_LENGTH_M: 'Độ dài (m)',
  LBL_WEIGHT_KG: 'Trọng lượng (kg)',
  LBL_PRODUCTION_DATE: 'Ngày dệt',
  LBL_QUALITY_GRADE: 'Chất lượng',
  LBL_STATUS: 'Trạng thái',
  LBL_WAREHOUSE_LOCATION: 'Vị trí kho',
  LBL_NOTES: 'Ghi chú',
  LBL_WORK_ORDER: 'Lệnh sản xuất (Work Order)',
  HINT_WORK_ORDER: 'Liên kết cuộn này với lệnh sản xuất để theo dõi tiến độ.',
  LBL_WEAVING_PARTNER: 'Nhà dệt gia công',
  BTN_NEW_PARTNER: '+ Tạo nhà dệt mới',
  LBL_YARN_RECEIPT: 'Phiếu nhập sợi nguồn',
  HINT_YARN_RECEIPT: 'Chỉ định sợi nguồn dùng để dệt nên cuộn mộc này.',
  BTN_SAVE_EDIT: 'Lưu thay đổi',
  BTN_SAVE_NEW: 'Nhập kho',
  ERR_PREFIX: 'Lỗi:',
  LBL_UNVERIFIED: 'Chưa kiểm định',
  VAL_NO_WO: '— Không liên kết lệnh (Dự trữ) —',
  VAL_CHOOSE_WEAVER: '— Chọn nhà dệt —',
  VAL_CHOOSE_YARN: '— Chọn phiếu sợi —',
  PLACEHOLDER_COLOR: 'Chọn hoặc nhập màu...',
};
