import { zodResolver } from '@hookform/resolvers/zod';
import { useCallback, useEffect, useState } from 'react';
import { useFieldArray, useForm, useWatch, Controller } from 'react-hook-form';

import { useFabricCatalogOptions } from '@/shared/hooks/useFabricCatalogOptions';
import { AdaptiveSheet } from '@/shared/components/AdaptiveSheet';
import { Combobox } from '@/shared/components/Combobox';
import {
  useColorOptions,
  toColorComboboxOptions,
} from '@/shared/hooks/useColorOptions';
import { useStepper } from '@/shared/hooks/useStepper';
import { LotMatrixCard } from '@/shared/components/roll-grid';
import type { RollMatrixItem } from '@/shared/components/roll-grid';

import {
  QUALITY_GRADE_LABELS,
  QUALITY_GRADES,
  ROLL_STATUS_LABELS,
  ROLL_STATUSES,
  bulkInputDefaults,
  bulkInputSchema,
  formatBulkRollNumber,
} from './raw-fabric.module';
import type { BulkInputFormValues } from './raw-fabric.module';
import type { RawFabricRoll } from './types';
import {
  useCreateRawFabricBulk,
  useWeavingPartners,
  useWorkOrderOptions,
  useYarnReceiptOptions,
} from './useRawFabric';
import { useRawFabricExport } from './useRawFabricExport';

type Props = {
  onClose: () => void;
};

export function RawFabricBulkForm({ onClose }: Props) {
  const bulkMutation = useCreateRawFabricBulk();
  const { data: weavingPartners = [] } = useWeavingPartners();
  const { data: yarnReceipts = [] } = useYarnReceiptOptions();
  const { data: workOrders = [] } = useWorkOrderOptions();
  const { data: colorOptions = [] } = useColorOptions();
  const { data: fabricCatalogOptions = [] } = useFabricCatalogOptions();
  const [savedRolls, setSavedRolls] = useState<RawFabricRoll[] | null>(null);
  const { exportExcel, exportPdf } = useRawFabricExport();

  const stepper = useStepper({ totalSteps: 2 });

  const {
    register,
    handleSubmit,
    control,
    setValue,
    trigger,
    formState: { errors, isValid, isSubmitting },
  } = useForm<BulkInputFormValues>({
    resolver: zodResolver(bulkInputSchema),
    defaultValues: bulkInputDefaults,
    mode: 'onTouched',
  });

  const { fields, append } = useFieldArray({
    control,
    name: 'rolls',
  });

  const rollPrefix = useWatch({
    control,
    name: 'roll_prefix',
  });
  const startNumber = useWatch({
    control,
    name: 'start_number',
  });
  const expectedRolls = useWatch({
    control,
    name: 'expected_rolls',
  });
  const rolls = useWatch({
    control,
    name: 'rolls',
  });

  // Auto-generate roll numbers khi prefix hoặc start_number thay đổi
  useEffect(() => {
    const prefix = rollPrefix?.trim() || bulkInputDefaults.roll_prefix;
    const start =
      typeof startNumber === 'number'
        ? startNumber
        : bulkInputDefaults.start_number;
    fields.forEach((_, idx) => {
      setValue(
        `rolls.${idx}.roll_number`,
        formatBulkRollNumber(prefix, start + idx),
      );
    });
  }, [rollPrefix, startNumber, fields.length, setValue, fields]);

  // Sinh tự động Lot number từ Lệnh SX, Nhà dệt, Phiếu sợi
  const workOrderId = useWatch({
    control,
    name: 'work_order_id',
  });
  const weavingPartnerId = useWatch({
    control,
    name: 'weaving_partner_id',
  });
  const yarnReceiptId = useWatch({
    control,
    name: 'yarn_receipt_id',
  });
  const productionDate = useWatch({
    control,
    name: 'production_date',
  });
  const manualLotNumber = useWatch({
    control,
    name: 'lot_number',
  });

  useEffect(() => {
    if (workOrderId && weavingPartnerId && yarnReceiptId) {
      const wo = workOrders.find((w) => w.id === workOrderId);
      const wp = weavingPartners.find((w) => w.id === weavingPartnerId);
      const yr = yarnReceipts.find((r) => r.id === yarnReceiptId);

      if (wo && wp && yr) {
        let datePart = '';
        if (productionDate) {
          datePart = productionDate.replace(/-/g, '');
        } else {
          datePart = new Date()
            .toISOString()
            .substring(0, 10)
            .replace(/-/g, '');
        }

        const wpCode = wp.code || wp.name.substring(0, 3).toUpperCase();
        const autoLot = `${wo.work_order_number}-${wpCode}-${yr.receipt_number}-${datePart}`;

        if (manualLotNumber !== autoLot) {
          setValue('lot_number', autoLot, {
            shouldValidate: true,
            shouldDirty: true,
          });
        }
      }
    }
  }, [
    workOrderId,
    weavingPartnerId,
    yarnReceiptId,
    productionDate,
    manualLotNumber,
    workOrders,
    weavingPartners,
    yarnReceipts,
    setValue,
  ]);

  // Sinh tiền tố cuộn (RM) tự động từ Lot Number
  useEffect(() => {
    if (manualLotNumber) {
      const autoPrefix = `RM-${manualLotNumber}-`;
      if (rollPrefix !== autoPrefix) {
        setValue('roll_prefix', autoPrefix, {
          shouldValidate: true,
          shouldDirty: true,
        });
      }
    }
  }, [manualLotNumber, rollPrefix, setValue]);

  const isLotAutoGenerated = !!(
    workOrderId &&
    weavingPartnerId &&
    yarnReceiptId
  );
  const isPrefixAutoGenerated = !!manualLotNumber;

  /** Thêm 1 cuộn mới vào cuối grid */
  const addRow = useCallback(() => {
    const prefix = rollPrefix?.trim() || bulkInputDefaults.roll_prefix;
    const start =
      typeof startNumber === 'number'
        ? startNumber
        : bulkInputDefaults.start_number;
    append({
      roll_number: formatBulkRollNumber(prefix, start + fields.length),
      weight_kg: undefined as unknown as number,
      length_m: undefined,
      quality_grade: undefined,
      notes: '',
    });
  }, [append, rollPrefix, startNumber, fields.length]);

  /** Embed rolls array as RollMatrixItem[] for LotMatrixCard */
  const gridRolls: RollMatrixItem[] = fields.map((field, idx) => ({
    id: field.id,
    roll_number: rolls?.[idx]?.roll_number ?? '',
    weight_kg: rolls?.[idx]?.weight_kg,
  }));

  // Tổng hợp — chỉ đếm dòng có nhập trọng lượng > 0
  const filledRolls = (rolls ?? []).filter((r) => {
    const val = parseFloat(String(r.weight_kg));
    return Number.isFinite(val) && val > 0;
  });
  const totalRolls = filledRolls.length;

  async function handleNextStep() {
    if (stepper.currentStep === 0) {
      const stepValid = await trigger([
        'fabric_type',
        'width_cm',
        'roll_prefix',
        'start_number',
      ]);
      if (!stepValid) return;

      // Auto-populate grid dựa trên expected_rolls
      const target = typeof expectedRolls === 'number' ? expectedRolls : 1;
      const prefix = rollPrefix?.trim() || bulkInputDefaults.roll_prefix;
      const start =
        typeof startNumber === 'number'
          ? startNumber
          : bulkInputDefaults.start_number;
      const missing = target - fields.length;
      if (missing > 0) {
        const newRows = Array.from({ length: missing }, (_, i) => ({
          roll_number: formatBulkRollNumber(prefix, start + fields.length + i),
          weight_kg: undefined as unknown as number,
          length_m: undefined,
          quality_grade: undefined,
          notes: '',
        }));
        append(newRows);
      }

      stepper.next();
    }
  }

  async function onSubmit(values: BulkInputFormValues) {
    if (!stepper.isLast) return;
    const saved = await bulkMutation.mutateAsync(values);
    setSavedRolls(saved);
  }

  const isPending = isSubmitting || bulkMutation.isPending;

  return (
    <AdaptiveSheet
      open={true}
      onClose={onClose}
      title="Nhập nhanh cuộn vải mộc"
      stepInfo={
        savedRolls
          ? undefined
          : {
              current: stepper.currentStep,
              total: stepper.totalSteps,
            }
      }
      maxWidth={960}
    >
      {/* ===== SUCCESS STATE ===== */}
      {savedRolls !== null ? (
        <div className="bulk-success">
          <div className="bulk-success-icon">✓</div>
          <p className="bulk-success-title">Nhập kho thành công</p>
          <p className="bulk-success-sub">
            Đã lưu <strong>{savedRolls.length} cuộn</strong> ·{' '}
            <strong>
              {savedRolls
                .reduce((sum, r) => sum + (r.weight_kg ?? 0), 0)
                .toLocaleString('vi-VN', { maximumFractionDigits: 2 })}{' '}
              kg
            </strong>
          </p>
          <p className="bulk-success-hint">
            Tùy chọn: xuất danh sách vừa nhập ra file
          </p>
          <div className="bulk-success-actions">
            <button
              className="btn-secondary"
              type="button"
              onClick={() => exportExcel(savedRolls, 'bien_ban_nhap_kho')}
            >
              📊 Xuất Excel
            </button>
            <button
              className="btn-secondary"
              type="button"
              onClick={() => exportPdf(savedRolls, 'bien_ban_nhap_kho')}
            >
              🖨 Xuất PDF
            </button>
            <button
              className="primary-button btn-standard"
              type="button"
              onClick={onClose}
            >
              Đóng
            </button>
          </div>
        </div>
      ) : (
        <>
          {bulkMutation.error && (
            <p className="error-inline" style={{ marginBottom: '1rem' }}>
              Lỗi: {(bulkMutation.error as Error).message}
            </p>
          )}

          <form
            id="raw-fabric-bulk-form"
            onSubmit={handleSubmit(onSubmit)}
            noValidate
          >
            {/* ── BƯỚC 1: CẤU HÌNH NHẬP & NHẢY MÃ ── */}
            <div
              style={{ display: stepper.currentStep === 0 ? 'block' : 'none' }}
            >
              <fieldset className="bulk-section">
                <legend>Thông tin đồng loạt</legend>

                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label>
                      Loại vải <span className="field-required">*</span>
                    </label>
                    <Controller
                      control={control}
                      name="fabric_type"
                      render={({ field }) => (
                        <Combobox
                          options={fabricCatalogOptions.map((c) => ({
                            label: c.name,
                            value: c.name,
                            code: c.code,
                          }))}
                          value={field.value || ''}
                          onChange={field.onChange}
                          onBlur={field.onBlur}
                          placeholder="Chọn hoặc nhập loại vải..."
                          hasError={!!errors.fabric_type}
                          allowInput
                        />
                      )}
                    />
                    {errors.fabric_type && (
                      <span className="field-error">
                        {errors.fabric_type.message}
                      </span>
                    )}
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_warehouse_location">Vị trí kho</label>
                    <input
                      id="bulk_warehouse_location"
                      className="field-input"
                      type="text"
                      placeholder="VD: A1-R3-S2"
                      {...register('warehouse_location')}
                    />
                  </div>
                </div>

                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label htmlFor="bulk_color_name">Màu vải</label>
                    <Controller
                      name="color_name"
                      control={control}
                      render={({ field }) => (
                        <Combobox
                          options={toColorComboboxOptions(colorOptions)}
                          value={field.value ?? ''}
                          onChange={field.onChange}
                          placeholder="Chọn hoặc nhập màu..."
                        />
                      )}
                    />
                  </div>
                  <div className="form-field">
                    <label htmlFor="bulk_color_code">Mã màu</label>
                    <input
                      id="bulk_color_code"
                      className="field-input"
                      type="text"
                      placeholder="VD: TC-01"
                      {...register('color_code')}
                    />
                  </div>
                </div>

                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label htmlFor="bulk_width_cm">Khổ vải (cm)</label>
                    <input
                      id="bulk_width_cm"
                      className={`field-input${errors.width_cm ? ' is-error' : ''}`}
                      type="number"
                      step="0.01"
                      min="0"
                      placeholder="VD: 150"
                      {...register('width_cm')}
                    />
                    {errors.width_cm && (
                      <span className="field-error">
                        {errors.width_cm.message}
                      </span>
                    )}
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_quality_grade">
                      Chất lượng mặc định
                    </label>
                    <Controller
                      name="quality_grade"
                      control={control}
                      render={({ field }) => (
                        <Combobox
                          options={[
                            {
                              value: '',
                              label: 'Chưa kiểm định',
                            },
                            ...QUALITY_GRADES.map((g) => ({
                              value: g,
                              label: QUALITY_GRADE_LABELS[g],
                            })),
                          ]}
                          value={field.value}
                          onChange={field.onChange}
                        />
                      )}
                    />
                  </div>
                </div>

                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label htmlFor="bulk_status">Trạng thái</label>
                    <Controller
                      name="status"
                      control={control}
                      render={({ field }) => (
                        <Combobox
                          options={ROLL_STATUSES.map((s) => ({
                            value: s,
                            label: ROLL_STATUS_LABELS[s],
                          }))}
                          value={field.value}
                          onChange={field.onChange}
                        />
                      )}
                    />
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_production_date">Ngày dệt</label>
                    <input
                      id="bulk_production_date"
                      className="field-input"
                      type="date"
                      {...register('production_date')}
                    />
                  </div>
                </div>

                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label htmlFor="bulk_work_order_id">
                      Lệnh sản xuất (Work Order)
                    </label>
                    <Controller
                      name="work_order_id"
                      control={control}
                      render={({ field }) => (
                        <Combobox
                          options={workOrders.map((wo) => ({
                            value: wo.id,
                            label: `${wo.work_order_number} (${wo.bom_template?.name})`,
                          }))}
                          value={field.value}
                          onChange={field.onChange}
                          placeholder="— Không liên kết lệnh (Dự trữ) —"
                        />
                      )}
                    />
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_weaving_partner_id">
                      Nhà dệt gia công
                    </label>
                    <Controller
                      name="weaving_partner_id"
                      control={control}
                      render={({ field }) => (
                        <Combobox
                          options={weavingPartners.map((s) => ({
                            value: s.id,
                            label: `${s.name} (${s.code})`,
                          }))}
                          value={field.value}
                          onChange={field.onChange}
                          placeholder="— Chọn nhà dệt —"
                        />
                      )}
                    />
                  </div>
                </div>

                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label htmlFor="bulk_yarn_receipt_id">
                      Phiếu nhập sợi nguồn
                    </label>
                    <Controller
                      name="yarn_receipt_id"
                      control={control}
                      render={({ field }) => (
                        <Combobox
                          options={yarnReceipts.map((r) => ({
                            value: r.id,
                            label: `${r.receipt_number} (${r.receipt_date})`,
                          }))}
                          value={field.value}
                          onChange={field.onChange}
                          placeholder="— Chọn phiếu sợi —"
                        />
                      )}
                    />
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_lot_number">Số lô (Lot number)</label>
                    <input
                      id="bulk_lot_number"
                      className="field-input"
                      type="text"
                      placeholder="VD: LOT-2026-001"
                      {...register('lot_number')}
                      disabled={isLotAutoGenerated}
                      style={
                        isLotAutoGenerated
                          ? {
                              background: 'var(--surface-subtle)',
                              cursor: 'not-allowed',
                            }
                          : {}
                      }
                    />
                    {isLotAutoGenerated && (
                      <span
                        className="field-hint"
                        style={{
                          marginTop: '0.25rem',
                          display: 'block',
                        }}
                      >
                        Tự tạo từ Lệnh SX + Nhà dệt + Phiếu sợi.
                      </span>
                    )}
                  </div>
                </div>
              </fieldset>

              <fieldset className="bulk-section">
                <legend>Cấu hình Mã Cuộn & Nhảy số</legend>
                <div
                  className="form-grid"
                  style={{
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                  }}
                >
                  <div className="form-field">
                    <label htmlFor="bulk_roll_prefix">
                      Tiền tố mã cuộn <span className="field-required">*</span>
                    </label>
                    <input
                      id="bulk_roll_prefix"
                      className={`field-input${errors.roll_prefix ? ' is-error' : ''}`}
                      type="text"
                      placeholder="VD: RM-"
                      {...register('roll_prefix')}
                      disabled={isPrefixAutoGenerated}
                      style={
                        isPrefixAutoGenerated
                          ? {
                              background: 'var(--surface-subtle)',
                              cursor: 'not-allowed',
                            }
                          : {}
                      }
                    />
                    {isPrefixAutoGenerated ? (
                      <span className="field-hint">
                        Tự động sinh theo Lot number.
                      </span>
                    ) : errors.roll_prefix ? (
                      <span className="field-error">
                        {errors.roll_prefix.message}
                      </span>
                    ) : null}
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_start_number">Số bắt đầu</label>
                    <input
                      id="bulk_start_number"
                      className={`field-input${errors.start_number ? ' is-error' : ''}`}
                      type="number"
                      min="1"
                      step="1"
                      {...register('start_number')}
                    />
                    {errors.start_number && (
                      <span className="field-error">
                        {errors.start_number.message}
                      </span>
                    )}
                  </div>

                  <div className="form-field">
                    <label htmlFor="bulk_expected_rolls">Số cuộn dự kiến</label>
                    <input
                      id="bulk_expected_rolls"
                      className="field-input"
                      type="number"
                      min="1"
                      max="500"
                      step="1"
                      placeholder="VD: 20"
                      {...register('expected_rolls')}
                    />
                    <span
                      className="field-hint"
                      style={{
                        fontSize: '0.78rem',
                        color: 'var(--muted)',
                        display: 'block',
                        marginTop: '0.25rem',
                      }}
                    >
                      Hệ thống tự tạo sẵn lưới trống theo số lượng này.
                    </span>
                  </div>
                </div>
              </fieldset>
            </div>

            {/* ── BƯỚC 2: LƯỚI NHẬP SỐ TỊNH ── */}
            <div
              style={{ display: stepper.currentStep === 1 ? 'block' : 'none' }}
            >
              <fieldset className="bulk-section">
                <legend>Nhập số tịnh từng cuộn</legend>

                <LotMatrixCard
                  title={`Lô ${rollPrefix ?? 'RM-'} — ${fields.length} cuộn`}
                  rolls={gridRolls}
                  expectedRollsCount={fields.length}
                  mode="input"
                  onRollChange={(index, weight) => {
                    setValue(
                      `rolls.${index}.weight_kg`,
                      (weight ?? undefined) as unknown as number,
                      { shouldValidate: false },
                    );
                  }}
                  onAddRoll={addRow}
                />

                {errors.rolls?.message && (
                  <span
                    className="field-error"
                    style={{
                      marginTop: '0.75rem',
                      display: 'block',
                    }}
                  >
                    {errors.rolls.message}
                  </span>
                )}

                <div
                  style={{
                    display: 'flex',
                    gap: '0.5rem',
                    marginTop: '1rem',
                  }}
                >
                  <button
                    className="btn-secondary"
                    type="button"
                    onClick={addRow}
                  >
                    + 1 cuộn
                  </button>
                  <span
                    style={{
                      alignSelf: 'center',
                      fontSize: '0.78rem',
                      color: 'var(--muted)',
                    }}
                  >
                    Gõ số tịnh → nhấn Enter để chuyển ô tiếp theo
                  </span>
                </div>
              </fieldset>
            </div>

            {/* ===== ACTIONS ===== */}
            <div
              className="modal-footer"
              style={{
                marginTop: '1.5rem',
                padding: 0,
                border: 'none',
                justifyContent: 'space-between',
              }}
            >
              <div>
                {!stepper.isFirst && (
                  <button
                    className="btn-secondary"
                    type="button"
                    onClick={stepper.prev}
                    disabled={isPending}
                  >
                    Quay lại
                  </button>
                )}
                {stepper.isFirst && (
                  <button
                    className="btn-secondary"
                    type="button"
                    onClick={onClose}
                    disabled={isPending}
                  >
                    Hủy
                  </button>
                )}
              </div>

              <div>
                {!stepper.isLast ? (
                  <button
                    className="primary-button btn-standard"
                    type="button"
                    onClick={handleNextStep}
                    disabled={isPending}
                  >
                    Tiếp tục
                  </button>
                ) : (
                  <button
                    className="primary-button btn-standard"
                    type="submit"
                    disabled={isPending || !isValid || totalRolls === 0}
                  >
                    {isPending ? 'Đang lưu...' : `Lưu ${totalRolls} cuộn`}
                  </button>
                )}
              </div>
            </div>
          </form>
        </>
      )}
    </AdaptiveSheet>
  );
}
