export const INVENTORY_MESSAGES = {
  PAGE_TITLE: 'Tồn kho',
  PAGE_SUBTITLE: 'Quản lý tồn kho sợi, mộc, thành phẩm và phân tích tuổi kho.',

  BTN_ADJUSTMENT: 'Lập phiếu điều chỉnh',
  BTN_HISTORY: 'Lịch sử điều chỉnh',

  TAB_YARN: 'Sợi (Yarn)',
  TAB_RAW: 'Vải mộc',
  TAB_FINISHED: 'Thành phẩm',
  TAB_AGING: 'Tồn lâu (Aging)',
  TAB_HISTORY: 'Lịch sử điều chỉnh',

  LBL_YARN_IN_STOCK: 'Sợi Tồn kho (thực tế)',
  LBL_YARN_TOTAL: 'Tổng SL tồn (kiện)',
  LBL_YARN_WEIGHT: 'Tổng Trọng lượng (kg)',
  LBL_RAW_ROLLS: 'Vải Mộc (Rolls)',
  LBL_RAW_TOTAL: 'Tổng Cuộn Mộc',
  LBL_RAW_LENGTH: 'Tổng mét mộc',
  LBL_FIN_ROLLS: 'Thành Phẩm (Rolls)',
  LBL_FIN_TOTAL: 'Tổng Cuộn TP',
  LBL_FIN_LENGTH: 'Tổng mét TP',

  COL_ROLL_CODE: 'Mã cuộn',
  COL_TYPE: 'Loại',
  COL_FABRIC: 'Loại vải',
  COL_COLOR: 'Màu',
  COL_LOCATION: 'Vị trí',
  COL_AGE_DAYS: 'Ngày tồn',
  COL_SEVERITY: 'Mức',
  COL_QUALITY: 'Chất lượng',
  COL_ROLL_COUNT: 'Cuộn',
  COL_LENGTH: 'Dài (m)',
  COL_WEIGHT: 'Nặng (kg)',
  COL_LOT: 'Lô / Màu',

  ERR_LOAD_AGING: 'Không thể tải danh sách tồn lâu:',
  ERR_LOAD_RAW: 'Không thể tải tồn vải mộc:',
  ERR_LOAD_FIN: 'Không thể tải tồn thành phẩm:',

  VAL_RAW: 'Mộc',
  VAL_FIN: 'TP',
  VAL_RAW_FULL: 'Vải mộc',
  VAL_FIN_FULL: 'Thành phẩm',
  VAL_TOTAL_LENGTH: 'Tổng dài',
  VAL_TOTAL_WEIGHT: 'Trọng lượng',

  LOADING_DATA: 'Đang tải dữ liệu tồn kho...',
  DAYS: 'ngày',

  LBL_YARN_NAME: 'Tên Sợi',
  LBL_LOT_ID: 'Lô',
  LBL_COLOR: 'Màu:',

  MODAL_ADJUSTMENT_TITLE: 'Lập phiếu điều chỉnh',
  LBL_ITEM_TYPE: 'Loại hàng (*)',
  OPT_RAW_FABRIC: 'Vải mộc',
  OPT_FINISHED_FABRIC: 'Vải thành phẩm',
  OPT_YARN: 'Sợi',
  LBL_ITEM_ID: 'Mã cuộn / lô (ID) (*)',
  LBL_ADJUST_REASON: 'Lý do điều chỉnh (*)',
  OPT_REASON_PHYSICAL_COUNT: 'Kiểm kê thực tế',
  OPT_REASON_DAMAGE: 'Hàng hỏng / Rách',
  OPT_REASON_QUALITY_REJECTION: 'Lỗi chất lượng',
  OPT_REASON_SAMPLE_USAGE: 'Cắt mẫu',
  OPT_REASON_PRODUCTION_CONSUMPTION: 'Tiêu hao sản xuất',
  LBL_ADJUST_TYPE: 'Hình thức (*)',
  OPT_TYPE_QUICK: 'Điều chỉnh nhanh (+ / -)',
  OPT_TYPE_PHYSICAL: 'Kiểm đếm vật lý (Actual vs System)',
  LBL_SYS_STOCK: 'Tồn hệ thống',
  LBL_ACTUAL_STOCK: 'Tồn thực tế',
  LBL_DIFF: 'Chênh lệch:',
  LBL_ADJUST_QTY: 'Số lượng điều chỉnh (*)',
  LBL_NOTES: 'Diễn giải / Ghi chú (*)',

  LBL_YARN_CODE: 'Mã sợi',
  LBL_YARN_COLOR: 'Màu sắc',
  LBL_YARN_TOTAL_KG: 'Tổng tồn (kg)',
  LBL_YARN_RESERVED_KG: 'Đã giữ (kg)',
  LBL_YARN_AVAILABLE: 'Khả dụng (Available)',
  LBL_SHORT_TOTAL: 'Tổng',
  LBL_SHORT_RESERVED: 'Giữ chỗ',
  LBL_SHORT_AVAILABLE: 'Khả dụng',

  BTN_CANCEL: 'Hủy',
  BTN_SAVE: 'Lưu điều chỉnh',
  BTN_SAVING: 'Đang lưu...',

  COL_ADJUST_DATE: 'Ngày',
  COL_ADJUST_ITEM_TYPE: 'Loại hàng',
  COL_ADJUST_REASON: 'Lý do',
  COL_ADJUST_BEFORE: 'Trước ĐC',
  COL_ADJUST_QTY: 'Mức ĐC',
  COL_ADJUST_AFTER: 'Sau ĐC',
  COL_ADJUST_STATUS: 'Trạng thái',

  REASON_PHYSICAL_COUNT: 'Kiểm kê',
  REASON_DAMAGE: 'Hàng hỏng',
  REASON_QUALITY_REJECTION: 'Lỗi chất lượng',
  REASON_SAMPLE_USAGE: 'Cắt mẫu',
  REASON_PRODUCTION_CONSUMPTION: 'Tiêu hao SX',
  REASON_SYSTEM_CORRECTION: 'Sửa lỗi HT',

  ERR_ADJUST_HIST: 'Lỗi: ',
  EMPTY_ADJUST_HIST_TITLE: 'Chưa có lịch sử điều chỉnh',
  EMPTY_ADJUST_HIST_DESC:
    'Mọi giao dịch điều chỉnh số lượng tồn kho sẽ hiển thị tại đây.',
};
