export const FINISHED_FABRIC_PAGE_LABELS = {
  PAGE_TITLE: 'Kho Thành Phẩm',
  PAGE_SUBTITLE: 'Quản lý vải thành phẩm sau khi nhuộm và KCS',
  STAT_TOTAL_ROLLS: 'Tổng thành phẩm',
  STAT_TOTAL_ROLLS_DESC: 'Cuộn đã hoàn tất công đoạn nhuộm',
  STAT_TOTAL_LENGTH: 'Tổng chiều dài',
  STAT_TOTAL_LENGTH_DESC: 'Đã kiểm tra chất lượng (QC)',
  STAT_TOTAL_WEIGHT: 'Tổng khối lượng',
  STAT_TOTAL_WEIGHT_DESC: 'Trọng lượng tịnh xuất kho',
} as const;

export const FINISHED_FABRIC_LIST_LABELS = {
  BTN_NEW: 'Nhập mới',
  BTN_BULK_NEW: 'Nhập mẻ',
  BTN_EXPORT: 'Xuất Excel',
  FILTER_FABRIC_LABEL: 'Loại vải',
  FILTER_FABRIC_PLACEHOLDER: 'Tìm loại vải...',
  FILTER_STATUS_LABEL: 'Trạng thái',
  FILTER_QUALITY_LABEL: 'Chất lượng',
  EMPTY_STATE_FILTER_TITLE: 'Không tìm thấy cuộn thành phẩm',
  EMPTY_STATE_DEFAULT_TITLE: 'Chưa có cuộn thành phẩm nào',
  EMPTY_STATE_DEFAULT_DESC: 'Bắt đầu bằng cách nhập thành phẩm mới.',
  COL_ROLL_NUMBER: 'Mã cuộn',
  COL_RAW_ROLL: 'Mộc gốc',
  COL_LOT_NUMBER: 'Số lô',
  COL_FABRIC_TYPE: 'Loại vải / Màu',
  COL_WEIGHT: 'Khối lượng',
  COL_LENGTH: 'Chiều dài',
  COL_STATUS: 'Trạng thái',
  COL_ACTIONS: 'Thao tác',
  LBL_LOT: 'Lô:',
  LBL_NO_LOT: 'KHÔNG CÓ LÔ',
  LBL_CLEAR_FILTER: 'Xóa bộ lọc',
  BTN_EDIT_TITLE: 'Chỉnh sửa',
  BTN_DELETE_TITLE: 'Xóa',
  BTN_TRACE_TITLE: 'Truy vết',
  ERR_LOAD: 'Lỗi tải dữ liệu:',
  ERR_EXPORT: 'Lỗi xuất Excel:',
  CONFIRM_DELETE_MSG: 'Xóa cuộn "{num}"? Hành động này không thể hoàn tác.',
} as const;

export const FINISHED_FABRIC_FORM_LABELS = {
  FORM_TITLE_EDIT: 'Sửa cuộn:',
  FORM_TITLE_NEW: 'Nhập cuộn vải thành phẩm',
  ERR_UNSAVED: 'Bạn có thông tin chưa lưu. Bạn có chắc chắn muốn đóng?',
  LBL_LOT_NUMBER: 'Số lô (Lot number)',
  LBL_LOT_AUTO_HINT: 'Tự động tạo từ Cuộn mộc + Nhà nhuộm + Ngày hoàn thành.',
  LBL_LOT_MANUAL_HINT: 'Nhóm các cuộn cùng lô sản xuất.',
  LBL_ROLL_NUMBER: 'Mã cuộn',
  LBL_FABRIC_TYPE: 'Loại vải',
  LBL_COLOR_NAME: 'Màu vải',
  LBL_COLOR_CODE: 'Mã màu',
  LBL_WIDTH_CM: 'Khổ vải (cm)',
  LBL_LENGTH_M: 'Độ dài (m)',
  LBL_WEIGHT_KG: 'Trọng lượng (kg)',
  LBL_PRODUCTION_DATE: 'Ngày hoàn thành',
  LBL_QUALITY_GRADE: 'Chất lượng',
  LBL_STATUS: 'Trạng thái',
  LBL_WAREHOUSE_LOCATION: 'Vị trí kho',
  LBL_NOTES: 'Ghi chú',
  LBL_RAW_ROLL: 'Cuộn mộc gốc (Tùy chọn)',
  HINT_RAW_ROLL:
    'Nếu cuộn này được nhuộm từ một cuộn mộc có sẵn, chọn mã mộc gốc để truy vết.',
  LBL_DYEING_PARTNER: 'Nhà nhuộm',
  BTN_NEW_PARTNER: '+ Tạo đối tác mới',
  BTN_SAVE_EDIT: 'Lưu thay đổi',
  BTN_SAVE_NEW: 'Nhập kho',
  ERR_PREFIX: 'Lỗi:',
  LBL_UNVERIFIED: 'Chưa kiểm định',
  VAL_CHOOSE_DYER: '— Chọn nhà nhuộm —',
  VAL_CHOOSE_RAW: '— Tìm mã mộc —',
  PLACEHOLDER_COLOR: 'Chọn hoặc nhập màu...',
} as const;

export const FINISHED_FABRIC_BULK_LABELS = {
  FORM_TITLE: 'Nhập nhanh cuộn vải thành phẩm',
  SUCCESS_TITLE: 'Nhập kho thành công',
  SUCCESS_DESC: 'Đã lưu {count} cuộn | {weight} kg',
  SUCCESS_HINT: 'Tùy chọn: xuất danh sách vừa nhập ra file',
  BTN_EXPORT_EXCEL: 'Xuất Excel',
  BTN_EXPORT_PDF: 'Xuất PDF',
  BTN_CLOSE: 'Đóng',
  ERR_PREFIX: 'Lỗi:',
  STEP_GENERAL: 'Cấu hình nhập & Nhảy mã tự động',
  STEP_TABLE: 'Bảng nhập liệu (Data Table)',
  IMPORT_SECTION_TITLE: 'Import từ Excel / CSV',
  IMPORT_HINT: 'Header: Mã cuộn, Cuộn mộc, Cân, Dài, CL, Ghi chú.',
  ERR_IMPORT_EMPTY: 'File không có dữ liệu hoặc không đúng định dạng.',
  ERR_IMPORT_RAW_NOT_FOUND:
    'Chưa tìm thấy cuộn mộc nào trong lô "{lot}". Hãy kiểm tra lại số lô.',
  ERR_IMPORT_RAW_MISSING:
    '{parsedCount} dòng đã nhập. {unresolvedCount} cuộn mộc không tìm thấy trong lô "{lot}": {missing}. Vui lòng chọn lại cuộn mộc cho các dòng này.',
  ERR_IMPORT_READ: 'Lỗi đọc file: {msg}',
  MANUAL_SECTION_TITLE: 'Nhập số tĩnh từng cuộn thành phẩm',
  LOT_MATCH_INFO:
    'Đã ghép {matchedCount} cuộn mộc từ lô. Nhấn nhẹ vào ô để chọn mã cuộn mộc nguồn.',
  LOT_MATRIX_TITLE: 'Lô {lot} | {count} cuộn TP',
  BTN_ADD_ROW: '+ 1 cuộn',
  ADD_ROW_HINT: 'Gõ số tĩnh -> nhấn Enter để chuyển ô tiếp theo',
  BTN_SUBMIT: 'Lưu {count} cuộn',
} as const;

export const FINISHED_FABRIC_BULK_CONFIG_LABELS = {
  TITLE: '1. Thông tin phiếu nhập',
  LBL_LOT_NUMBER: 'Số lô (Lot number)',
  LBL_LOT_PLACEHOLDER: 'Tự động tạo hoặc nhập tay...',
  LBL_LOT_DESC: 'Tự động tạo dựa trên: Cuộn mộc + Nhà nhuộm + Ngày HT.',
  LBL_DYEING_PARTNER: 'Nhà nhuộm',
  VAL_CHOOSE_DYER: '— Chọn đối tác —',
  LBL_FABRIC_TYPE: 'Loại vải',
  VAL_CHOOSE_FABRIC: '— Chọn loại vải —',
  LBL_COLOR: 'Màu sắc (TP)',
  LBL_PRODUCTION_DATE: 'Ngày hoàn thành',
  LBL_WAREHOUSE: 'Vị trí kho',
  TITLE_2: '2. Tự động nhảy mã cuộn TP',
  DESC_2: 'Quy tắc: Prefix + Số thứ tự. VD: TP-1, TP-2...',
  LBL_PREFIX: 'Tiền tố (Prefix)',
  LBL_START_NUMBER: 'Số bắt đầu',
  DESC_PREVIEW: 'Xem trước:',
  LBL_DEFAULT_QUALITY: 'Chất lượng mặc định',
  LBL_DEFAULT_STATUS: 'Trạng thái mặc định',
  TITLE_3: '3. Import từ PO Nhuộm (Tùy chọn)',
  DESC_3: 'Tìm và kéo dữ liệu từ Đơn hàng Nhuộm (Dyeing PO)',
  LBL_DYEING_PO: 'Mã PO Nhuộm',
  VAL_CHOOSE_PO: '— Chọn PO —',
  LBL_PO_ITEM: 'Dòng PO (PO Item)',
  VAL_CHOOSE_PO_ITEM: '— Chọn dòng PO —',
  BTN_APPLY_PO: 'Áp dụng dữ liệu PO',
} as const;

export const FINISHED_FABRIC_TRACE_LABELS = {
  // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
  TITLE: '🔗 Truy vết nguồn gốc',
  BTN_CLOSE: 'Đóng',
  NODE_FINISHED: 'Cuộn thành phẩm',
  NODE_RAW: 'Cuộn vải mộc',
  NODE_YARN: 'Phiếu nhập sợi',
  // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
  LBL_LOT: '📦 Lô:',
  // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
  LBL_WEAVER: '🏠 Nhà dệt:',
  // eslint-disable-next-line no-restricted-syntax -- Allowed string emoji
  LBL_SUPPLIER: '🏢 NCC sợi:',
  LBL_STATUS: 'Trạng thái:',
  LBL_DATE: 'Ngày:',
  LBL_VALUE: 'Giá trị:',
  LBL_YARN_LINES: 'dòng sợi',
  LOADING: 'Đang tải...',
  EMPTY_RAW: 'Không có liên kết cuộn mộc',
  EMPTY_YARN: 'Không có liên kết phiếu nhập sợi',
  STATUS: {
    in_stock: 'Trong kho',
    sold: 'Đã bán',
    reserved: 'Đã giữ',
    defective: 'Lỗi',
    draft: 'Nháp',
    confirmed: 'Đã xác nhận',
    cancelled: 'Đã hủy',
  } as Record<string, string>,
} as const;

export const FINISHED_FABRIC_MODULE_LABELS = {
  FEATURE_TITLE: 'Vải thành phẩm (Lưu kho)',
  FEATURE_DESC:
    'Quản lý tồn kho vải đã nhuộm thành phẩm, sẵn sàng giao hàng hoặc xả kho.',
  PLUGIN_LABEL: 'Kho Thành phẩm',
  PLUGIN_SHORT_LABEL: 'Thành phẩm',
  PLUGIN_DESC: 'Theo dõi tồn kho vải đã nhuộm, nhập kho và xuất kho giao hàng.',
} as const;

export const FINISHED_FABRIC_TRANSITIONS_LABELS = {
  ERR_SHIPPED_EDIT: 'Cuộn đã xuất kho — không thể chỉnh sửa',
  ERR_WRITTEN_OFF_EDIT: 'Cuộn đã xóa sổ — không thể chỉnh sửa',
  ERR_SHIPPED_DEL: 'Cuộn đã xuất kho — không thể xóa',
  ERR_RESERVED_DEL: 'Cuộn đang được đặt trước — không thể xóa',
  ERR_DAMAGED_DEL: 'Cuộn hư hỏng — không thể xóa, hãy giữ để kiểm tra',
  ERR_WRITTEN_OFF_DEL: 'Cuộn đã xóa sổ — không thể xóa',
} as const;
